// Generated by gen_shim.py from 6rbc.app -- do not edit.
//
// Which import index each diversion sits at in THIS game. See HOOKS in
// gen_shim.py for what each one is; 65535 means the game never imports it
// and the guards in gate6.cpp then leave that hook uninstalled.
//
// GAME_UID3 is the image these indices were read out of. The loader
// checks it against the image it is actually given, because this
// header and gate4_shim.cpp are generated as a pair from one game
// and are meaningless against another -- and a wrong index is not an
// error, it is a call to the wrong function.
#ifndef GATE_IMPORTS_H
#define GATE_IMPORTS_H

enum { GAME_UID3 = 0x101fd42d };

enum {
    IMPORT_ADDDF3                      =   405,
    IMPORT_ADDTOSTACKL                 =    51,
    IMPORT_ADD_EVENT                   = 65535,   // absent
    IMPORT_ADD_FOREGROUND_OBSERVER     =    50,
    IMPORT_AKN_CBA                     = 65535,   // absent
    IMPORT_AKN_STATUS_PANE             = 65535,   // absent
    IMPORT_APPUI_EXIT                  = 65535,   // absent
    IMPORT_APPUI_FACTORY               = 65535,   // absent
    IMPORT_APPUI_PREPARE_EXIT          =    33,
    IMPORT_APP_FULL_NAME               =     0,
    IMPORT_APP_RECT                    =   172,
    IMPORT_BASECONSTRUCTL              =     9,
    IMPORT_BMU_BEGIN                   = 65535,   // absent
    IMPORT_BMU_END                     = 65535,   // absent
    IMPORT_CACTIVE_CTOR                = 65535,   // absent
    IMPORT_CANCEL                      =   279,
    IMPORT_CHUNK_CREATE_GLOBAL         = 65535,   // absent
    IMPORT_CLEANUP_NEW                 =   330,
    IMPORT_CLIENT_RECT                 = 65535,   // absent
    IMPORT_COECONTROL_CTOR             =    89,
    IMPORT_COEENV_STATIC               =    86,
    IMPORT_CREATEWINDOWL               =    55,
    IMPORT_CREATE_BITMAP               = 65535,   // absent
    IMPORT_CREATE_CONTEXT              = 65535,   // absent
    IMPORT_CREATE_SESSION              =   298,
    IMPORT_CTIMER_CTOR                 =   391,
    IMPORT_CTIMER_DOCANCEL             =   306,
    IMPORT_CTIMER_DTOR                 =   379,
    IMPORT_CTL_DRAWABLE_WINDOW         = 65535,   // absent
    IMPORT_CTL_RECT                    = 65535,   // absent
    IMPORT_CTL_SETRECT                 =    98,
    IMPORT_DEF_MODE_COLORS             = 65535,   // absent
    IMPORT_DELETE_OP                   =   408,
    IMPORT_DES_FORMAT                  =   314,
    IMPORT_DES_FORMATLIST              = 65535,   // absent
    IMPORT_DIVDF3                      = 65535,   // absent
    IMPORT_DLL_NAME                    =     2,
    IMPORT_DSA_NEWL                    =   460,
    IMPORT_DSA_STARTL                  =   461,
    IMPORT_EQDF2                       = 65535,   // absent
    IMPORT_EXIT                        =   308,
    IMPORT_EXTENDSFDF2                 =   413,
    IMPORT_FBS_BITMAP_CREATE           =   427,
    IMPORT_FBS_BITMAP_CTOR             =   430,
    IMPORT_FBS_DATA_ADDRESS            =   428,
    IMPORT_FBS_DISPLAY_MODE            = 65535,   // absent
    IMPORT_FILEMAN_NEWL                = 65535,   // absent
    IMPORT_FILE_CREATE                 =   101,
    IMPORT_FILE_OPEN                   =   109,
    IMPORT_FILE_READ                   =   110,
    IMPORT_FILE_READ_POS               = 65535,   // absent
    IMPORT_FILE_READ_STATIC            =   110,
    IMPORT_FILE_REPLACE                =   111,
    IMPORT_FILE_SIZE                   =   115,
    IMPORT_FIND_WILD_BY_DIR            = 65535,   // absent
    IMPORT_FIXDFSI                     = 65535,   // absent
    IMPORT_FLOATSIDF                   =   415,
    IMPORT_FOPEN                       =   226,
    IMPORT_FS_CONNECT                  =   100,
    IMPORT_FS_ENTRY                    = 65535,   // absent
    IMPORT_FS_MKDIRALL                 =   106,
    IMPORT_FS_MODIFIED                 = 65535,   // absent
    IMPORT_FS_SESSION_PATH             = 65535,   // absent
    IMPORT_FS_SET_DEFAULT_PATH         = 65535,   // absent
    IMPORT_FS_VOLUME                   = 65535,   // absent
    IMPORT_GC_SETCLIP                  =    46,
    IMPORT_GEDF2                       = 65535,   // absent
    IMPORT_GTDF2                       = 65535,   // absent
    IMPORT_HANDLE_CLOSE                =   281,
    IMPORT_LEAVE                       =   324,
    IMPORT_LEAVE_IF_ERROR              =   322,
    IMPORT_LEAVE_NOMEM                 =   323,
    IMPORT_LEDF2                       = 65535,   // absent
    IMPORT_LEX16_VAL_REAL              = 65535,   // absent
    IMPORT_LIBRARY_LOAD                =   325,
    IMPORT_LIBRARY_LOOKUP              =   326,
    IMPORT_LTDF2                       = 65535,   // absent
    IMPORT_MALLOC                      =   215,
    IMPORT_MATH_ACOS                   = 65535,   // absent
    IMPORT_MATH_ASIN                   = 65535,   // absent
    IMPORT_MATH_ATAN                   = 65535,   // absent
    IMPORT_MATH_ATAN2                  = 65535,   // absent
    IMPORT_MATH_COS                    = 65535,   // absent
    IMPORT_MATH_EXP                    = 65535,   // absent
    IMPORT_MATH_FRAC                   = 65535,   // absent
    IMPORT_MATH_FRAND                  = 65535,   // absent
    IMPORT_MATH_INT                    = 65535,   // absent
    IMPORT_MATH_INT16                  = 65535,   // absent
    IMPORT_MATH_INT_D                  = 65535,   // absent
    IMPORT_MATH_LN                     = 65535,   // absent
    IMPORT_MATH_LOG                    = 65535,   // absent
    IMPORT_MATH_MOD                    = 65535,   // absent
    IMPORT_MATH_POW                    = 65535,   // absent
    IMPORT_MATH_ROUND                  = 65535,   // absent
    IMPORT_MATH_SIN                    = 65535,   // absent
    IMPORT_MATH_SQRT                   = 65535,   // absent
    IMPORT_MATH_TAN                    = 65535,   // absent
    IMPORT_MDA_NEWL                    =   458,
    IMPORT_MKDIR                       = 65535,   // absent
    IMPORT_MSG_COMPLETE                =   285,
    IMPORT_MULDF3                      =   418,
    IMPORT_NEDF2                       = 65535,   // absent
    IMPORT_NEGDF2                      = 65535,   // absent
    IMPORT_PANIC                       =   338,
    IMPORT_PUSHL_CBASE                 =   345,
    IMPORT_READ_FILE_SECTION           = 65535,   // absent
    IMPORT_REQUEST_COMPLETE            =   350,
    IMPORT_RWIN_BEGIN_REDRAW           = 65535,   // absent
    IMPORT_RWIN_CTOR                   = 65535,   // absent
    IMPORT_RWIN_CTOR_WS                = 65535,   // absent
    IMPORT_RWIN_END_REDRAW             = 65535,   // absent
    IMPORT_SCREEN_INFO                 =   356,
    IMPORT_SCREEN_UPDATE               =    47,
    IMPORT_SDPDB_CLOSE                 = 65535,   // absent
    IMPORT_SDPDB_CREATE_RECORD         = 65535,   // absent
    IMPORT_SDPDB_CTOR                  = 65535,   // absent
    IMPORT_SDPDB_DELETE_RECORD         = 65535,   // absent
    IMPORT_SDPDB_OPEN                  = 65535,   // absent
    IMPORT_SDPDB_UPDATE_DES16          = 65535,   // absent
    IMPORT_SDPDB_UPDATE_UINT           = 65535,   // absent
    IMPORT_SDPDB_UPDATE_VALUE          = 65535,   // absent
    IMPORT_SDP_NEW_DES                 = 65535,   // absent
    IMPORT_SEM_CREATE                  =   296,
    IMPORT_SEM_WAIT                    =   374,
    IMPORT_SEND_RECEIVE                =   357,
    IMPORT_SERVER_STARTL               =   366,
    IMPORT_SET_AUTO_UPDATE             =    45,
    IMPORT_SHADOW_BUFFLAT              = 65535,   // absent
    IMPORT_SHADOW_CMDLINE              = 65535,   // absent
    IMPORT_SHADOW_DESC16FLAT           = 65535,   // absent
    IMPORT_SHADOW_DESC8FLAT            = 65535,   // absent
    IMPORT_SHADOW_FILEMAN              = 65535,   // absent
    IMPORT_SHADOW_MSVSESSION           = 65535,   // absent
    IMPORT_SHADOW_PERIODIC             =   329,
    IMPORT_SHADOW_SCREENDEVICE         = 65535,   // absent
    IMPORT_SHADOW_SDPAGENT             = 65535,   // absent
    IMPORT_SHADOW_SDPPATTERN           = 65535,   // absent
    IMPORT_SHADOW_WGNAME               = 65535,   // absent
    IMPORT_SOCK_RECV1                  = 65535,   // absent
    IMPORT_SOCK_WRITE                  = 65535,   // absent
    IMPORT_START_APP                   = 65535,   // absent
    IMPORT_SUBDF3                      = 65535,   // absent
    IMPORT_SYSTEM_GC                   = 65535,   // absent
    IMPORT_THREAD_CREATE               =   299,
    IMPORT_THREAD_OPEN                 =   337,
    IMPORT_THREAD_RESUME               =   353,
    IMPORT_THREAD_SUSPEND              =   370,
    IMPORT_TRUNCDFSF2                  =   423,
    IMPORT_UNLINK                      = 65535,   // absent
    IMPORT_USER_AFTER                  =   267,
    IMPORT_USER_ALLOC                  =   270,
    IMPORT_USER_ALLOCL                 =   269,
    IMPORT_USER_ALLOCZ                 =   421,
    IMPORT_USER_ALLOCZL                =   265,
    IMPORT_USER_FREE_OP                =   315,
    IMPORT_VEC_DELETE_OP               =   410,
    IMPORT_WAIT_FOR_REQUEST            = 65535,   // absent
    IMPORT_WFOPEN                      = 65535,   // absent
    IMPORT_WINDOW                      =    87,
    IMPORT_WS_EVENT_READY              = 65535,   // absent
    IMPORT_WS_GET_EVENT                = 65535,   // absent
};

// Imports that are a method on CCoeEnv. The game holds a copy of the
// environment laid out the old way; cone has to be given the real one.
//     75  CCoeEnv::RemoveForegroundObserver(MCoeForegroundObserver &)
#define GATE_COEENV_METHODS  75
#define GATE_COEENV_METHOD_COUNT 1

// Methods on CEikAppUi. A null `this` from the game is replaced
// with the real app UI, when the game asks for it (GAME_FIX_APPUI_THIS).
#define GATE_APPUI_METHODS  121, 125, 128, 135, 137, 139, 140, 141, 147, 149, 153, 155, 156, 157, 162, 163
#define GATE_APPUI_METHOD_COUNT 16

// The trace lists: see MILESTONES and HOT in gen_shim.py. Both may be
// empty, which is why gate6.cpp appends the two exits to the first.
#define GATE_MILESTONES  460, 461, 100, 109, 110, 99, 325, 326, 283, 45, 46, 350, 296, 299, 362, 353, 374, 281, 330, 386, 319, 363, 322, 367, 298, 357, 295, 397, 366, 355, 400, 285, 376, 339, 458, 323, 315, 111, 104, 107, 102,
#define GATE_HOT  424, 425, 274, 287, 272, 417, 383, 369, 389, 264, 344,
#define GATE_HOT_COUNT 11

// The diversions: see DIVERTS in gen_shim.py. {import, register,
// which wrapper}, and an import the game does not have is left out.
#define GATE_DIVERTS  { 172, 1, 0 }, { 98, 0, 1 }, { 49, 0, 1 }, { 68, 0, 1 }, { 71, 0, 1 }, { 82, 1, 1 }, { 76, 1, 1 }, { 20, 0, 0 }, { 22, 0, 0 }, { 46, 0, 3 }, { 286, 0, 2 }, { 268, 0, 2 }, { 266, 0, 2 }, { 358, 0, 2 },
#define GATE_DIVERT_COUNT 14

#endif
