// Generated by gen_shim.py from 6r21.app -- do not edit.
//
// Which import index each diversion sits at in THIS game. See HOOKS in
// gen_shim.py for what each one is; 65535 means the game never imports it
// and the guards in gate6.cpp then leave that hook uninstalled.
//
// GAME_UID3 is the image these indices were read out of. The loader
// checks it against the image it is actually given, because this
// header and gate4_shim.cpp are generated as a pair from one game
// and are meaningless against another -- and a wrong index is not an
// error, it is a call to the wrong function.
#ifndef GATE_IMPORTS_H
#define GATE_IMPORTS_H

enum { GAME_UID3 = 0x101fd3e9 };

enum {
    IMPORT_ADDDF3                      =   290,
    IMPORT_ADDTOSTACKL                 =    39,
    IMPORT_ADD_FOREGROUND_OBSERVER     = 65535,   // absent
    IMPORT_APPUI_EXIT                  =   109,
    IMPORT_APPUI_FACTORY               = 65535,   // absent
    IMPORT_APP_FULL_NAME               =     0,
    IMPORT_APP_RECT                    =   151,
    IMPORT_BASECONSTRUCTL              =    13,
    IMPORT_CACTIVE_CTOR                =   284,
    IMPORT_CANCEL                      =   192,
    IMPORT_CLEANUP_NEW                 =   232,
    IMPORT_CLIENT_RECT                 = 65535,   // absent
    IMPORT_COECONTROL_CTOR             =    77,
    IMPORT_COEENV_STATIC               =    74,
    IMPORT_CREATEWINDOWL               =    43,
    IMPORT_CREATE_CONTEXT              =    31,
    IMPORT_CREATE_SESSION              = 65535,   // absent
    IMPORT_CTIMER_CTOR                 =   279,
    IMPORT_CTIMER_DOCANCEL             =   208,
    IMPORT_CTIMER_DTOR                 =   269,
    IMPORT_CTL_DRAWABLE_WINDOW         =    45,
    IMPORT_CTL_RECT                    =    64,
    IMPORT_CTL_SETRECT                 =    85,
    IMPORT_DELETE_OP                   =   292,
    IMPORT_DES_FORMAT                  =   213,
    IMPORT_DES_FORMATLIST              =   212,
    IMPORT_DIVDF3                      =   296,
    IMPORT_DLL_NAME                    = 65535,   // absent
    IMPORT_DSA_NEWL                    = 65535,   // absent
    IMPORT_DSA_STARTL                  = 65535,   // absent
    IMPORT_EQDF2                       = 65535,   // absent
    IMPORT_EXIT                        = 65535,   // absent
    IMPORT_EXTENDSFDF2                 = 65535,   // absent
    IMPORT_FILEMAN_NEWL                = 65535,   // absent
    IMPORT_FILE_CREATE                 = 65535,   // absent
    IMPORT_FILE_OPEN                   =    92,
    IMPORT_FILE_READ                   = 65535,   // absent
    IMPORT_FILE_READ_POS               =    94,
    IMPORT_FILE_READ_STATIC            = 65535,   // absent
    IMPORT_FILE_REPLACE                =    95,
    IMPORT_FILE_SIZE                   =    96,
    IMPORT_FIND_WILD_BY_DIR            = 65535,   // absent
    IMPORT_FIXDFSI                     = 65535,   // absent
    IMPORT_FLOATSIDF                   =   298,
    IMPORT_FS_CONNECT                  =    87,
    IMPORT_FS_ENTRY                    = 65535,   // absent
    IMPORT_FS_SET_DEFAULT_PATH         = 65535,   // absent
    IMPORT_FS_VOLUME                   = 65535,   // absent
    IMPORT_GEDF2                       = 65535,   // absent
    IMPORT_GTDF2                       = 65535,   // absent
    IMPORT_LEAVE                       =   225,
    IMPORT_LEAVE_IF_ERROR              =   222,
    IMPORT_LEAVE_NOMEM                 =   224,
    IMPORT_LEDF2                       = 65535,   // absent
    IMPORT_LIBRARY_LOAD                = 65535,   // absent
    IMPORT_LIBRARY_LOOKUP              = 65535,   // absent
    IMPORT_LTDF2                       =   302,
    IMPORT_MALLOC                      = 65535,   // absent
    IMPORT_MATH_ACOS                   = 65535,   // absent
    IMPORT_MATH_ASIN                   = 65535,   // absent
    IMPORT_MATH_ATAN                   = 65535,   // absent
    IMPORT_MATH_ATAN2                  = 65535,   // absent
    IMPORT_MATH_COS                    = 65535,   // absent
    IMPORT_MATH_EXP                    = 65535,   // absent
    IMPORT_MATH_FRAC                   = 65535,   // absent
    IMPORT_MATH_FRAND                  = 65535,   // absent
    IMPORT_MATH_INT                    =   220,
    IMPORT_MATH_INT16                  = 65535,   // absent
    IMPORT_MATH_INT_D                  = 65535,   // absent
    IMPORT_MATH_LN                     = 65535,   // absent
    IMPORT_MATH_LOG                    = 65535,   // absent
    IMPORT_MATH_MOD                    = 65535,   // absent
    IMPORT_MATH_POW                    =   238,
    IMPORT_MATH_ROUND                  = 65535,   // absent
    IMPORT_MATH_SIN                    =   253,
    IMPORT_MATH_SQRT                   = 65535,   // absent
    IMPORT_MATH_TAN                    = 65535,   // absent
    IMPORT_MDA_NEWL                    =   340,
    IMPORT_MSG_COMPLETE                = 65535,   // absent
    IMPORT_MULDF3                      =   305,
    IMPORT_NEDF2                       = 65535,   // absent
    IMPORT_NEGDF2                      = 65535,   // absent
    IMPORT_PANIC                       =   234,
    IMPORT_PUSHL_CBASE                 =   242,
    IMPORT_READ_FILE_SECTION           =    93,
    IMPORT_REQUEST_COMPLETE            = 65535,   // absent
    IMPORT_SCREEN_INFO                 = 65535,   // absent
    IMPORT_SCREEN_UPDATE               = 65535,   // absent
    IMPORT_SEM_CREATE                  =   200,
    IMPORT_SEM_WAIT                    =   265,
    IMPORT_SEND_RECEIVE                = 65535,   // absent
    IMPORT_SERVER_STARTL               = 65535,   // absent
    IMPORT_SET_AUTO_UPDATE             = 65535,   // absent
    IMPORT_SUBDF3                      =   310,
    IMPORT_SYSTEM_GC                   =    75,
    IMPORT_THREAD_CREATE               =   202,
    IMPORT_THREAD_OPEN                 = 65535,   // absent
    IMPORT_THREAD_RESUME               =   247,
    IMPORT_THREAD_SUSPEND              = 65535,   // absent
    IMPORT_TRUNCDFSF2                  = 65535,   // absent
    IMPORT_USER_ALLOC                  =   184,
    IMPORT_USER_ALLOCL                 =   182,
    IMPORT_USER_ALLOCZ                 =   308,
    IMPORT_USER_ALLOCZL                =   177,
    IMPORT_USER_FREE_OP                =   214,
    IMPORT_VEC_DELETE_OP               =   294,
    IMPORT_WINDOW                      = 65535,   // absent
};

// Imports that are a method on CCoeEnv. The game holds a copy of the
// environment laid out the old way; cone has to be given the real one.
//    152  CEikonEnv::DenseFont() const
#define GATE_COEENV_METHODS  152
#define GATE_COEENV_METHOD_COUNT 1

// Methods on CEikAppUi. A null `this` from the game is replaced
// with the real app UI, when the game asks for it (GAME_FIX_APPUI_THIS).
#define GATE_APPUI_METHODS  101, 104, 112, 114, 116, 117, 118, 125, 127, 131, 133, 134, 135, 140, 141
#define GATE_APPUI_METHOD_COUNT 15

// The trace lists: see MILESTONES and HOT in gen_shim.py. Both may be
// empty, which is why gate6.cpp appends the two exits to the first.
#define GATE_MILESTONES  87, 92, 86, 200, 202, 250, 247, 265, 193, 232, 275, 219, 252, 222, 256, 340, 224, 214,
#define GATE_HOT  312, 189, 304, 273, 260, 276, 176, 241,
#define GATE_HOT_COUNT 8

// The diversions: see DIVERTS in gen_shim.py. {import, register,
// which wrapper}, and an import the game does not have is left out.
#define GATE_DIVERTS  { 151, 1, 0 }, { 85, 0, 1 }, { 38, 0, 1 }, { 45, 0, 1 }, { 64, 1, 1 }, { 59, 0, 1 }, { 70, 1, 1 }, { 65, 1, 1 }, { 15, 0, 0 }, { 17, 0, 0 }, { 196, 0, 2 }, { 180, 0, 2 }, { 178, 0, 2 }, { 249, 0, 2 },
#define GATE_DIVERT_COUNT 14

#endif
