// Step 3: the wrapper.
//
// Gate 4 loaded the N-Gage binary and ran its code; gate 5 made this a real
// S60v3 GUI application. This joins them. The framework asks for a
// CApaApplication; the game's own NewApplication builds one, but it is an
// old-ABI object the 9.x framework cannot call. So hand the framework a
// 9.x-layout object of our own whose slots dispatch into the old one -- which
// is what gate 3 proved works, now against an object the game really built.
//
// Read 6RBC.APP, copy its code into an executable chunk, rebase it with its own
// relocation table, point all 462 imports at stubs, and enter it.  The game is
// an EKA1 polymorphic DLL, so "enter it" means its entry point and then export
// ordinal 1, CApaApplication's factory.
//
// The result is reported as a panic, because that is the only channel a phone
// gives us.  The category says how far it got and the reason says which import
// its code reached first -- and reaching an import at all is the whole point:
// it means the game's own instructions ran, on hardware they were never built
// for, and called out through our table.

typedef unsigned char u8;
typedef unsigned short u16;
typedef unsigned int u32;
typedef int i32;

extern "C" {
void user_panic(const void *category, int reason);
void *user_alloc(int size);
i32 chunk_createlocalcode(void *chunk, int size, int maxSize, int owner);
u8 *chunk_base(const void *chunk);
i32 fs_connect(void *fs, int slots);
i32 file_open(void *file, void *fs, const void *name, u32 mode);
i32 file_size(const void *file, int *size);
i32 file_read(const void *file, void *des);
i32 rlibrary_load(void *lib, const void *name, const void *path);
void *rlibrary_lookup(const void *lib, int ordinal);

// Generated by gen_shim.py: which 9.x DLL and ordinal answers each old import.
extern const unsigned short *const kShimDllName[];
extern const unsigned char kShimDllLen[];
extern const u32 kShimDllCount;
extern const u32 kShimTable[];
extern const u32 kShimCount;
}

// TDesC16 and TDes8: a length word whose top four bits are the descriptor type,
// then (for a modifiable one) a maximum length, then the data pointer.
enum { EPtrC = 1, EPtr = 2, KTypeShift = 28 };

struct Ptrc16 { u32 lengthAndType; const u16 *text; };
struct Ptr8 { u32 lengthAndType; int maxLength; u8 *ptr; };

// Every import gets a slot big enough for whichever thunk it needs.
enum { SLOT = 48 };
enum { KIND_CALL = 1, KIND_REM = 2, KIND_LOCAL = 3, KIND_ARG3 = 4, KIND_SRET8 = 5 };
enum { LOCAL_NEGSF2 = 0, LOCAL_PURE_VIRTUAL = 1, LOCAL_NOOP = 2, LOCAL_MEM_COMPARE = 3,
       LOCAL_TRAP_ENTER = 4, LOCAL_TINT64_SET = 5 };

static void panic(const u16 *cat, int catLen, int reason)
{
    Ptrc16 d;
    d.lengthAndType = ((u32)EPtrC << KTypeShift) | (u32)catLen;
    d.text = cat;
    user_panic(&d, reason);
}

#define PANIC(name, reason) do { \
    static const u16 s[] = name; \
    panic(s, (int)(sizeof s / sizeof s[0]), (reason)); } while (0)

#define CAT_FS  {'G','6','F','S'}
#define CAT_MEM {'G','6','M','E','M'}
#define CAT_HDR {'G','6','H','D','R'}
#define CAT_IMP {'G','6','I','M','P'}
#define CAT_RET {'G','6','R','E','T'}
#define CAT_LIB {'G','6','L','I','B'}
#define CAT_SHIM {'G','6','S','H','M'}
#define CAT_NUL {'G','6','N','U','L'}
#define CAT_PURE {'G','6','P','U','R'}

// The EKA1 header, at the offsets EKA2L1's loader reads.
struct E32 {
    u32 uid1, uid2, uid3, check, sig, cpu;
    u32 pad, compression, petran, timeLo, timeHi;
    u32 flags, codeSize, dataSize, heapMin, heapMax, stackSize, bssSize;
    u32 entryPoint, codeBase, dataBase, dllRefCount;
    u32 exportDirOffset, exportDirCount, textSize;
    u32 codeOffset, dataOffset, importOffset, codeRelocOffset, dataRelocOffset;
};

static const u16 kPath0[] = {'E',':','\\','6','r','b','c','.','a','p','p'};
static const u16 kPath1[] = {'C',':','\\','6','r','b','c','.','a','p','p'};
static const u16 kPath2[] = {'E',':','\\','s','y','s','t','e','m','\\','a','p','p','s','\\',
                             '6','r','b','c','\\','6','r','b','c','.','a','p','p'};

// Every import points here, through a 16-byte stub carrying its own report
// code. That code is `import count * 1000 + index`, because a panic gives us
// one integer and which binary was loaded is half the answer: this game ships
// both as a 1.6 MB image with 462 imports and as a 4 KB loader stub with 41,
// and an index alone cannot tell them apart. Keeping it in the stub also keeps
// this program free of writable globals, which the image has no room for --
// it declares no .bss.
extern "C" void gate6_report(int code)
{
    PANIC(CAT_IMP, code);
}

// A call through a vtable slot the old binary never filled in.
extern "C" void gate6_pure_virtual()
{
    PANIC(CAT_PURE, 0);
}

// Only the 16-bit Mem::Compare is still exported, so the 8-bit one lives here.
// Symbian's contract: compare the common prefix, then the lengths.
extern "C" int gate6_mem_compare(const u8 *a, int la, const u8 *b, int lb)
{
    const int n = (la < lb) ? la : lb;
    for (int i = 0; i < n; i++)
        if (a[i] != b[i])
            return (int)a[i] - (int)b[i];
    return la - lb;
}

extern "C" {
void eikstart_runapplication(u32 type, u32 data, u32 cached, u32 spare);
void eikapplication_ctor(void *self);                 // CEikApplication::CEikApplication()
void akndocument_ctor(void *self, void *app);         // CAknDocument::CAknDocument(CEikApplication&)
void coeappui_ctor(void *self);                       // CCoeAppUi::CCoeAppUi()
void eikappui_ctor(void *self);                       // CEikAppUi::CEikAppUi()
void eikappui_baseconstructl(void *self, int flags);  // CEikAppUi::BaseConstructL(TInt)
void *coeenv_static(void);                            // CCoeEnv::Static()
i32 user_setexceptionhandler(void *handler, u32 mask); // User::SetExceptionHandler
void *coecontrol_ctor(void *self);                    // CCoeControl::CCoeControl()
void coecontrol_createwindowl(void *self);            // CCoeControl::CreateWindowL()
void *user_allocz(int size);

// A GCC98r2 virtual call: the vptr is at offset 0 and points eight bytes
// before slot 0. Arguments past `this` are not passed, which is all the old
// slots reached from here need.
u32 old_call(const void *object, int slot);
}

#define CAT_CHN {'G','6','C','H','N'}
#define CAT_FLT {'G','6','F','L','T'}
#define CAT_UID {'G','6','U','I','D'}

// Two object graphs, not one. The 9.x framework gets objects of its own,
// constructed the ordinary way from exported constructors, and the game keeps
// the objects its own code built. A wrapper holds a pointer to its counterpart
// and forwards only the slots the game actually overrides; everything the game
// inherited stays with the 9.x implementation, which then runs against a 9.x
// object as it expects. Bridging an inherited slot instead sends the framework
// through the game's veneers back into 9.x code with `this` pointing at the old
// object, and it faults -- which is what the first attempt at this did.
//
// The game's own overrides, from its vtables:
//
//   application  0 destructor   3 AppDllUid    12 CreateDocumentL()   13 ?
//   document     0 destructor   9 ?            17 CreateAppUiL()
//
// AppDllUid is the exception: see below.
//
// Destructors stay 9.x: the wrapper is a real 9.x object and has to be torn
// down as one. The old objects leak, which for now costs nothing.
enum { VT_HEADER = 2 };
enum { APP_SLOTS = 18, SLOT_APP_DLL_UID = 5, SLOT_CREATE_DOCUMENT = 17 };
enum { DOC_SLOTS = 34, SLOT_CREATE_APP_UI = 19 };
enum { UI_SLOTS = 48, SLOT_UI_CONSTRUCT = 16 };

enum { OLD_CREATE_DOCUMENT = 12, OLD_UI_CONSTRUCT = 13, OLD_CREATE_APP_UI = 17 };

// The game's app UI ConstructL, old slot 13: BaseConstructL(0), then a trap
// harness, then it builds a control, asks for ApplicationRect, pushes the
// control on the stack, and sets the key block mode -- every one of them a
// framework method called on the old object. Slot 17 is HandleCommandL, which
// compares its argument against 0x100; slot 13 is what is left.
enum { IMPORT_BASECONSTRUCTL = 9 };     // avkon CAknAppUi::BaseConstructL(TInt)

// The control. ConstructL builds one, and unlike the application, the document
// and the app UI, the game constructs it itself -- so its base class has to be
// right, not just wrapped. The N-Gage ROM says what right is:
//
//   CCoeControl   iCoeEnv 0x08   iWin 0x20        (9.x: 0x0c and 0x28)
//   CCoeEnv       iWsSession 0x20  iRootWin 0x2c  iSystemGc 0x34  iScreen 0x3c
//
// and 9.x CCoeEnv holds the same four twelve bytes further along -- measured in
// both ROMs, at all four. The whole tail moved together, so the game can be
// given the real environment as a pointer twelve bytes past it, and every old
// offset it reads lands on the right 9.x field. No copy, no synthetic object:
// the game gets the real window server session and the real screen device, by
// reference, through its own layout.
enum { COEENV_BIAS = 0x0c };
enum { OLD_CONTROL_BYTES = 0x30, OLD_CONTROL_COEENV = 0x08, OLD_CONTROL_WIN = 0x20 };
enum { NEW_CONTROL_WIN = 0x28 };

enum { IMPORT_DLL_NAME = 2 };           // apparc CApaApplication::DllName() const
enum { IMPORT_COEENV_STATIC = 86 };     // cone CCoeEnv::Static()
enum { IMPORT_COECONTROL_CTOR = 89 };   // cone CCoeControl::CCoeControl()
enum { IMPORT_CREATEWINDOWL = 55 };     // cone CCoeControl::CreateWindowL()
enum { IMPORT_WINDOW = 87 };            // cone CCoeControl::Window() const

// The rest of what ConstructL calls on itself keeps its 9.x implementation and
// only needs the old object swapped for the wrapper. ApplicationRect returns a
// TRect, so r0 is the return buffer and `this` is in r1.
enum { ON_APP_UI = 0, ON_CONTROL = 1 };

struct Divert { u16 import; u8 arg; u8 object; };
static const Divert kDiverts[] = {
    { 172, 1, ON_APP_UI },      // eikcore  CEikAppUi::ApplicationRect() const
    {  39, 0, ON_APP_UI },      // avkon    CAknAppUi::SetKeyBlockMode(TAknKeyBlockMode)
    {  98, 0, ON_CONTROL },     // cone     the Nokia export standing in for SetRect
    {  49, 0, ON_CONTROL },     // cone     CCoeControl::ActivateL()
};

// AddToStackL is the one that needs both at once: the app UI it is called on
// and the control it is handed.
enum { IMPORT_ADDTOSTACKL = 51 };

// EIKAPPUI.H, as gate 5 established.
enum { ENoAppResourceFile = 0x01, ENoScreenFurniture = 0x04 };

// This program has no writable globals -- the image declares no .bss -- so each
// wrapper carries its counterpart itself, parked well past the end of any real
// 9.x object in the 2 KB we give it.
enum { WRAP_BYTES = 2048, WRAP_OLD = WRAP_BYTES / 4 - 1, WRAP_CTX = WRAP_BYTES / 4 - 2 };

// What the shim needs to know and cannot keep in a global. Every wrapper holds
// a pointer to it, so any of them can find it from `this`.
struct Context {
    u32 *wrapUi;
    u32 *wrapControl;
    const u16 *path;        // where the game was loaded from
    int pathLen;
    u32 lastImport;         // the last import the game called: see the tracer
};

static Context *context_of(const void *wrapper)
{
    return (Context *)((const u32 *)wrapper)[WRAP_CTX];
}

static const u32 *vtable_of(const u32 *object)
{
    return (const u32 *)object[0] - VT_HEADER;
}

static u32 *copy_vtable(const u32 *real, int slots)
{
    u32 *vt = (u32 *)user_allocz((VT_HEADER + slots) * 4);
    if (!vt) PANIC(CAT_MEM, -30);
    for (int i = 0; i < VT_HEADER + slots; i++)
        vt[i] = real[i];
    return vt;
}

// The other direction. When the game calls a framework method on itself, the
// 9.x implementation must not see the old object, so the call is diverted to
// one of ours -- which needs the context, and gets it in r2:
//
//   ldr r2, [pc, #4]    @ the context, baked in when the stub is built
//   ldr pc, [pc, #4]    @ and on to our implementation
//   .word context
//   .word our function
//
// r0 and r1 pass through untouched, so the old arguments arrive as they were.
static u32 ctx_thunk(u8 *code, const void *ctx, u32 target)
{
    u32 *b = (u32 *)code;
    b[0] = 0xE59F2004;                  // ldr r2, [pc, #4]
    b[1] = 0xE59FF004;                  // ldr pc, [pc, #4]
    b[3] = (u32)ctx;
    b[4] = target;
    return (u32)b;
}

// The simpler diversion: the 9.x implementation is the right one, it just must
// not be handed the old object. The wrapper does not exist when the stub is
// built, so the thunk reads it from the context each time:
//
//   ldr rN, [pc, #8]    @ rN = the cell holding the wrapper
//   ldr rN, [rN]
//   ldr pc, [pc, #4]
//   .word cell
//   .word the 9.x function
static u32 this_thunk(u8 *code, const void *cell, u32 target, int reg)
{
    u32 *b = (u32 *)code;
    b[0] = 0xE59F0008 | ((u32)reg << 12);           // ldr rN, [pc, #8]
    b[1] = 0xE5900000 | ((u32)reg << 16) | ((u32)reg << 12);
    b[2] = 0xE59FF004;                              // ldr pc, [pc, #4]
    b[4] = (u32)cell;
    b[5] = target;
    return (u32)b;
}

// A phone reports a fault as KERN-EXEC 3 and nothing else -- no address, no
// instruction. So every import the game makes goes through this first, which
// records which one it was and jumps on. r0 and r12 are saved across the
// record; lr is the caller's and is never touched, and neither are the flags.
//
//   stmdb sp!, {r0, r12}
//   ldr   r0, [pc, #12]     @ where to record it
//   ldr   r12, [pc, #12]    @ which import
//   str   r12, [r0]
//   ldmia sp!, {r0, r12}
//   ldr   pc, [pc, #4]      @ and on to whatever answers it
enum { TRACE = 48 };

static u32 trace_thunk(u8 *code, const void *cell, u32 index, u32 target)
{
    u32 *b = (u32 *)code;
    b[0] = 0xE92D1001;
    b[1] = 0xE59F000C;
    b[2] = 0xE59FC00C;
    b[3] = 0xE580C000;
    b[4] = 0xE8BD1001;
    b[5] = 0xE59FF004;
    b[6] = (u32)cell;
    b[7] = index;
    b[8] = target;
    return (u32)b;
}

// Then a fault says where it happened, in the only terms the phone gives us.
extern "C" void gate6_fault(Context *c, int type)
{
    PANIC(CAT_FLT, (int)(c->lastImport * 100 + (u32)(type & 63)));
}

// Both at once, for a call that is given one wrapper and made on another. Five
// instructions and three words is exactly the slot, with nothing to spare.
static u32 pair_thunk(u8 *code, const void *cell0, const void *cell1, u32 target)
{
    u32 *b = (u32 *)code;
    b[0] = 0xE59F000C;                  // ldr r0, [pc, #12]
    b[1] = 0xE5900000;                  // ldr r0, [r0]
    b[2] = 0xE59F1008;                  // ldr r1, [pc, #8]
    b[3] = 0xE5911000;                  // ldr r1, [r1]
    b[4] = 0xE59FF004;                  // ldr pc, [pc, #4]
    b[5] = (u32)cell0;
    b[6] = (u32)cell1;
    b[7] = target;
    return (u32)b;
}

// ---- the app UI ------------------------------------------------------------

// The game asks CAknAppUi to base-construct the old object. Ours is a
// CEikAppUi, built from the constructors gate 5 used, so it gets the CEikAppUi
// one -- and the flags gate 5 established rather than the game's zero, since
// nothing here has screen furniture to construct yet.
// ---- the control -----------------------------------------------------------

// The game asks its application where it lives and takes the drive and path
// from the answer, which is how it finds its own data files. Ours is a 9.x
// CEikApplication built from nothing and has no name to give, so the answer is
// the path the loader actually opened.
//
// TFileName is a TBuf<256>: a length word whose top four bits are the
// descriptor type, a maximum length, then the text -- 0x208 bytes, which is
// what the game reserves for it. Too big to return in registers, so r0 is the
// buffer to fill and the function hands it back.
enum { EBuf = 3 };

extern "C" void *gate6_dll_name(u32 *out, void *, Context *c)
{
    out[0] = ((u32)EBuf << KTypeShift) | (u32)c->pathLen;
    out[1] = 256;
    u16 *text = (u16 *)(out + 2);
    for (int i = 0; i < c->pathLen; i++)
        text[i] = c->path[i];
    return out;
}

// The game must never see the environment as it really is. It asks for it by
// name as well as reading it out of its control -- CCoeEnv::Static() then
// [env+0x18] is how it finds the app UI -- so the shifted view is what
// CCoeEnv::Static() returns too.
extern "C" void *gate6_coeenv_static(void)
{
    return (u8 *)coeenv_static() + COEENV_BIAS;
}

// The game's own control, constructed the way its own code expects. What the
// 9.x constructor would write is not merely different, it is at the wrong
// offsets, so this writes the old layout instead. A GCC98r2 constructor returns
// the object.
extern "C" void *gate6_coecontrol_ctor(u32 *self)
{
    for (int i = 0; i < OLD_CONTROL_BYTES / 4; i++)
        self[i] = 0;
    self[OLD_CONTROL_COEENV / 4] = (u32)gate6_coeenv_static();
    return self;
}

// A window belongs to a 9.x control, so build one and lend the game its window:
// old Window() is one instruction, a load from offset 0x20, so putting the
// window there is all it takes for the game to find it.
extern "C" void gate6_create_window(u32 *oldControl, int, Context *c)
{
    u32 *ctl = (u32 *)user_allocz(WRAP_BYTES);
    if (!ctl) PANIC(CAT_MEM, -33);
    coecontrol_ctor(ctl);
    coecontrol_createwindowl(ctl);
    oldControl[OLD_CONTROL_WIN / 4] = ctl[NEW_CONTROL_WIN / 4];
    c->wrapControl = ctl;
}

extern "C" void gate6_baseconstructl(void *, int, Context *c)
{
    eikappui_baseconstructl(c->wrapUi, ENoAppResourceFile | ENoScreenFurniture);
}

extern "C" void gate6_ui_construct(void *self)
{
    // From here the game's own ConstructL drives, and whatever it reaches that
    // the shim cannot answer panics with that import's index. It now runs to
    // the end, so let it return and the framework take over.
    context_of(self)->wrapUi = (u32 *)self;
    old_call((const u32 *)((const u32 *)self)[WRAP_OLD], OLD_UI_CONSTRUCT);
}

extern "C" void *gate6_create_app_ui(void *self)
{
    const u32 *oldDoc = (const u32 *)((const u32 *)self)[WRAP_OLD];
    u32 oldUi = old_call(oldDoc, OLD_CREATE_APP_UI);
    if (!oldUi) PANIC(CAT_NUL, 3);

    u32 *ui = (u32 *)user_allocz(WRAP_BYTES);
    if (!ui) PANIC(CAT_MEM, -31);
    coeappui_ctor(ui);          // assigns iCoeEnv, which BaseConstructL reads
    eikappui_ctor(ui);
    ui[WRAP_OLD] = oldUi;
    ui[WRAP_CTX] = ((const u32 *)self)[WRAP_CTX];

    u32 *vt = copy_vtable(vtable_of(ui), UI_SLOTS);
    vt[VT_HEADER + SLOT_UI_CONSTRUCT] = (u32)&gate6_ui_construct;
    ui[0] = (u32)(vt + VT_HEADER);
    return ui;
}

// ---- the document ----------------------------------------------------------

extern "C" void *gate6_create_document(void *self)
{
    const u32 *oldApp = (const u32 *)((const u32 *)self)[WRAP_OLD];
    u32 oldDoc = old_call(oldApp, OLD_CREATE_DOCUMENT);
    if (!oldDoc) PANIC(CAT_NUL, 2);

    u32 *doc = (u32 *)user_allocz(WRAP_BYTES);
    if (!doc) PANIC(CAT_MEM, -32);
    akndocument_ctor(doc, self);        // the 9.x document points at the 9.x app
    doc[WRAP_OLD] = oldDoc;
    doc[WRAP_CTX] = ((const u32 *)self)[WRAP_CTX];

    u32 *vt = copy_vtable(vtable_of(doc), DOC_SLOTS);
    vt[VT_HEADER + SLOT_CREATE_APP_UI] = (u32)&gate6_create_app_ui;
    doc[0] = (u32)(vt + VT_HEADER);
    return doc;
}

// ---- the application -------------------------------------------------------

// The game's own AppDllUid answers with the N-Gage UID, and bridging it is what
// the first run of this did: the framework then looked the application up by
// that UID, found no registration for it and left with KErrNotFound before the
// document was ever asked for. The UID is the framework's name for *us*, so it
// stays ours -- the same one the registration resource carries.
extern "C" u32 gate6_app_dll_uid(void *)
{
    return 0xE0001006;          // TUid is one word, returned in r0
}

static u32 load_and_start(void);   // -> the wrapper the framework gets

extern "C" void *gate6_new_application()
{
    return (void *)load_and_start();
}

extern "C" u32 gate6_main()
{
    eikstart_runapplication(0, (u32)&gate6_new_application, 0, 0);
    PANIC(CAT_RET, 0);
    return 0;
}

static u32 load_and_start()
{
    u32 fs[2] = { 0, 0 };
    u32 file[4] = { 0, 0, 0, 0 };
    i32 err = fs_connect(fs, -1);
    if (err) PANIC(CAT_FS, err);

    const u16 *paths[3] = { kPath0, kPath1, kPath2 };
    const int lens[3] = { sizeof kPath0 / 2, sizeof kPath1 / 2, sizeof kPath2 / 2 };
    err = -1;
    int chosen = 0;
    for (int i = 0; i < 3 && err; i++) {
        Ptrc16 name;
        name.lengthAndType = ((u32)EPtrC << KTypeShift) | (u32)lens[i];
        name.text = paths[i];
        err = file_open(file, fs, &name, 1);       // EFileRead | EFileShareReadersOnly
        chosen = i;
    }
    if (err) PANIC(CAT_FS, err);

    int size = 0;
    err = file_size(file, &size);
    if (err) PANIC(CAT_FS, err);

    u8 *raw = (u8 *)user_alloc(size);
    if (!raw) PANIC(CAT_MEM, size);

    // RFile::Read stops at the descriptor's maximum, so loop until it is full.
    int got = 0;
    while (got < size) {
        Ptr8 des;
        des.lengthAndType = (u32)EPtr << KTypeShift;
        des.maxLength = size - got;
        des.ptr = raw + got;
        err = file_read(file, &des);
        if (err) PANIC(CAT_FS, err);
        int n = (int)(des.lengthAndType & 0x0FFFFFFF);
        if (n <= 0) break;
        got += n;
    }
    if (got != size) PANIC(CAT_FS, got);

    const E32 *h = (const E32 *)raw;
    if (h->sig != 0x434F5045) PANIC(CAT_HDR, 1);            // 'EPOC'
    if (h->uid1 != 0x10000079) PANIC(CAT_HDR, 2);           // a polymorphic DLL
    if (h->cpu != 0x2000 && h->cpu != 0x1000) PANIC(CAT_HDR, 3);  // must be EKA1
    if (h->compression) PANIC(CAT_HDR, 4);
    if (h->textSize > h->codeSize) PANIC(CAT_HDR, 5);

    const u32 nImports = (h->codeSize - h->textSize) / 4;
    const u32 stubBytes = nImports * SLOT;
    const u32 traceBytes = nImports * TRACE + TRACE;    // one spare for the handler
    const u32 chunkSize = h->codeSize + stubBytes + traceBytes;

    u32 chunk[2] = { 0, 0 };
    err = chunk_createlocalcode(chunk, (int)chunkSize, (int)chunkSize, 0);
    if (err) PANIC(CAT_MEM, err);
    u8 *base = chunk_base(chunk);
    if (!base) PANIC(CAT_MEM, 0x0BADBA5E);

    for (u32 i = 0; i < h->codeSize; i++)
        base[i] = raw[h->codeOffset + i];

    // Rebase. Type 3 is KInferredRelocType and this image has no data section,
    // so every relocation lands in the code we just copied.
    const u32 delta = (u32)base - h->codeBase;
    u32 relocated = 0;
    if (h->codeRelocOffset) {
        const u8 *sec = raw + h->codeRelocOffset;
        const u32 secSize = *(const u32 *)sec;
        u32 o = 8;
        while (o < secSize + 8) {
            const u32 pageBase = *(const u32 *)(sec + o);
            const u32 blockSize = *(const u32 *)(sec + o + 4);
            if (blockSize < 8 || (blockSize & 1)) break;
            for (u32 k = 0; k < (blockSize - 8) / 2; k++) {
                const u16 e = *(const u16 *)(sec + o + 8 + 2 * k);
                if (!e) continue;
                const u32 at = pageBase + (e & 0x0FFF);
                if (at + 4 > h->codeSize) PANIC(CAT_HDR, 6);
                *(u32 *)(base + at) += delta;
                relocated++;
            }
            o += blockSize;
        }
    }
    if (!relocated) PANIC(CAT_HDR, 7);

    // Load the 9.x libraries the forwarding table names. Resolving at run time
    // rather than through our own import section means an ordinal this phone
    // does not have is a null we can count, not a refusal to start at all.
    u32 libs[24];
    if (kShimDllCount > 24) PANIC(CAT_SHIM, (int)kShimDllCount);
    Ptrc16 nopath;
    nopath.lengthAndType = (u32)EPtrC << KTypeShift;
    nopath.text = 0;
    for (u32 i = 0; i < kShimDllCount; i++) {
        libs[i] = 0;
        Ptrc16 nm;
        nm.lengthAndType = ((u32)EPtrC << KTypeShift) | (u32)kShimDllLen[i];
        nm.text = kShimDllName[i];
        err = rlibrary_load(&libs[i], &nm, &nopath);
        if (err) PANIC(CAT_LIB, (int)(i * 1000) + err);
    }

    // Build one stub per import and write its address into the import address
    // table, which on EKA1 sits at the end of the code section.
    //   ldr r0, [pc, #0]   -> the report code
    //   ldr pc, [pc, #0]   -> gate6_report
    u32 *iat = (u32 *)(base + h->textSize);
    u8 *stub = base + h->codeSize;
    u8 *trace = stub + stubBytes;
    u32 forwarded = 0, missing = 0;

    Context *ctx = (Context *)user_allocz((int)sizeof(Context));
    if (!ctx) PANIC(CAT_MEM, -23);
    ctx->path = paths[chosen];
    ctx->pathLen = lens[chosen];
    ctx->lastImport = 0xFFFF;               // nothing yet

    // The handler takes a TExcType in r0 and has nowhere to keep the context,
    // so it arrives through a thunk of its own.
    {
        u32 *b = (u32 *)(trace + nImports * TRACE);
        b[0] = 0xE1A01000;                  // mov r1, r0   -- the exception type
        b[1] = 0xE59F0000;                  // ldr r0, [pc, #0]
        b[2] = 0xE59FF000;                  // ldr pc, [pc, #0]
        b[3] = (u32)ctx;
        b[4] = (u32)&gate6_fault;
        user_setexceptionhandler(b, 0xFFFFFFFF);
    }
    for (u32 i = 0; i < nImports; i++) {
        u32 *s = (u32 *)(stub + SLOT * i);
        s[0] = 0xE59F0000;                  // ldr r0, [pc, #0]  -> the report code
        s[1] = 0xE59FF000;                  // ldr pc, [pc, #0]  -> gate6_report
        s[2] = nImports * 1000 + i;
        s[3] = (u32)&gate6_report;
        iat[i] = (u32)s;

        const u32 entry = (i < kShimCount) ? kShimTable[i] : 0;
        const u32 kind = entry >> 24;
        if (!kind)
            continue;

        if (kind == KIND_LOCAL) {
            switch (entry & 0xFFFF) {
            case LOCAL_NEGSF2:
                s[0] = 0xE2200102;          // eor r0, r0, #0x80000000
                s[1] = 0xE12FFF1E;          // bx  lr
                break;
            case LOCAL_NOOP:                // an empty body: _Reserved slots, CBase
                s[0] = 0xE3A00000;          // mov r0, #0
                s[1] = 0xE12FFF1E;          // bx  lr
                break;
            case LOCAL_TRAP_ENTER:          // TTrap::Trap(TInt&): first pass, no error
                s[0] = 0xE3A00000;          // mov r0, #0
                s[1] = 0xE5810000;          // str r0, [r1]
                s[2] = 0xE12FFF1E;          // bx  lr
                break;
            case LOCAL_TINT64_SET:          // TInt64 from a TInt: sign-extend
                s[0] = 0xE5801000;          // str r1, [r0]
                s[1] = 0xE1A02FC1;          // mov r2, r1, asr #31
                s[2] = 0xE5802004;          // str r2, [r0, #4]
                s[3] = 0xE12FFF1E;          // bx  lr     -- r0 is still the object
                break;
            case LOCAL_MEM_COMPARE:
                s[0] = 0xE51FF004;          // ldr pc, [pc, #-4]
                s[1] = (u32)&gate6_mem_compare;
                break;
            default:
                s[0] = 0xE51FF004;
                s[1] = (u32)&gate6_pure_virtual;
                break;
            }
            forwarded++;
            continue;
        }

        void *fn = rlibrary_lookup(&libs[(entry >> 16) & 0xFF], (int)(entry & 0xFFFF));
        if (!fn) {
            missing++;                      // the stub stays, so we hear about it
            continue;
        }
        if (kind == KIND_CALL) {
            iat[i] = (u32)fn;
        } else if (kind == KIND_SRET8) {
            // GCC98r2 returned an eight-byte structure in r0 and r1; EABI wants
            // a buffer in r0 and pushes `this` to r1. Borrow eight bytes of
            // stack, let the callee fill them, and hand them back in registers.
            s[0] = 0xE92D4010;              // push  {r4, lr}
            s[1] = 0xE24DD008;              // sub   sp, sp, #8
            s[2] = 0xE1A01000;              // mov   r1, r0      -- `this`
            s[3] = 0xE1A0000D;              // mov   r0, sp      -- the buffer
            s[4] = 0xE59F4008;              // ldr   r4, [pc, #8]
            s[5] = 0xE12FFF34;              // blx   r4
            s[6] = 0xE8BD0003;              // ldmia sp!, {r0, r1}
            s[7] = 0xE8BD8010;              // pop   {r4, pc}
            s[8] = (u32)fn;
        } else if (kind == KIND_ARG3) {
            s[0] = 0xE3A02000;              // mov r2, #0    -- the added argument
            s[1] = 0xE51FF004;              // ldr pc, [pc, #-4]
            s[2] = (u32)fn;
        } else {
            s[0] = 0xE92D4000;              // push {lr}
            s[1] = 0xE59FC008;              // ldr  r12, [pc, #8]
            s[2] = 0xE12FFF3C;              // blx  r12
            s[3] = 0xE1A00001;              // mov  r0, r1   -- the remainder
            s[4] = 0xE8BD8000;              // pop  {pc}
            s[5] = (u32)fn;
        }
        forwarded++;
    }
    if (!forwarded) PANIC(CAT_SHIM, (int)missing);

    // The stub slot of a resolved import is spare -- its address went straight
    // into the table -- so the diversions are built there.
    if (nImports <= IMPORT_BASECONSTRUCTL) PANIC(CAT_SHIM, (int)nImports);
    iat[IMPORT_BASECONSTRUCTL] = ctx_thunk(stub + SLOT * IMPORT_BASECONSTRUCTL,
                                           ctx, (u32)&gate6_baseconstructl);

    if (nImports > IMPORT_CREATEWINDOWL)
        iat[IMPORT_CREATEWINDOWL] = ctx_thunk(stub + SLOT * IMPORT_CREATEWINDOWL,
                                              ctx, (u32)&gate6_create_window);
    if (nImports > IMPORT_DLL_NAME)
        iat[IMPORT_DLL_NAME] = ctx_thunk(stub + SLOT * IMPORT_DLL_NAME,
                                         ctx, (u32)&gate6_dll_name);
    if (nImports > IMPORT_COEENV_STATIC)
        iat[IMPORT_COEENV_STATIC] = (u32)&gate6_coeenv_static;
    if (nImports > IMPORT_COECONTROL_CTOR)
        iat[IMPORT_COECONTROL_CTOR] = (u32)&gate6_coecontrol_ctor;
    if (nImports > IMPORT_WINDOW) {
        u32 *w = (u32 *)(stub + SLOT * IMPORT_WINDOW);
        w[0] = 0xE5900000 | OLD_CONTROL_WIN;    // ldr r0, [r0, #0x20]  -- iWin
        w[1] = 0xE12FFF1E;                      // bx  lr
        iat[IMPORT_WINDOW] = (u32)w;
    }
    if (nImports > IMPORT_ADDTOSTACKL && IMPORT_ADDTOSTACKL < kShimCount &&
        (kShimTable[IMPORT_ADDTOSTACKL] >> 24) == KIND_CALL)
        iat[IMPORT_ADDTOSTACKL] = pair_thunk(stub + SLOT * IMPORT_ADDTOSTACKL,
                                             &ctx->wrapUi, &ctx->wrapControl,
                                             iat[IMPORT_ADDTOSTACKL]);

    for (u32 k = 0; k < sizeof kDiverts / sizeof kDiverts[0]; k++) {
        const u32 j = kDiverts[k].import;
        // An import the shim could not answer keeps its reporting stub: sending
        // it through a diversion would lose the one thing it can still tell us.
        if (j >= nImports || j >= kShimCount || (kShimTable[j] >> 24) != KIND_CALL)
            continue;
        u32 **cell = (kDiverts[k].object == ON_CONTROL) ? &ctx->wrapControl : &ctx->wrapUi;
        iat[j] = this_thunk(stub + SLOT * j, cell, iat[j], kDiverts[k].arg);
    }

    // Last, so that it records every import however it ended up being answered.
    for (u32 i = 0; i < nImports; i++)
        iat[i] = trace_thunk(trace + TRACE * i, &ctx->lastImport, i, iat[i]);

    // Enter it. EKA1 calls a DLL's entry point with EDllProcessAttach first,
    // then apparc asks ordinal 1 for the application object.
    typedef int (*EntryFn)(int);
    typedef void *(*Ordinal1Fn)(void);
    ((EntryFn)(base + h->entryPoint))(0);
    const u32 ord1 = *(const u32 *)(raw + h->exportDirOffset);
    void *app = ((Ordinal1Fn)(base + ord1))();
    if (!app) PANIC(CAT_NUL, (int)(forwarded * 1000 + missing));
    // The 9.x application: built the ordinary way, then told which old object
    // it stands for, with its two overridden slots pointed at the game.
    u32 *wrap = (u32 *)user_allocz(WRAP_BYTES);
    if (!wrap) PANIC(CAT_MEM, -20);
    eikapplication_ctor(wrap);
    wrap[WRAP_OLD] = (u32)app;
    wrap[WRAP_CTX] = (u32)ctx;

    u32 *vt = copy_vtable(vtable_of(wrap), APP_SLOTS);
    vt[VT_HEADER + SLOT_APP_DLL_UID] = (u32)&gate6_app_dll_uid;
    vt[VT_HEADER + SLOT_CREATE_DOCUMENT] = (u32)&gate6_create_document;
    wrap[0] = (u32)(vt + VT_HEADER);
    return (u32)wrap;

}
