// Gate 4: load the N-Gage binary on S60v3 and run it.
//
// Read 6RBC.APP, copy its code into an executable chunk, rebase it with its own
// relocation table, point all 462 imports at stubs, and enter it.  The game is
// an EKA1 polymorphic DLL, so "enter it" means its entry point and then export
// ordinal 1, CApaApplication's factory.
//
// The result is reported as a panic, because that is the only channel a phone
// gives us.  The category says how far it got and the reason says which import
// its code reached first -- and reaching an import at all is the whole point:
// it means the game's own instructions ran, on hardware they were never built
// for, and called out through our table.

typedef unsigned char u8;
typedef unsigned short u16;
typedef unsigned int u32;
typedef int i32;

extern "C" {
void user_panic(const void *category, int reason);
void *user_alloc(int size);
i32 chunk_createlocalcode(void *chunk, int size, int maxSize, int owner);
u8 *chunk_base(const void *chunk);
i32 fs_connect(void *fs, int slots);
i32 file_open(void *file, void *fs, const void *name, u32 mode);
i32 file_size(const void *file, int *size);
i32 file_read(const void *file, void *des);
i32 rlibrary_load(void *lib, const void *name, const void *path);
void *rlibrary_lookup(const void *lib, int ordinal);

// Generated by gen_shim.py: which 9.x DLL and ordinal answers each old import.
extern const unsigned short *const kShimDllName[];
extern const unsigned char kShimDllLen[];
extern const u32 kShimDllCount;
extern const u32 kShimTable[];
extern const u32 kShimCount;
}

// TDesC16 and TDes8: a length word whose top four bits are the descriptor type,
// then (for a modifiable one) a maximum length, then the data pointer.
enum { EPtrC = 1, EPtr = 2, KTypeShift = 28 };

struct Ptrc16 { u32 lengthAndType; const u16 *text; };
struct Ptr8 { u32 lengthAndType; int maxLength; u8 *ptr; };

// Every import gets a slot big enough for whichever thunk it needs.
enum { SLOT = 48 };
enum { KIND_CALL = 1, KIND_REM = 2, KIND_LOCAL = 3, KIND_ARG3 = 4, KIND_SRET8 = 5,
       KIND_ARGSHIFT = 6 };
enum { LOCAL_NEGSF2 = 0, LOCAL_PURE_VIRTUAL = 1, LOCAL_NOOP = 2, LOCAL_MEM_COMPARE = 3,
       LOCAL_TRAP_ENTER = 4, LOCAL_TINT64_SET = 5 };

static void panic(const u16 *cat, int catLen, int reason)
{
    Ptrc16 d;
    d.lengthAndType = ((u32)EPtrC << KTypeShift) | (u32)catLen;
    d.text = cat;
    user_panic(&d, reason);
}

#define PANIC(name, reason) do { \
    static const u16 s[] = name; \
    panic(s, (int)(sizeof s / sizeof s[0]), (reason)); } while (0)

#define CAT_FS  {'G','4','F','S'}
#define CAT_MEM {'G','4','M','E','M'}
#define CAT_HDR {'G','4','H','D','R'}
#define CAT_IMP {'G','4','I','M','P'}
#define CAT_RET {'G','4','R','E','T'}
#define CAT_LIB {'G','4','L','I','B'}
#define CAT_SHIM {'G','4','S','H','M'}
#define CAT_NUL {'G','4','N','U','L'}
#define CAT_PURE {'G','4','P','U','R'}

// The EKA1 header, at the offsets EKA2L1's loader reads.
struct E32 {
    u32 uid1, uid2, uid3, check, sig, cpu;
    u32 pad, compression, petran, timeLo, timeHi;
    u32 flags, codeSize, dataSize, heapMin, heapMax, stackSize, bssSize;
    u32 entryPoint, codeBase, dataBase, dllRefCount;
    u32 exportDirOffset, exportDirCount, textSize;
    u32 codeOffset, dataOffset, importOffset, codeRelocOffset, dataRelocOffset;
};

static const u16 kPath0[] = {'E',':','\\','6','r','b','c','.','a','p','p'};
static const u16 kPath1[] = {'C',':','\\','6','r','b','c','.','a','p','p'};
static const u16 kPath2[] = {'E',':','\\','s','y','s','t','e','m','\\','a','p','p','s','\\',
                             '6','r','b','c','\\','6','r','b','c','.','a','p','p'};

// Every import points here, through a 16-byte stub carrying its own report
// code. That code is `import count * 1000 + index`, because a panic gives us
// one integer and which binary was loaded is half the answer: this game ships
// both as a 1.6 MB image with 462 imports and as a 4 KB loader stub with 41,
// and an index alone cannot tell them apart. Keeping it in the stub also keeps
// this program free of writable globals, which the image has no room for --
// it declares no .bss.
extern "C" void gate4_report(int code)
{
    PANIC(CAT_IMP, code);
}

// A call through a vtable slot the old binary never filled in.
extern "C" void gate4_pure_virtual()
{
    PANIC(CAT_PURE, 0);
}

// Only the 16-bit Mem::Compare is still exported, so the 8-bit one lives here.
// Symbian's contract: compare the common prefix, then the lengths.
extern "C" int gate4_mem_compare(const u8 *a, int la, const u8 *b, int lb)
{
    const int n = (la < lb) ? la : lb;
    for (int i = 0; i < n; i++)
        if (a[i] != b[i])
            return (int)a[i] - (int)b[i];
    return la - lb;
}

extern "C" u32 gate4_main()
{
    u32 fs[2] = { 0, 0 };
    u32 file[4] = { 0, 0, 0, 0 };
    i32 err = fs_connect(fs, -1);
    if (err) PANIC(CAT_FS, err);

    const u16 *paths[3] = { kPath0, kPath1, kPath2 };
    const int lens[3] = { sizeof kPath0 / 2, sizeof kPath1 / 2, sizeof kPath2 / 2 };
    err = -1;
    for (int i = 0; i < 3 && err; i++) {
        Ptrc16 name;
        name.lengthAndType = ((u32)EPtrC << KTypeShift) | (u32)lens[i];
        name.text = paths[i];
        err = file_open(file, fs, &name, 1);       // EFileRead | EFileShareReadersOnly
    }
    if (err) PANIC(CAT_FS, err);

    int size = 0;
    err = file_size(file, &size);
    if (err) PANIC(CAT_FS, err);

    u8 *raw = (u8 *)user_alloc(size);
    if (!raw) PANIC(CAT_MEM, size);

    // RFile::Read stops at the descriptor's maximum, so loop until it is full.
    int got = 0;
    while (got < size) {
        Ptr8 des;
        des.lengthAndType = (u32)EPtr << KTypeShift;
        des.maxLength = size - got;
        des.ptr = raw + got;
        err = file_read(file, &des);
        if (err) PANIC(CAT_FS, err);
        int n = (int)(des.lengthAndType & 0x0FFFFFFF);
        if (n <= 0) break;
        got += n;
    }
    if (got != size) PANIC(CAT_FS, got);

    const E32 *h = (const E32 *)raw;
    if (h->sig != 0x434F5045) PANIC(CAT_HDR, 1);            // 'EPOC'
    if (h->uid1 != 0x10000079) PANIC(CAT_HDR, 2);           // a polymorphic DLL
    if (h->cpu != 0x2000 && h->cpu != 0x1000) PANIC(CAT_HDR, 3);  // must be EKA1
    if (h->compression) PANIC(CAT_HDR, 4);
    if (h->textSize > h->codeSize) PANIC(CAT_HDR, 5);

    const u32 nImports = (h->codeSize - h->textSize) / 4;
    const u32 stubBytes = nImports * SLOT;
    const u32 chunkSize = h->codeSize + stubBytes;

    u32 chunk[2] = { 0, 0 };
    err = chunk_createlocalcode(chunk, (int)chunkSize, (int)chunkSize, 0);
    if (err) PANIC(CAT_MEM, err);
    u8 *base = chunk_base(chunk);
    if (!base) PANIC(CAT_MEM, 0x0BADBA5E);

    for (u32 i = 0; i < h->codeSize; i++)
        base[i] = raw[h->codeOffset + i];

    // Rebase. Type 3 is KInferredRelocType and this image has no data section,
    // so every relocation lands in the code we just copied.
    const u32 delta = (u32)base - h->codeBase;
    u32 relocated = 0;
    if (h->codeRelocOffset) {
        const u8 *sec = raw + h->codeRelocOffset;
        const u32 secSize = *(const u32 *)sec;
        u32 o = 8;
        while (o < secSize + 8) {
            const u32 pageBase = *(const u32 *)(sec + o);
            const u32 blockSize = *(const u32 *)(sec + o + 4);
            if (blockSize < 8 || (blockSize & 1)) break;
            for (u32 k = 0; k < (blockSize - 8) / 2; k++) {
                const u16 e = *(const u16 *)(sec + o + 8 + 2 * k);
                if (!e) continue;
                const u32 at = pageBase + (e & 0x0FFF);
                if (at + 4 > h->codeSize) PANIC(CAT_HDR, 6);
                *(u32 *)(base + at) += delta;
                relocated++;
            }
            o += blockSize;
        }
    }
    if (!relocated) PANIC(CAT_HDR, 7);

    // Load the 9.x libraries the forwarding table names. Resolving at run time
    // rather than through our own import section means an ordinal this phone
    // does not have is a null we can count, not a refusal to start at all.
    u32 libs[24];
    if (kShimDllCount > 24) PANIC(CAT_SHIM, (int)kShimDllCount);
    Ptrc16 nopath;
    nopath.lengthAndType = (u32)EPtrC << KTypeShift;
    nopath.text = 0;
    for (u32 i = 0; i < kShimDllCount; i++) {
        libs[i] = 0;
        Ptrc16 nm;
        nm.lengthAndType = ((u32)EPtrC << KTypeShift) | (u32)kShimDllLen[i];
        nm.text = kShimDllName[i];
        err = rlibrary_load(&libs[i], &nm, &nopath);
        if (err) PANIC(CAT_LIB, (int)(i * 1000) + err);
    }

    // Build one stub per import and write its address into the import address
    // table, which on EKA1 sits at the end of the code section.
    //   ldr r0, [pc, #0]   -> the report code
    //   ldr pc, [pc, #0]   -> gate4_report
    u32 *iat = (u32 *)(base + h->textSize);
    u8 *stub = base + h->codeSize;
    u32 forwarded = 0, missing = 0;
    for (u32 i = 0; i < nImports; i++) {
        u32 *s = (u32 *)(stub + SLOT * i);
        s[0] = 0xE59F0000;                  // ldr r0, [pc, #0]  -> the report code
        s[1] = 0xE59FF000;                  // ldr pc, [pc, #0]  -> gate4_report
        s[2] = nImports * 1000 + i;
        s[3] = (u32)&gate4_report;
        iat[i] = (u32)s;

        const u32 entry = (i < kShimCount) ? kShimTable[i] : 0;
        const u32 kind = entry >> 24;
        if (!kind)
            continue;

        if (kind == KIND_LOCAL) {
            switch (entry & 0xFFFF) {
            case LOCAL_NEGSF2:
                s[0] = 0xE2200102;          // eor r0, r0, #0x80000000
                s[1] = 0xE12FFF1E;          // bx  lr
                break;
            case LOCAL_NOOP:                // an empty body: _Reserved slots, CBase
                s[0] = 0xE3A00000;          // mov r0, #0
                s[1] = 0xE12FFF1E;          // bx  lr
                break;
            case LOCAL_TRAP_ENTER:          // TTrap::Trap(TInt&): first pass, no error
                s[0] = 0xE3A00000;          // mov r0, #0
                s[1] = 0xE5810000;          // str r0, [r1]
                s[2] = 0xE12FFF1E;          // bx  lr
                break;
            case LOCAL_TINT64_SET:          // TInt64 from a TInt: sign-extend
                s[0] = 0xE5801000;          // str r1, [r0]
                s[1] = 0xE1A02FC1;          // mov r2, r1, asr #31
                s[2] = 0xE5802004;          // str r2, [r0, #4]
                s[3] = 0xE12FFF1E;          // bx  lr     -- r0 is still the object
                break;
            case LOCAL_MEM_COMPARE:
                s[0] = 0xE51FF004;          // ldr pc, [pc, #-4]
                s[1] = (u32)&gate4_mem_compare;
                break;
            default:
                s[0] = 0xE51FF004;
                s[1] = (u32)&gate4_pure_virtual;
                break;
            }
            forwarded++;
            continue;
        }

        void *fn = rlibrary_lookup(&libs[(entry >> 16) & 0xFF], (int)(entry & 0xFFFF));
        if (!fn) {
            missing++;                      // the stub stays, so we hear about it
            continue;
        }
        if (kind == KIND_CALL) {
            iat[i] = (u32)fn;
        } else if (kind == KIND_SRET8) {
            // GCC98r2 returned an eight-byte structure in r0 and r1; EABI wants
            // a buffer in r0 and pushes `this` to r1. Borrow eight bytes of
            // stack, let the callee fill them, and hand them back in registers.
            s[0] = 0xE92D4010;              // push  {r4, lr}
            s[1] = 0xE24DD008;              // sub   sp, sp, #8
            s[2] = 0xE1A01000;              // mov   r1, r0      -- `this`
            s[3] = 0xE1A0000D;              // mov   r0, sp      -- the buffer
            s[4] = 0xE59F4008;              // ldr   r4, [pc, #8]
            s[5] = 0xE12FFF34;              // blx   r4
            s[6] = 0xE8BD0003;              // ldmia sp!, {r0, r1}
            s[7] = 0xE8BD8010;              // pop   {r4, pc}
            s[8] = (u32)fn;
        } else if (kind == KIND_ARGSHIFT) {
            // A member function 9.x made free: drop `this` and move the rest
            // down a register.
            s[0] = 0xE1A00001;              // mov r0, r1
            s[1] = 0xE1A01002;              // mov r1, r2
            s[2] = 0xE1A02003;              // mov r2, r3
            s[3] = 0xE51FF004;              // ldr pc, [pc, #-4]
            s[4] = (u32)fn;
        } else if (kind == KIND_ARG3) {
            s[0] = 0xE3A02000;              // mov r2, #0    -- the added argument
            s[1] = 0xE51FF004;              // ldr pc, [pc, #-4]
            s[2] = (u32)fn;
        } else {
            s[0] = 0xE92D4000;              // push {lr}
            s[1] = 0xE59FC008;              // ldr  r12, [pc, #8]
            s[2] = 0xE12FFF3C;              // blx  r12
            s[3] = 0xE1A00001;              // mov  r0, r1   -- the remainder
            s[4] = 0xE8BD8000;              // pop  {pc}
            s[5] = (u32)fn;
        }
        forwarded++;
    }
    if (!forwarded) PANIC(CAT_SHIM, (int)missing);

    // Enter it. EKA1 calls a DLL's entry point with EDllProcessAttach first,
    // then apparc asks ordinal 1 for the application object.
    typedef int (*EntryFn)(int);
    typedef void *(*Ordinal1Fn)(void);
    ((EntryFn)(base + h->entryPoint))(0);
    const u32 ord1 = *(const u32 *)(raw + h->exportDirOffset);
    void *app = ((Ordinal1Fn)(base + ord1))();
    if (!app) PANIC(CAT_NUL, (int)(forwarded * 1000 + missing));

    // It built its application object and handed it back. Report how many
    // forwards this phone actually resolved rather than the pointer: the
    // ordinals come from a later 9.x than any one device, so some will be
    // missing, and that count is the thing worth knowing.
    PANIC(CAT_RET, (int)(forwarded * 1000 + missing));
    return 0;
}
