// Step 3: the wrapper.
//
// Gate 4 loaded the N-Gage binary and ran its code; gate 5 made this a real
// S60v3 GUI application. This joins them. The framework asks for a
// CApaApplication; the game's own NewApplication builds one, but it is an
// old-ABI object the 9.x framework cannot call. So hand the framework a
// 9.x-layout object of our own whose slots dispatch into the old one -- which
// is what gate 3 proved works, now against an object the game really built.
//
// Read 6RBC.APP, copy its code into an executable chunk, rebase it with its own
// relocation table, point all 462 imports at stubs, and enter it.  The game is
// an EKA1 polymorphic DLL, so "enter it" means its entry point and then export
// ordinal 1, CApaApplication's factory.
//
// The result is reported as a panic, because that is the only channel a phone
// gives us.  The category says how far it got and the reason says which import
// its code reached first -- and reaching an import at all is the whole point:
// it means the game's own instructions ran, on hardware they were never built
// for, and called out through our table.

typedef unsigned char u8;
typedef unsigned short u16;
typedef unsigned int u32;
typedef int i32;

extern "C" {
void user_panic(const void *category, int reason);
void *user_alloc(int size);
i32 chunk_createlocalcode(void *chunk, int size, int maxSize, int owner);
u8 *chunk_base(const void *chunk);
i32 fs_connect(void *fs, int slots);
i32 file_open(void *file, void *fs, const void *name, u32 mode);
i32 file_size(const void *file, int *size);
i32 file_read(const void *file, void *des);
i32 file_replace(void *file, void *fs, const void *name, u32 mode);
i32 file_write_at(const void *file, int pos, const void *des);
i32 file_flush(const void *file);
i32 rhandle_close(void *handle);
i32 fs_delete(void *fs, const void *name);
i32 rlibrary_load(void *lib, const void *name, const void *path);
void *rlibrary_lookup(const void *lib, int ordinal);
// After writing code: the stores are in the data cache and the instruction
// cache still holds what was there, so every thunk this program builds is put
// through here before anything jumps to it.
void user_imb_range(void *start, void *end);

// Generated by gen_shim.py: which 9.x DLL and ordinal answers each old import.
extern const unsigned short *const kShimDllName[];
extern const unsigned char kShimDllLen[];
extern const u32 kShimDllCount;
extern const u32 kShimTable[];
extern const u32 kShimCount;
extern const u16 kShimEuser[];
extern const u32 kShimEuserCount;
extern const u16 kShimEfsrv[];
extern const u32 kShimEfsrvCount;
extern const u16 kShimEuser[];
extern const u32 kShimEuserCount;
}

// TDesC16 and TDes8: a length word whose top four bits are the descriptor type,
// then (for a modifiable one) a maximum length, then the data pointer.
enum { EBufC = 0, EPtrC = 1, EPtr = 2, EBufType = 3, KTypeShift = 28 };

// The record: four counters and a ring of the last sixteen imports, which is
// what says what the game was doing rather than only how far it had got.
// The record: four counters, a ring of the last sixteen imports, the same
// again for where each was called from, and which path the game came from.
// Knowing the import says what the game asked for; knowing the caller says
// which of its own functions asked, which is the half that locates a fault.
enum { BOX_RING = 16 };
enum { BOX_FROM = 4 + BOX_RING, BOX_PATH = BOX_FROM + BOX_RING };
enum { BOX_SLOT = BOX_PATH + 1, BOX_FRAMES = BOX_SLOT + 1, BOX_STACK = BOX_FRAMES + 1 };
// A count per marker. The tail says where it was; these say whether it was
// going round in circles to get there, and how many times.
enum { BOX_HITS = BOX_STACK + 1, BOX_MARKERS = 40 };
enum { BOX_WORDS = BOX_HITS + BOX_MARKERS, BOX_BYTES = BOX_WORDS * 4 };

struct Ptrc16 { u32 lengthAndType; const u16 *text; };
struct Ptr8 { u32 lengthAndType; int maxLength; u8 *ptr; };

// Every import gets a slot big enough for whichever thunk it needs.
enum { SLOT = 48 };
enum { KIND_CALL = 1, KIND_REM = 2, KIND_LOCAL = 3, KIND_ARG3 = 4, KIND_SRET8 = 5,
       KIND_ARGSHIFT = 6 };
enum { LOCAL_NEGSF2 = 0, LOCAL_PURE_VIRTUAL = 1, LOCAL_NOOP = 2, LOCAL_MEM_COMPARE = 3,
       LOCAL_TRAP_ENTER = 4, LOCAL_TINT64_SET = 5, LOCAL_TRUE = 6, LOCAL_SELF = 7 };

static void panic(const u16 *cat, int catLen, int reason)
{
    Ptrc16 d;
    d.lengthAndType = ((u32)EPtrC << KTypeShift) | (u32)catLen;
    d.text = cat;
    user_panic(&d, reason);
}

#define PANIC(name, reason) do { \
    static const u16 s[] = name; \
    panic(s, (int)(sizeof s / sizeof s[0]), (reason)); } while (0)

#define CAT_FS  {'G','6','F','S'}
#define CAT_MEM {'G','6','M','E','M'}
#define CAT_HDR {'G','6','H','D','R'}
#define CAT_IMP {'G','6','I','M','P'}
#define CAT_RET {'G','6','R','E','T'}
#define CAT_LIB {'G','6','L','I','B'}
#define CAT_SHIM {'G','6','S','H','M'}
#define CAT_NUL {'G','6','N','U','L'}
#define CAT_PURE {'G','6','P','U','R'}

// The EKA1 header, at the offsets EKA2L1's loader reads.
struct E32 {
    u32 uid1, uid2, uid3, check, sig, cpu;
    u32 pad, compression, petran, timeLo, timeHi;
    u32 flags, codeSize, dataSize, heapMin, heapMax, stackSize, bssSize;
    u32 entryPoint, codeBase, dataBase, dllRefCount;
    u32 exportDirOffset, exportDirCount, textSize;
    u32 codeOffset, dataOffset, importOffset, codeRelocOffset, dataRelocOffset;
};

static const u16 kPath0[] = {'E',':','\\','6','r','b','c','.','a','p','p'};
static const u16 kPath1[] = {'C',':','\\','6','r','b','c','.','a','p','p'};
static const u16 kPath2[] = {'E',':','\\','s','y','s','t','e','m','\\','a','p','p','s','\\',
                             '6','r','b','c','\\','6','r','b','c','.','a','p','p'};

// Every import points here, through a 16-byte stub carrying its own report
// code. That code is `import count * 1000 + index`, because a panic gives us
// one integer and which binary was loaded is half the answer: this game ships
// both as a 1.6 MB image with 462 imports and as a 4 KB loader stub with 41,
// and an index alone cannot tell them apart. Keeping it in the stub also keeps
// this program free of writable globals, which the image has no room for --
// it declares no .bss.
extern "C" void gate6_report(int code)
{
    PANIC(CAT_IMP, code);
}

// A call through a vtable slot the old binary never filled in.
extern "C" void gate6_pure_virtual()
{
    PANIC(CAT_PURE, 0);
}

// Only the 16-bit Mem::Compare is still exported, so the 8-bit one lives here.
// Symbian's contract: compare the common prefix, then the lengths.
extern "C" int gate6_mem_compare(const u8 *a, int la, const u8 *b, int lb)
{
    const int n = (la < lb) ? la : lb;
    for (int i = 0; i < n; i++)
        if (a[i] != b[i])
            return (int)a[i] - (int)b[i];
    return la - lb;
}

extern "C" {
void eikstart_runapplication(u32 type, u32 data, u32 cached, u32 spare);
void eikapplication_ctor(void *self);                 // CEikApplication::CEikApplication()
void akndocument_ctor(void *self, void *app);         // CAknDocument::CAknDocument(CEikApplication&)
void coeappui_ctor(void *self);                       // CCoeAppUi::CCoeAppUi()
void eikappui_ctor(void *self);                       // CEikAppUi::CEikAppUi()
void eikappui_baseconstructl(void *self, int flags);  // CEikAppUi::BaseConstructL(TInt)
void *coeenv_static(void);                            // CCoeEnv::Static()
i32 user_setexceptionhandler(void *handler, u32 mask); // User::SetExceptionHandler
void *coecontrol_ctor(void *self);                    // CCoeControl::CCoeControl()
void coecontrol_createwindowl(void *self);            // CCoeControl::CreateWindowL()
void *user_allocz(int size);
void *cperiodic_newl(int priority);

// A GCC98r2 virtual call: the vptr is at offset 0 and points eight bytes
// before slot 0. Arguments past `this` are not passed, which is all the old
// slots reached from here need.
u32 old_call(const void *object, int slot);

// Imported for its own sake. A normal EABI application links against the C++
// runtime because its compiler emits calls into it; this one does not, so
// drtaeabi would only ever be loaded at run time by the shim -- and then the
// framework's own use of it, the unwinder behind every leave, runs against a
// library whose per-thread state was never set up. One static reference puts
// it in the process's dependencies where it belongs.
void drtaeabi_pure_virtual(void);

// The C++ runtime's per-thread state. On a normal EABI application euser's own
// thread entry declares one of these on its stack and the constructor stores it
// in the DLL's thread-local slot; our startup is our own and never did, so
// __cxa_get_globals -- which is nothing but that lookup -- returned null, and
// the first leave that had to become a C++ exception read through it. That is
// every leave on 9.x: TRAP is try/catch. Hence a fault in framework code with
// no code of ours or the game's anywhere near it.
void cpprt_globals_ctor(void *self);
u32 old_call1(const void *object, int slot, u32 arg);
}

#define CAT_CHN {'G','6','C','H','N'}
#define CAT_FLT {'G','6','F','L','T'}
#define CAT_TMR {'G','6','T','M','R'}
#define CAT_BOX {'G','6','B','O','X'}
#define CAT_UID {'G','6','U','I','D'}

// Two object graphs, not one. The 9.x framework gets objects of its own,
// constructed the ordinary way from exported constructors, and the game keeps
// the objects its own code built. A wrapper holds a pointer to its counterpart
// and forwards only the slots the game actually overrides; everything the game
// inherited stays with the 9.x implementation, which then runs against a 9.x
// object as it expects. Bridging an inherited slot instead sends the framework
// through the game's veneers back into 9.x code with `this` pointing at the old
// object, and it faults -- which is what the first attempt at this did.
//
// The game's own overrides, from its vtables:
//
//   application  0 destructor   3 AppDllUid    12 CreateDocumentL()   13 ?
//   document     0 destructor   9 ?            17 CreateAppUiL()
//
// AppDllUid is the exception: see below.
//
// Destructors stay 9.x: the wrapper is a real 9.x object and has to be torn
// down as one. The old objects leak, which for now costs nothing.
enum { VT_HEADER = 2 };
enum { APP_SLOTS = 18, SLOT_APP_DLL_UID = 5, SLOT_CREATE_DOCUMENT = 17 };
enum { DOC_SLOTS = 23, SLOT_CREATE_APP_UI = 19 };
enum { UI_SLOTS = 48, SLOT_UI_CONSTRUCT = 16 };

// The app UI is the object the framework touches last before it dies, and ours
// was only a CEikAppUi. The framework here is avkon's, and avkon reaches past
// the virtuals into CAknAppUi's own members -- so the wrapper has to be one.
// Neither its constructor nor its vtable is exported by name that we can link
// against, but CAknAppUiBase's constructor is, and the vtable is an export like
// any other. Both are looked up at run time and checked before use, since the
// ordinals come from a source release later than any phone.
enum { AKN_APPUI_BASE_CTOR = 217, AKN_APPUI_VTABLE = 3820, AKN_APPUI_SLOTS = 45 };

static const u16 kAvkonName[] = {'a','v','k','o','n','{','0','0','0','a','0','0','0','0','}',
                                 '[','1','0','0','0','5','6','c','6',']','.','d','l','l'};

enum { OLD_CREATE_DOCUMENT = 12, OLD_UI_CONSTRUCT = 13, OLD_CREATE_APP_UI = 17 };

// The game's app UI ConstructL, old slot 13: BaseConstructL(0), then a trap
// harness, then it builds a control, asks for ApplicationRect, pushes the
// control on the stack, and sets the key block mode -- every one of them a
// framework method called on the old object. Slot 17 is HandleCommandL, which
// compares its argument against 0x100; slot 13 is what is left.
enum { IMPORT_BASECONSTRUCTL = 9 };     // avkon CAknAppUi::BaseConstructL(TInt)

// The control. ConstructL builds one, and unlike the application, the document
// and the app UI, the game constructs it itself -- so its base class has to be
// right, not just wrapped. The N-Gage ROM says what right is:
//
//   CCoeControl   iCoeEnv 0x08   iWin 0x20        (9.x: 0x0c and 0x28)
//   CCoeEnv       iWsSession 0x20  iRootWin 0x2c  iSystemGc 0x34  iScreen 0x3c
//
// and 9.x CCoeEnv holds the same four twelve bytes further along -- measured in
// both ROMs, at all four. The whole tail moved together, so the game can be
// given the real environment as a pointer twelve bytes past it, and every old
// offset it reads lands on the right 9.x field. No copy, no synthetic object:
// the game gets the real window server session and the real screen device, by
// reference, through its own layout.
enum { COEENV_BIAS = 0x0c };
enum { OLD_CONTROL_BYTES = 0x30, OLD_CONTROL_COEENV = 0x08, OLD_CONTROL_WIN = 0x20 };
// Every one of these was measured against its own vtable in the 5320 ROM,
// counting until the table ends, rather than taken from the game's old tables
// or from counting a header. Too many is harmless -- the extra slots are never
// called -- but too few is fatal: CCoeControl::SetExtent calls slot 27, and a
// table copied at 27 slots ends one short of it.
//
//   CCoeControl 44   CEikApplication 18   CAknDocument 23   CAknAppUi 45
//   CTimer 6
enum { NEW_CONTROL_WIN = 0x28, CONTROL_SLOTS = 44 };

// The control is where the game draws, so its overrides have to come back to
// it. Its old vtable overrides four slots, and the two tables were lined up by
// naming both out of their own ROMs and matching the inherited entries between
// them:
//
//   old  0 destructor        -> 9.x keeps its own
//   old  1 OfferKeyEventL    -> 9.x 3    (two arguments: not yet)
//   old 19 FocusChanged      -> 9.x 26
//   old 24 Draw              -> 9.x 41
enum { OLD_CTL_FOCUS = 19, OLD_CTL_DRAW = 24 };
enum { NEW_CTL_FOCUS = 26, NEW_CTL_DRAW = 41 };

// Direct screen access is the first thing that calls the game back. The window
// server aborts it whenever the screen changes hands, and calls the observer
// the game handed to CDirectScreenAccess::NewL -- which is a GCC98r2 mixin
// subobject, vptr eight bytes before slot 0 and entries that are adjustor
// thunks. A 9.x caller reads the offset-to-top word as slot 0 and jumps to
// nothing. So the window server gets an observer of ours instead, two slots
// wide like the interface, each dispatching into the game's the old way.
enum { IMPORT_DSA_NEWL = 460 };         // ws32 CDirectScreenAccess::NewL(...)
enum { IMPORT_DSA_STARTL = 461 };       // ws32 CDirectScreenAccess::StartL()
enum { DSA_SLOTS = 2 };

// The game's graphics object is a CTimer and it adds itself to the active
// scheduler, so the framework does not merely call it -- it owns its request.
// A 9.x CTimer of ours goes to the scheduler instead and the game's is driven
// from its virtuals.
//
// The vtables, both read out of their own ROM rather than counted:
//
//   9.x  0,1 ~CTimer   2 CBase::Extension_   3 DoCancel  4 RunL  5 RunError
//   7.0s 0   ~CTimer   1 DoCancel            2 RunL      3 RunError
//
// The data needs no translation. CActive keeps iStatus at 4 and iActive at 8 in
// both -- 9.x turned iActive into flags, but bit zero is still what ETrue sets,
// and what grew is iLink at the end, which only the framework touches. CTimer's
// own member moved from 0x18 to 0x1c, which is the four bytes of it.
enum { ACTIVE_STATUS = 4, ACTIVE_ACTIVE = 8 };
enum { TIMER_SLOTS = 6, NEW_DOCANCEL = 3, NEW_RUNL = 4, NEW_RUNERROR = 5 };
enum { OLD_DOCANCEL = 1, OLD_RUNL = 2, OLD_RUNERROR = 3 };

enum { IMPORT_CTIMER_CTOR = 391 };      // euser CTimer::CTimer(TInt)

// The game starts its own frame loop the usual way:
//
//   SetActive();                          @ diverted, so the wrapper is active
//   r3 = this + 4;                        @ the old object's iStatus
//   User::RequestComplete(&r3, KErrNone);
//
// which marks our timer active and completes the game's own request status --
// two different words, so the scheduler waits on one that nothing ever
// completes and no frame is ever drawn. Anything completing the old object's
// status means the wrapper's.
enum { IMPORT_REQUEST_COMPLETE = 350 };  // euser User::RequestComplete(TRequestStatus*&, TInt)
enum { IMPORT_CANCEL = 279 };            // euser CActive::Cancel()

// The game does not only import: it loads euser.dll by name and asks it for a
// run of ordinals, then calls each one without checking. An ordinal is a
// build's own numbering with nothing in common between the two -- 799 is
// RDebug::Open in the 7.0s euser and TLex8::Val(TReal64&) in the 9.x one,
// called with a debug channel number for a TLex, which is where it first
// faulted -- so the lookups go through the same signature pairing the imports
// do, in kShimEuser.
//
// What it is resolving is its own decryptor. One function of the game, from
// 0xd5094 to 0xd5254, ships XOR-encrypted, and the five ordinals it asks for
// are RDebug::Open, RThread::Id, RDebug::WriteMemory, User::IMB_Range and
// RChunk::Base: on EKA1 a code segment cannot be written to, so the game
// attaches to itself as a debugger and writes its own plaintext in through
// RDebug::WriteMemory. 9.x has none of the RDebug half -- it went with EKA1 --
// but our code chunk is plain writable memory, so WriteMemory is a copy and
// the thread id it is keyed on need only be consistent with itself. Answer
// those three ourselves, pair the other two, and the game decrypts itself.
enum { IMPORT_LIBRARY_LOOKUP = 326, IMPORT_LIBRARY_LOAD = 325 };
// Which library the ordinals belong to: it loads euser.dll and efsrv.dll, and
// their numberings have nothing to do with each other, so the load is watched
// to know which table a lookup should go through.
enum { LIB_EUSER = 0, LIB_EFSRV = 1, LIB_OTHER = 2 };
enum { OLD_RFSBASE_CLOSE = 15 };
enum { OLD_RDEBUG_OPEN = 799, OLD_RTHREAD_ID = 533, OLD_RDEBUG_WRITEMEMORY = 1233 };

// And one the pairing gets wrong. The N-Gage's euser exports 1679 functions
// where the 7.0 def lists 1680, so the two numberings are not the same all the
// way up, and by 1649 they have parted: the def says User::IMB_Range, which
// takes two arguments and returns nothing, while the game calls 1649 with four
// and treats the answer as an error code, then asks the same object for
// RChunk::Base and keeps that as an address. That is RChunk::CreateLocalCode,
// the def's 1648 -- and the same pair this loader uses to make somewhere to
// put the game.
enum { OLD_CHUNK_CREATELOCALCODE = 1649, NEW_CHUNK_CREATELOCALCODE = 905 };
enum { ON_TIMER = 2, ON_GC = 3 };

enum { IMPORT_DLL_NAME = 2 };           // apparc CApaApplication::DllName() const
enum { IMPORT_COEENV_STATIC = 86 };     // cone CCoeEnv::Static()
enum { IMPORT_COECONTROL_CTOR = 89 };   // cone CCoeControl::CCoeControl()
enum { IMPORT_CREATEWINDOWL = 55 };     // cone CCoeControl::CreateWindowL()
enum { IMPORT_WINDOW = 87 };            // cone CCoeControl::Window() const

// The rest of what ConstructL calls on itself keeps its 9.x implementation and
// only needs the old object swapped for the wrapper. ApplicationRect returns a
// TRect, so r0 is the return buffer and `this` is in r1.
// Shifting the environment answers every field but one. The game's app UI is
// its own class, and it reads its own members straight off whatever
// CCoeEnv::Static()->AppUi() gives back -- so that word has to be the game's
// object, not the wrapper the framework keeps there. Nothing else can be a
// view of the real environment either, because the window server session and
// the screen device the game reads out of it are handed to 9.x functions and
// must stay real. So the game gets a copy: the shifted environment word for
// word, with the app UI put back to its own.
enum { COEENV_VIEW_WORDS = 0x60 / 4, OLD_COEENV_APPUI = 0x18 };

enum { ON_APP_UI = 0, ON_CONTROL = 1 };

// The frame loop is started from inside the game's own FocusChanged and Draw,
// and both gate it on CCoeControl::IsFocused():
//
//   if (iEngine && IsFocused())  Resume(fromFocus);  else  Suspend();
//
// Asked of the old object that nothing ever focuses, the answer is always no
// and the game never starts. Asked of the wrapper -- which is what the control
// stack actually focuses -- it is the real answer, and losing focus still
// suspends the game as the game intends.

struct Divert { u16 import; u8 arg; u8 object; };
static const Divert kDiverts[] = {
    { 172, 1, ON_APP_UI },      // eikcore  CEikAppUi::ApplicationRect() const
    {  39, 0, ON_APP_UI },      // avkon    CAknAppUi::SetKeyBlockMode(TAknKeyBlockMode)
    {  98, 0, ON_CONTROL },     // cone     the Nokia export standing in for SetRect
    {  49, 0, ON_CONTROL },     // cone     CCoeControl::ActivateL()
    {  68, 0, ON_CONTROL },     // cone     CCoeControl::IsFocused() const
    {  46, 0, ON_GC },          // bitgdi   CFbsBitGc::SetClippingRegion(const TRegion*)
    { 286, 0, ON_TIMER },       // euser    CTimer::ConstructL()
    { 268, 0, ON_TIMER },       // euser    CTimer::After(TTimeIntervalMicroSeconds32)
    { 266, 0, ON_TIMER },       // euser    CActiveScheduler::Add(CActive*)
    { 358, 0, ON_TIMER },       // euser    CActive::SetActive()
};

// AddToStackL is the one that needs both at once: the app UI it is called on
// and the control it is handed.
enum { IMPORT_ADDTOSTACKL = 51 };

// EIKAPPUI.H, as gate 5 established.
enum { ENoAppResourceFile = 0x01, ENoScreenFurniture = 0x04 };

// This program has no writable globals -- the image declares no .bss -- so each
// wrapper carries its counterpart itself, parked well past the end of any real
// 9.x object in the 2 KB we give it.
enum { WRAP_BYTES = 2048, WRAP_OLD = WRAP_BYTES / 4 - 1, WRAP_CTX = WRAP_BYTES / 4 - 2 };

// What the shim needs to know and cannot keep in a global. Every wrapper holds
// a pointer to it, so any of them can find it from `this`.
struct Context {
    u32 *wrapUi;
    u32 *wrapControl;
    const u16 *path;        // where the game was loaded from
    int pathLen;
    u32 lastImport;         // the last import the game called: see the tracer
    u32 *oldObserver;       // the game's MDirectScreenAccess, old layout
    u32 *oldControl;        // the game's CCoeControl, old layout
    u32 *oldTimer;          // the game's CTimer, old layout
    u32 *wrapTimer;         // the 9.x CTimer the scheduler owns
    u32 newTimerCtor;       // 9.x CTimer::CTimer(TInt), as the shim resolved it
    u32 timerThunks[3];     // DoCancel, RunL, RunError, built in the code chunk
    u32 reached;            // which of the game's callbacks have been entered
    u32 cppRuntime;         // see drtaeabi_pure_virtual: the reference is the point

    // The black box. A phone reports a fault as KERN-EXEC 3 and nothing else,
    // and it will not dispatch one to a handler, so the trace has to survive
    // the crash instead of escaping it: a timer writes the last import to a
    // file every few milliseconds, and the next run reads it back and reports
    // it. Two launches, one answer.
    u32 boxFs[2];
    u32 boxFile[4];
    u32 boxData[BOX_WORDS];
    u32 pathIndex;          // which candidate the game was loaded from
    u32 codeBase;           // where the game was loaded, so callers read as offsets
    u32 frames;             // how many times the frame loop has come round
    u32 spTop;              // where the stack started
    u32 spLow;              // and the deepest it has been seen
    u32 boxDes[2];
    u32 noteText[4];        // seven characters, for the emulator's log
    u32 noteDes[2];
    u32 traceCount;         // how many imports have gone past
    u32 lastCall;           // the last slot of ours the framework called
    u32 avkon;              // an RLibrary on avkon, for what it does not export
    u32 newBaseConstructL;  // avkon's CAknAppUi::BaseConstructL, as resolved
    u32 newRequestComplete; // euser's User::RequestComplete, as resolved
    u32 *dsaReal;           // the CDirectScreenAccess ws32 made
    u32 *dsaShadow;         // and the old-layout view of it the game holds
    u32 *realGc;            // the 9.x CFbsBitGc inside it
    u32 *fakeGc;            // and the old-vtable stand-in the game calls
    u32 newDsaStartL;       // ws32's CDirectScreenAccess::StartL, as resolved
    u32 *oldUi;             // the game's CEikAppUi, old layout
    u32 *coeEnv;            // the environment as it really is
    u32 *oldForeground;     // the game's MCoeForegroundObserver, old layout
    u32 coeEnvView[COEENV_VIEW_WORDS];  // the environment as the game must see it
    u32 newCancel;          // euser's CActive::Cancel, as resolved
    u32 noopFn;             // what a lookup answers when 9.x dropped the export
    u32 writeFn;            // and what stands in for RDebug::WriteMemory
    u32 idFn;               // RThread::Id: a TThreadId of zero, in r0 and r1
    u32 newLibraryLookup;   // euser's RLibrary::Lookup, as resolved
    u32 newLibraryLoad;     // euser's RLibrary::Load, as resolved
    void *dynLib[2];        // the RLibrary the game opened on each of the two
    u8 *spare;              // unused executable room, handed out as needed
    u8 *spareEnd;
};

static Context *context_of(const void *wrapper)
{
    return (Context *)((const u32 *)wrapper)[WRAP_CTX];
}

static const u32 *vtable_of(const u32 *object)
{
    return (const u32 *)object[0] - VT_HEADER;
}

static u32 *copy_vtable(const u32 *real, int slots)
{
    u32 *vt = (u32 *)user_allocz((VT_HEADER + slots) * 4);
    if (!vt) PANIC(CAT_MEM, -30);
    for (int i = 0; i < VT_HEADER + slots; i++)
        vt[i] = real[i];
    return vt;
}

// The other direction. When the game calls a framework method on itself, the
// 9.x implementation must not see the old object, so the call is diverted to
// one of ours -- which needs the context, and gets it in r2:
//
//   ldr r2, [pc, #4]    @ the context, baked in when the stub is built
//   ldr pc, [pc, #4]    @ and on to our implementation
//   .word context
//   .word our function
//
// r0 and r1 pass through untouched, so the old arguments arrive as they were.
static u32 ctx_thunk(u8 *code, const void *ctx, u32 target)
{
    u32 *b = (u32 *)code;
    b[0] = 0xE59F2004;                  // ldr r2, [pc, #4]
    b[1] = 0xE59FF004;                  // ldr pc, [pc, #4]
    b[3] = (u32)ctx;
    b[4] = target;
    user_imb_range(b, b + 5);
    return (u32)b;
}

// The same, for a call that already uses r0 to r2.
//
//   ldr r3, [pc, #4]
//   ldr pc, [pc, #4]
static u32 ctx3_thunk(u8 *code, const void *ctx, u32 target)
{
    u32 *b = (u32 *)code;
    b[0] = 0xE59F3004;
    b[1] = 0xE59FF004;
    b[3] = (u32)ctx;
    b[4] = target;
    user_imb_range(b, b + 5);
    return (u32)b;
}

// The simpler diversion: the 9.x implementation is the right one, it just must
// not be handed the old object. The wrapper does not exist when the stub is
// built, so the thunk reads it from the context each time:
//
//   ldr rN, [pc, #8]    @ rN = the cell holding the wrapper
//   ldr rN, [rN]
//   ldr pc, [pc, #4]
//   .word cell
//   .word the 9.x function
static u32 this_thunk(u8 *code, const void *cell, u32 target, int reg)
{
    u32 *b = (u32 *)code;
    b[0] = 0xE59F0008 | ((u32)reg << 12);           // ldr rN, [pc, #8]
    b[1] = 0xE5900000 | ((u32)reg << 16) | ((u32)reg << 12);
    b[2] = 0xE59FF004;                              // ldr pc, [pc, #4]
    b[4] = (u32)cell;
    b[5] = target;
    user_imb_range(b, b + 6);
    return (u32)b;
}

// A phone reports a fault as KERN-EXEC 3 and nothing else -- no address, no
// instruction. So every import the game makes goes through this first, which
// records which one it was and jumps on. r0 and r12 are saved across the
// record; lr is the caller's and is never touched, and neither are the flags.
//
//   stmdb sp!, {r0, r12}
//   ldr   r0, [pc, #12]     @ where to record it
//   ldr   r12, [pc, #12]    @ which import
//   str   r12, [r0]
//   ldmia sp!, {r0, r12}
//   ldr   pc, [pc, #4]      @ and on to whatever answers it
enum { TRACE = 48 };

extern "C" void gate6_trace(u32 index, Context *c, u32 caller);
extern "C" void gate6_slot(u32 code, Context *c, u32 caller);

// Records `value` through `note` and carries on to `target`, leaving every
// argument register as it found them. lr still holds the caller's return
// address when the note is made, which is how a trace says where a call came
// from and not only what it was.
static u32 trace_thunk(u8 *code, const void *ctx, u32 value, u32 target, u32 note)
{
    u32 *b = (u32 *)code;
    b[0] = 0xE92D500F;                  // stmdb sp!, {r0-r3, r12, lr}  -- 24 bytes, aligned
    b[1] = 0xE59F0014;                  // ldr   r0, [pc, #20]   -- which import
    b[2] = 0xE59F1014;                  // ldr   r1, [pc, #20]   -- the context
    b[3] = 0xE59FC014;                  // ldr   r12, [pc, #20]
    b[4] = 0xE1A0200E;                  // mov   r2, lr          -- who called
    b[5] = 0xE12FFF3C;                  // blx   r12
    b[6] = 0xE8BD500F;                  // ldmia sp!, {r0-r3, r12, lr}
    b[7] = 0xE59FF008;                  // ldr   pc, [pc, #8]
    b[8] = value;
    b[9] = (u32)ctx;
    b[10] = note;
    b[11] = target;
    user_imb_range(b, b + 12);
    return (u32)b;
}

// Then a fault says where it happened, in the only terms the phone gives us.
extern "C" void gate6_fault(Context *c, int type)
{
    PANIC(CAT_FLT, (int)(c->lastImport * 100 + (u32)(type & 63)));
}

// Both at once, for a call that is given one wrapper and made on another. Five
// instructions and three words is exactly the slot, with nothing to spare.
static u32 pair_thunk(u8 *code, const void *cell0, const void *cell1, u32 target)
{
    u32 *b = (u32 *)code;
    b[0] = 0xE59F000C;                  // ldr r0, [pc, #12]
    b[1] = 0xE5900000;                  // ldr r0, [r0]
    b[2] = 0xE59F1008;                  // ldr r1, [pc, #8]
    b[3] = 0xE5911000;                  // ldr r1, [r1]
    b[4] = 0xE59FF004;                  // ldr pc, [pc, #4]
    b[5] = (u32)cell0;
    b[6] = (u32)cell1;
    b[7] = target;
    user_imb_range(b, b + 8);
    return (u32)b;
}

// Once the game has its own copy of the environment it also calls cone on it,
// and a copy is not something cone can be handed. So the calls go back to the
// real one -- and the observer that goes with this one is a GCC98r2 mixin,
// which a 9.x caller cannot use, so it gets the same two-slot stand-in the
// direct screen access observer gets.
//
//   ldr r12, [pc, #16]      @ where to keep the game's observer
//   str r1, [r12]
//   ldr r12, [pc, #12]      @ the real environment
//   ldr r0, [r12]
//   ldr r1, [pc, #8]        @ ours
//   ldr pc, [pc, #8]
static u32 fg_thunk(u8 *code, const void *savedCell, const void *envCell,
                    const void *observer, u32 target)
{
    u32 *b = (u32 *)code;
    b[0] = 0xE59FC010;
    b[1] = 0xE58C1000;
    b[2] = 0xE59FC00C;
    b[3] = 0xE59C0000;
    b[4] = 0xE59F1008;
    b[5] = 0xE59FF008;
    b[6] = (u32)savedCell;
    b[7] = (u32)envCell;
    b[8] = (u32)observer;
    b[9] = target;
    user_imb_range(b, b + 10);
    return (u32)b;
}

enum { IMPORT_ADD_FOREGROUND_OBSERVER = 50, FOREGROUND_SLOTS = 2 };
enum { OLD_FG_GAINING = 0, OLD_FG_LOSING = 1 };

extern "C" void gate6_foreground_gaining(void *, u32, Context *c)
{
    if (c->oldForeground) old_call(c->oldForeground, OLD_FG_GAINING);
}

extern "C" void gate6_foreground_losing(void *, u32, Context *c)
{
    if (c->oldForeground) old_call(c->oldForeground, OLD_FG_LOSING);
}

// ---- the app UI ------------------------------------------------------------

// The game asks CAknAppUi to base-construct the old object. Ours is a
// CEikAppUi, built from the constructors gate 5 used, so it gets the CEikAppUi
// one -- and the flags gate 5 established rather than the game's zero, since
// nothing here has screen furniture to construct yet.
// ---- the black box ---------------------------------------------------------

struct CallBack { int (*fn)(void *); void *ptr; };

extern "C" {
void cperiodic_start(void *self, int delay, int interval, CallBack cb);
void rdebug_rawprint(const void *text);
}

// On C: rather than the memory card. Two reasons: the card is the one piece of
// this the phone has a removable driver for, and internal flash answers a
// flush faster, which is what lets every record be flushed again.
static const u16 kBoxPath[] = {'C',':','\\','g','6','b','o','x','.','d','a','t'};

// A record left by a different build is worse than no record: it reads back as
// a plausible number and says nothing. So the file carries what wrote it.
enum { BOX_MAGIC = 0x47364234 };        // "G6B4"
enum { BOX_NONE = 0xFFFFFFFF, BOX_ARMED = 0xFFFFFFFE };
enum { EFileWrite = 0x200, EFileShareAny = 0x30 };

static void box_name(Ptrc16 *name)
{
    name->lengthAndType = ((u32)EPtrC << KTypeShift) | (u32)(sizeof kBoxPath / 2);
    name->text = kBoxPath;
}

// Writing is cheap enough to do on every import; it is the flush that costs,
// and the file server still has what was written when the process dies.
// The one thing a fault leaves no trace of is how much room it had left. Every
// marker notes where the stack had got to, and the record carries the deepest.
static void stack_mark(Context *c)
{
    const u32 sp = (u32)__builtin_frame_address(0);
    if (!c->spTop) c->spTop = sp;
    if (sp < c->spLow || !c->spLow) c->spLow = sp;
}

static void box_write(Context *c)
{
    c->boxData[0] = BOX_MAGIC;
    c->boxData[1] = c->lastImport;
    c->boxData[2] = c->reached;
    c->boxData[3] = c->traceCount;
    c->boxData[BOX_PATH] = c->pathIndex;
    c->boxData[BOX_SLOT] = c->lastCall;
    c->boxData[BOX_FRAMES] = c->frames;
    c->boxData[BOX_STACK] = c->spTop - c->spLow;
    c->boxDes[0] = ((u32)EPtrC << KTypeShift) | BOX_BYTES;
    c->boxDes[1] = (u32)c->boxData;
    file_write_at(c->boxFile, 0, c->boxDes);
}

static void box_flush(Context *c)
{
    box_write(c);
    file_flush(c->boxFile);
}

static const u16 kTextPath[] = {'C',':','\\','g','6','b','o','x','.','t','x','t'};

static int put_hex(u8 *out, u32 v)
{
    u8 digits[8];
    int n = 0;
    do { const u32 d = v & 0xF; digits[n++] = (u8)(d < 10 ? '0' + d : 'a' + d - 10); v >>= 4; }
    while (v);
    for (int i = 0; i < n; i++) out[i] = digits[n - 1 - i];
    return n;
}

static int put_u32(u8 *out, u32 v)
{
    u8 digits[10];
    int n = 0;
    do { digits[n++] = (u8)('0' + v % 10); v /= 10; } while (v);
    for (int i = 0; i < n; i++) out[i] = digits[n - 1 - i];
    return n;
}

// A panic carries one number. This carries the whole tail, in a file the phone
// can open: how many imports went past, which one it was on, what had happened
// and, oldest first, the last sixteen imports the game made. Written on the
// launch after the one that stopped, beside the record it is made from.
static void box_report(Context *c, u32 count)
{
    u8 text[1024];
    int n = 0;
    const u8 kSteps[] = { 's','t','e','p','s',' ' };
    const u8 kLast[] = { '\n','l','a','s','t',' ' };
    const u8 kFlags[] = { '\n','f','l','a','g','s',' ' };
    const u8 kPath[] = { '\n','p','a','t','h',' ' };
    const u8 kTail[] = { '\n','t','a','i','l' };
    for (u32 i = 0; i < sizeof kSteps; i++) text[n++] = kSteps[i];
    n += put_u32(text + n, count);
    for (u32 i = 0; i < sizeof kLast; i++) text[n++] = kLast[i];
    n += put_u32(text + n, c->boxData[1]);
    for (u32 i = 0; i < sizeof kFlags; i++) text[n++] = kFlags[i];
    n += put_u32(text + n, c->boxData[2]);
    for (u32 i = 0; i < sizeof kPath; i++) text[n++] = kPath[i];
    n += put_u32(text + n, c->boxData[BOX_PATH]);
    for (u32 i = 0; i < sizeof kTail; i++) text[n++] = kTail[i];
    for (u32 i = 0; i < BOX_RING; i++) {
        text[n++] = ' ';
        n += put_u32(text + n, c->boxData[4 + ((count + i) & (BOX_RING - 1))]);
    }
    const u8 kSlot[] = { '\n','s','l','o','t',' ' };
    for (u32 i = 0; i < sizeof kSlot; i++) text[n++] = kSlot[i];
    n += put_hex(text + n, c->boxData[BOX_SLOT]);
    const u8 kFrames[] = { '\n','f','r','a','m','e','s',' ' };
    for (u32 i = 0; i < sizeof kFrames; i++) text[n++] = kFrames[i];
    n += put_u32(text + n, c->boxData[BOX_FRAMES]);
    const u8 kStack[] = { '\n','s','t','a','c','k',' ' };
    for (u32 i = 0; i < sizeof kStack; i++) text[n++] = kStack[i];
    n += put_u32(text + n, c->boxData[BOX_STACK]);
    const u8 kHits[] = { '\n','h','i','t','s' };
    for (u32 i = 0; i < sizeof kHits; i++) text[n++] = kHits[i];
    for (u32 i = 0; i < BOX_MARKERS; i++) {
        text[n++] = ' ';
        n += put_u32(text + n, c->boxData[BOX_HITS + i]);
    }
    const u8 kFrom[] = { '\n','f','r','o','m' };
    for (u32 i = 0; i < sizeof kFrom; i++) text[n++] = kFrom[i];
    for (u32 i = 0; i < BOX_RING; i++) {
        text[n++] = ' ';
        n += put_hex(text + n, c->boxData[BOX_FROM + ((count + i) & (BOX_RING - 1))]);
    }
    text[n++] = '\n';

    u32 file[4] = { 0, 0, 0, 0 };
    Ptrc16 name;
    name.lengthAndType = ((u32)EPtrC << KTypeShift) | (u32)(sizeof kTextPath / 2);
    name.text = kTextPath;
    if (file_replace(file, c->boxFs, &name, EFileWrite | EFileShareAny) == 0) {
        u32 des[2];
        des[0] = ((u32)EPtrC << KTypeShift) | (u32)n;
        des[1] = (u32)text;
        file_write_at(file, 0, des);
        file_flush(file);
        rhandle_close(file);
    }
}

// The trace itself does the recording, because the crash we are after happens
// while the framework is still starting the application up and the active
// scheduler has not run yet -- a timer never gets a turn. Every import goes
// through here; every so many of them reach the disk.
enum { BOX_EVERY = 16 };
// How many records go by between flushes. Thinning this was a mistake: a write
// that has not been flushed is still in the file server when the phone goes
// down, and goes down with it, so the record was reading up to sixty-three
// events stale exactly when it mattered. Back to every one.
enum { BOX_SETTLE = 1 };
enum { REACHED_LEAVE = 64, REACHED_EXIT = 128 };  // how the game ended, if it did

// The emulator hears RDebug, and a phone does not, which makes this the one
// instrument that can say what happened in what order rather than only what
// happened last. "G6 01cc" is import 460; "G6+0504" is a call into one of our
// own slots.
// Every import is a lot of them; a phone would spend real time on it, so the
// per-import half is one constant away from being off.
enum { TRACE_IMPORTS = 0 };

static void note(Context *c, u32 value, u16 sign)
{
    u16 *b = (u16 *)c->noteText;
    b[0] = 'G';
    b[1] = '6';
    b[2] = sign;
    for (int i = 0; i < 4; i++) {
        const u32 d = (value >> (12 - 4 * i)) & 0xF;
        b[3 + i] = (u16)(d < 10 ? '0' + d : 'a' + d - 10);
    }
    c->noteDes[0] = ((u32)EPtrC << KTypeShift) | 7;
    c->noteDes[1] = (u32)c->noteText;
    rdebug_rawprint(c->noteDes);
}

// The phone goes down inside the obfuscated state machine at 0xc9cd4, between
// one import and the next, so the record has nothing to say about where. A
// breadcrumb is a marker planted at an address in the game: the instruction
// there is replaced with a branch to a stub that records which one was
// reached, puts the flags and registers back, runs the instruction it
// displaced, and returns to what followed it. These seventeen are the cases of
// that machine's jump table, which is as fine a grain as its own structure
// offers. Two of them read the program counter and cannot be moved, so they
// are left alone and never report.
enum { CRUMB_BYTES = 80, CRUMB_FIRST = 900 };
static const u32 kCrumb[] = {
    // The seventeen cases of the machine's jump table.
    0x0c9d84, 0x0c9dc0, 0x0ca470, 0x0c9e2c, 0x0c9e38, 0x0c9e44, 0x0c9e6c,
    0x0c9fb0, 0x0ca014, 0x0ca168, 0x0ca1d0, 0x0ca238, 0x0ca29c, 0x0ca2c4,
    0x0ca2e0, 0x0ca2fc, 0x0ca390,
    // And through the body of case 8, every forty bytes or so. Case 9 hands
    // to case 8 -- each case ends by loading a state and re-entering the
    // dispatcher, so the sequence reads straight out of the literals -- and
    // case 8 is where the phone stops reporting. It is also the one case whose
    // first instruction reads the program counter, which is why nothing was
    // planted in it the first time round.
    0x0ca038, 0x0ca060, 0x0ca088, 0x0ca0b0, 0x0ca0d8, 0x0ca100,
    0x0ca128, 0x0ca150,
    // And two that cut the remaining gap in three: the tail of case 9, and
    // the dispatcher every case returns to. 926 without 927 says it died in
    // case 9's own body; 927 without 917 says it died getting out of the
    // jump table.
    0x0ca1b4, 0x0c9d20,
    // Case 9's body is eighteen instructions of stack traffic and arithmetic,
    // and the phone dies somewhere inside it. One marker every few
    // instructions says which.
    0x0ca170, 0x0ca178, 0x0ca180, 0x0ca1a4, 0x0ca1ac, 0x0ca1b0,
};

// An instruction can only be moved if it does not depend on where it is.
static int crumb_safe(u32 w)
{
    if ((w >> 28) != 0xE) return 0;             // only the unconditional ones
    const u32 cls = (w >> 25) & 7;
    if (cls >= 5) return 0;                     // branches, coprocessor, SWI
    if (((w >> 16) & 0xF) == 15) return 0;      // reads the program counter
    if (((w >> 12) & 0xF) == 15) return 0;      // or writes it
    if ((cls == 0 || cls == 3) && (w & 0xF) == 15) return 0;
    if (cls == 4 && (w & 0x8000)) return 0;     // or carries it in a list
    return 1;
}

// User::Leave and User::Exit are where the game gives up, so those two say
// where from as well.
enum { IMPORT_LEAVE = 324, IMPORT_EXIT = 308 };

// A breadcrumb goes into the same ring as the imports, so the two interleave
// and the order is the order things happened in. The marker reads as 900 and
// up, which no import index does, and the caller column carries where it was
// planted.
extern "C" void gate6_crumb(u32 marker, Context *c, u32 site)
{
    stack_mark(c);
    if (marker - CRUMB_FIRST < BOX_MARKERS)
        c->boxData[BOX_HITS + (marker - CRUMB_FIRST)]++;
    c->lastImport = marker;
    const u32 slot = c->traceCount & (BOX_RING - 1);
    c->boxData[4 + slot] = marker;
    c->boxData[BOX_FROM + slot] = site;
    c->traceCount++;
    if ((c->traceCount % BOX_SETTLE) == 0) box_flush(c); else box_write(c);
}

//   stmdb sp!, {r0-r3, r12, lr}
//   mrs   r0, cpsr
//   stmdb sp!, {r0, r1}
//   ldr   r0, [pc, #36]     @ which one
//   ldr   r1, [pc, #36]     @ the context
//   ldr   r2, [pc, #36]     @ where it ended up being planted
//   ldr   r12, [pc, #36]
//   blx   r12
//   ldmia sp!, {r0, r1}
//   msr   cpsr_f, r0
//   ldmia sp!, {r0-r3, r12, lr}
//   <the instruction that used to be there>
//   ldr   pc, [pc, #-4]     @ and on with the rest of it
// Where the named instruction cannot be moved, the next few are tried: a
// prologue runs straight through, so a marker a little further in says the
// same thing. The search stops at anything that branches, since past that the
// marker would no longer mean the case was entered.
static void crumb_plant(Context *c, u8 *base, u32 at, u32 marker)
{
    u32 *site = 0;
    u32 original = 0;
    for (u32 i = 0; i < 8; i++) {
        u32 *p = (u32 *)(base + at + 4 * i);
        if (crumb_safe(*p)) { site = p; original = *p; break; }
        if (((*p >> 25) & 7) >= 5) break;       // a branch: go no further
    }
    if (!site || c->spare + CRUMB_BYTES > c->spareEnd)
        return;
    u32 *b = (u32 *)c->spare;
    c->spare += CRUMB_BYTES;
    b[0] = 0xE92D500F;  b[1] = 0xE10F0000;  b[2] = 0xE92D0003;
    b[3] = 0xE59F0024;  b[4] = 0xE59F1024;  b[5] = 0xE59F2024;
    b[6] = 0xE59FC024;  b[7] = 0xE12FFF3C;  b[8] = 0xE8BD0003;
    b[9] = 0xE128F000;  b[10] = 0xE8BD500F; b[11] = original;
    b[12] = 0xE51FF004; b[13] = (u32)(site + 1);
    b[14] = marker;     b[15] = (u32)c;
    b[16] = (u32)site - (u32)base;
    b[17] = (u32)&gate6_crumb;
    user_imb_range(b, b + 18);
    *site = 0xEA000000 | ((((u32)b - (u32)site - 8) >> 2) & 0x00FFFFFF);
    user_imb_range(site, site + 1);
}

extern "C" void gate6_trace(u32 index, Context *c, u32 caller)
{
    stack_mark(c);
    if (TRACE_IMPORTS)
        note(c, index, ' ');
    if (index == IMPORT_LEAVE || index == IMPORT_EXIT) {
        c->reached |= (index == IMPORT_LEAVE) ? REACHED_LEAVE : REACHED_EXIT;
        note(c, caller >> 16, 'R');
        note(c, caller & 0xFFFF, 'r');
        box_flush(c);
    }
    c->lastImport = index;
    const u32 slot = c->traceCount & (BOX_RING - 1);
    c->boxData[4 + slot] = index;
    c->boxData[BOX_FROM + slot] = caller - c->codeBase;
    // Every import is written, which costs the file server a message and the
    // card nothing. Flushing is what reaches the card, so it happens rarely.
    ++c->traceCount;
    if ((c->traceCount % BOX_SETTLE) == 0)
        box_flush(c);
    else
        box_write(c);
}

// The framework calling one of our objects. Rare enough to write out every
// time, so the record is exact rather than to the nearest sixteen.
enum { REACHED_SLOT = 16 };

extern "C" void gate6_slot(u32 code, Context *c, u32)
{
    note(c, code, '+');
    c->lastCall = code;
    c->reached |= REACHED_SLOT;         // so a zero can be told from a silence
    box_flush(c);
}

// Every slot of a wrapper's vtable, so that whatever the framework does to it
// last is on record. The object is named in the top byte.
enum { OBJ_APP = 1, OBJ_DOC = 2, OBJ_UI = 3, OBJ_CONTROL = 4, OBJ_TIMER = 5 };

static void instrument(Context *c, u32 *vt, int slots, u32 object)
{
    for (int i = 0; i < slots; i++) {
        if (c->spare + TRACE > c->spareEnd)
            return;
        vt[VT_HEADER + i] = trace_thunk(c->spare, c, (object << 8) | (u32)i,
                                        vt[VT_HEADER + i], (u32)&gate6_slot);
        c->spare += TRACE;
    }
}

// There was a timer here that flushed the record every five milliseconds. It
// was written before every import wrote its own record, when the worry was a
// fault arriving long after the last import; it has been redundant since, and
// it was doing two hundred RFile::Flush calls a second to a memory card for as
// long as the game ran. On a host file that costs nothing, which is why the
// emulator never minded. Every one of those flushes commits to the card on a
// phone, and the reboots -- hardware only, asynchronous, no panic, no leave,
// always at about the same point because the game takes about the same time to
// get there -- fit that and nothing in the game's own code.
static void box_start(Context *) {}

// ---- the timer -------------------------------------------------------------

typedef void *(*TimerCtor)(void *self, int priority);

// Which of the ways back into the game have been taken. A phone can report one
// number and only once, so the ones that must not stop are recorded and the one
// under test carries the record out with it.
enum { REACHED_ABORT = 1, REACHED_RESTART = 2, REACHED_DOCANCEL = 4, REACHED_RUNERROR = 8 };
enum { REACHED_RUNL = 32 };   // the frame loop ran at least once

extern "C" void gate6_timer_docancel(void *, u32, Context *c)
{
    c->reached |= REACHED_DOCANCEL;
    old_call(c->oldTimer, OLD_DOCANCEL);
}

static void dsa_refresh(Context *c);

extern "C" void gate6_timer_runl(void *, u32, Context *c)
{
    c->reached |= REACHED_RUNL;
    c->frames++;

    // The request completed into the wrapper, and the game reads the result out
    // of its own object, so carry it across before handing over.
    c->oldTimer[ACTIVE_STATUS / 4] = c->wrapTimer[ACTIVE_STATUS / 4];
    c->oldTimer[ACTIVE_ACTIVE / 4] = c->wrapTimer[ACTIVE_ACTIVE / 4];

    // The frame the game is about to draw reads the direct screen access
    // object, so its view of it is brought up to date first.
    dsa_refresh(c);

    old_call(c->oldTimer, OLD_RUNL);
}

extern "C" u32 gate6_timer_runerror(void *, u32 error, Context *c)
{
    c->reached |= REACHED_RUNERROR;
    return old_call1(c->oldTimer, OLD_RUNERROR, error);
}

extern "C" void gate6_request_complete(u32 **status, int reason, Context *c)
{
    typedef void (*RequestComplete)(u32 **, int);
    if (c->oldTimer && c->wrapTimer &&
        *status == (u32 *)((u8 *)c->oldTimer + ACTIVE_STATUS))
        *status = (u32 *)((u8 *)c->wrapTimer + ACTIVE_STATUS);
    ((RequestComplete)c->newRequestComplete)(status, reason);
}

// The game constructs its CTimer; ours is constructed alongside it, and from
// here on everything the game does to its own goes to ours instead. A GCC98r2
// constructor returns the object, which is still the game's.
extern "C" void *gate6_ctimer_ctor(u32 *oldSelf, int priority, Context *c)
{
    c->oldTimer = oldSelf;

    u32 *t = (u32 *)user_allocz(WRAP_BYTES);
    if (!t) PANIC(CAT_MEM, -35);
    ((TimerCtor)c->newTimerCtor)(t, priority);

    u32 *vt = copy_vtable(vtable_of(t), TIMER_SLOTS);
    vt[VT_HEADER + NEW_DOCANCEL] = c->timerThunks[0];
    vt[VT_HEADER + NEW_RUNL] = c->timerThunks[1];
    vt[VT_HEADER + NEW_RUNERROR] = c->timerThunks[2];
    instrument(c, vt, TIMER_SLOTS, OBJ_TIMER);
    t[0] = (u32)(vt + VT_HEADER);

    c->wrapTimer = t;
    return oldSelf;
}

// ---- direct screen access --------------------------------------------------

extern "C" void gate6_dsa_slot0(void *, u32 reason, Context *c)
{
    c->reached |= REACHED_ABORT;
    old_call1(c->oldObserver, 0, reason);
}

extern "C" void gate6_dsa_slot1(void *, u32 reason, Context *c)
{
    c->reached |= REACHED_RESTART;
    old_call1(c->oldObserver, 1, reason);
}

// CDirectScreenAccess is the one class the game reaches into rather than
// calls: Gc(), ScreenDevice() and DrawingRegion() are inline in ws32.h, so the
// game's code holds their offsets. Read out of both ROMs, 7.0s keeps them at
// 0x18, 0x1c and 0x20 and 9.x at 0x1c, 0x20 and 0x24 -- one word later, all
// three, because EKA2's CActive grew by a word.
//
// Shifting the pointer by that word is not enough, though, and the first
// hardware run showed why: the class is a CActive, and iStatus at 4 and
// iActive at 8 did not move. The game reads iActive every frame to decide
// whether to draw, so a shifted pointer has it reading the scheduler's list
// instead. So the game gets a shadow with the old layout, filled from the real
// object and refreshed every frame from RunL, and the two calls it makes on it
// -- StartL and CActive::Cancel -- are turned back.
enum { OLD_DSA_ACTIVE = 8, OLD_DSA_GC = 0x18, OLD_DSA_DEVICE = 0x1c,
       OLD_DSA_REGION = 0x20, OLD_DSA_BYTES = 0x28 };
enum { NEW_DSA_GC = 0x1c, NEW_DSA_DEVICE = 0x20, NEW_DSA_REGION = 0x24 };

static void dsa_refresh(Context *c)
{
    if (!c->dsaReal || !c->dsaShadow)
        return;
    const u32 *real = c->dsaReal;
    u32 *shadow = c->dsaShadow;
    shadow[ACTIVE_STATUS / 4] = real[ACTIVE_STATUS / 4];
    shadow[OLD_DSA_ACTIVE / 4] = real[OLD_DSA_ACTIVE / 4];
    c->realGc = (u32 *)real[NEW_DSA_GC / 4];
    // Not the real graphics context: the game calls it by vtable slot, and the
    // two vtables do not line up. What it gets is the stand-in built below.
    shadow[OLD_DSA_GC / 4] = (u32)c->fakeGc;
    shadow[OLD_DSA_DEVICE / 4] = real[NEW_DSA_DEVICE / 4];
    shadow[OLD_DSA_REGION / 4] = real[NEW_DSA_REGION / 4];
}

// Remember the observer the game passed, put ours in its place, keep what came
// back and hand the shadow over instead. r3 is the fourth argument and the
// only one that changes.
//
//   stmdb sp!, {r12, lr}
//   ldr   r12, [pc, #32]    @ where to keep the game's observer
//   str   r3, [r12]
//   ldr   r3, [pc, #28]     @ ours
//   ldr   r12, [pc, #28]    @ CDirectScreenAccess::NewL
//   blx   r12
//   ldr   r12, [pc, #20]    @ where the real one goes
//   str   r0, [r12]
//   ldr   r12, [pc, #16]    @ and the shadow comes back
//   ldr   r0, [r12]
//   ldmia sp!, {r12, pc}
static u32 dsa_thunk(u8 *code, const void *cell, const void *observer, u32 target,
                     const void *realCell, const void *shadowCell)
{
    u32 *b = (u32 *)code;
    b[0] = 0xE92D5000;
    b[1] = 0xE59FC020;
    b[2] = 0xE58C3000;
    b[3] = 0xE59F301C;
    b[4] = 0xE59FC01C;
    b[5] = 0xE12FFF3C;
    b[6] = 0xE59FC018;
    b[7] = 0xE58C0000;
    b[8] = 0xE59FC014;
    b[9] = 0xE59C0000;
    b[10] = 0xE8BD9000;
    b[11] = (u32)cell;
    b[12] = (u32)observer;
    b[13] = target;
    b[14] = (u32)realCell;
    b[15] = (u32)shadowCell;
    user_imb_range(b, b + 16);
    return (u32)b;
}

// The game blits its finished frame with iGc->vtable[46](TPoint&, CFbsBitmap*)
// -- by slot, not by name -- and the two vtables do not line up: the 7.0s
// CFbsBitGc has 51 virtuals, 9.x has more and in a different order, starting
// with the second destructor Itanium adds and CBase::Extension_ after it. Slot
// 46 there is BitBlt(const TPoint&, const CFbsBitmap*); here it is 57. Calling
// 57's neighbour instead is what put a band of pixels across the top of the
// screen and then took the phone down with it.
//
// So the game is handed an object of ours with a vtable in the old shape,
// every slot a thunk that swaps in the real context and jumps through its own.
// The pairing is by signature, read out of the CFbsBitGc vtable in each ROM;
// 41 and 42 are the two the old table does not export, and nothing calls them.
enum { OLD_GC_SLOTS = 51, GC_NONE = 0xFF };
static const u8 kGcSlot[OLD_GC_SLOTS] = {
     0,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
    18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
    34, 35, 36, 37, 38, 39, 40, 43, 44, GC_NONE, GC_NONE, 54, 55, 56,
    57, 58, 59, 60, 61,
};

// Swap `this` for the real graphics context and go through its own vtable.
//
//   ldr r12, [pc, #8]      @ where the real one is kept
//   ldr r0, [r12]
//   ldr r12, [r0]          @ its vtable
//   ldr pc, [r12, #slot*4]
static u32 gc_thunk(u8 *code, const void *cell, u32 slot)
{
    u32 *b = (u32 *)code;
    b[0] = 0xE59FC008;
    b[1] = 0xE59C0000;
    b[2] = 0xE59CC000;
    b[3] = 0xE59CF000 | (slot * 4);
    b[4] = (u32)cell;
    user_imb_range(b, b + 5);
    return (u32)b;
}

enum { GC_THUNK_BYTES = 20 };

// A diagnostic, not a setting. The phone reboots inside the first RunL, a few
// hundred imports after the frame loop starts, and the emulator does not, so
// the question is whether the drawing is what does it. With this at 0 the game
// runs exactly as before -- the direct screen access still starts, the
// clipping region is still set, the state machine is untouched -- and only
// BitBlt does nothing. If it still goes down, the drawing is not the cause.
enum { DRAW_THE_FRAME = 1, OLD_GC_BITBLT = 46 };

// The other half of the drawing, and the half the last experiment left alone.
// Turning the blit off proved nothing about the screen itself, because direct
// screen access still started and the game still told bitgdi to stop updating
// the display on its own and wait to be asked -- which is the one call in all
// of this that changes what the display driver is doing. With this at 0 that
// call and the Update that answers it both do nothing, and the driver is left
// as the system had it.
enum { TAKE_THE_SCREEN = 1 };
enum { IMPORT_SET_AUTO_UPDATE = 45, IMPORT_SCREEN_UPDATE = 47 };

extern "C" void gate6_dsa_startl(void *, u32, Context *c)
{
    typedef void (*StartL)(void *);
    ((StartL)c->newDsaStartL)(c->dsaReal);
    dsa_refresh(c);
}

// RDebug::WriteMemory(TThreadId, TUint32 aAddress, const TDesC8 &aData, TInt).
// The thread id goes in one register, not two -- the game called this with the
// address in r1 -- so the descriptor is r2, and the last argument is one the
// game does not need, which leaves r3 for the context.
extern "C" void gate6_write_memory(u32, u8 *address, const u32 *data, Context *c)
{
    const u32 length = data[0] & 0x0FFFFFFF;
    const u32 type = data[0] >> KTypeShift;
    // The four layouts of a descriptor: EBufC is the text straight after the
    // length word, EPtrC a pointer to it, and EBuf and EPtr the same two again
    // with a maximum length in between.
    const u8 *text = (type == EBufC)    ? (const u8 *)(data + 1)
                   : (type == EPtrC)    ? (const u8 *)data[1]
                   : (type == EBufType) ? (const u8 *)(data + 2)
                                        : (const u8 *)data[2];
    for (u32 i = 0; i < length; i++)
        address[i] = text[i];

    // What the game is writing is code, and on EKA1 it went in through the
    // kernel, which flushed the caches on the way. A copy in user space does
    // not: the stores sit in the data cache and the instruction cache still
    // holds what was there before, so the processor runs the old bytes. An
    // emulator has no such thing and never notices -- a phone faults the
    // moment it calls in, which is what KERN-EXEC 3 at the head of the
    // decrypted function was.
    user_imb_range(address, address + length);

    // Every region the game decrypts, so that code which reads as rubbish in
    // the file can be found and read as what it becomes.
    note(c, (u32)address >> 16, 'W');
    note(c, (u32)address & 0xFFFF, 'w');
    note(c, length, 'n');
}

// The game names the library in a descriptor; the second letter is enough to
// tell euser.dll from efsrv.dll, and anything else gets no table at all.
extern "C" int gate6_library_load(void *self, const u32 *name, const u32 *path,
                                  Context *c)
{
    typedef int (*Load)(void *, const u32 *, const u32 *);
    const int err = ((Load)c->newLibraryLoad)(self, name, path);
    if (err)
        return err;

    const u32 type = name[0] >> KTypeShift;
    const u16 *text = (type == EBufC)    ? (const u16 *)(name + 1)
                    : (type == EPtrC)    ? (const u16 *)name[1]
                    : (type == EBufType) ? (const u16 *)(name + 2)
                                         : (const u16 *)name[2];
    const u32 length = name[0] & 0x0FFFFFFF;
    // The game keeps both open at once, so each is remembered in its own slot.
    const u32 kind = (length < 2) ? LIB_OTHER
                   : (text[1] == 'u' || text[1] == 'U') ? LIB_EUSER
                   : (text[1] == 'f' || text[1] == 'F') ? LIB_EFSRV
                                                        : LIB_OTHER;
    if (kind != LIB_OTHER)
        c->dynLib[kind] = self;
    return err;
}

extern "C" u32 gate6_library_lookup(void *lib, int ordinal, Context *c)
{
    note(c, (u32)ordinal, 'L');
    const u32 kind = (lib == c->dynLib[LIB_EUSER]) ? LIB_EUSER
                   : (lib == c->dynLib[LIB_EFSRV]) ? LIB_EFSRV : LIB_OTHER;
    u32 mapped = 0;
    if (kind == LIB_EUSER) {
        switch (ordinal) {
        case OLD_RDEBUG_OPEN:        return c->noopFn;   // a channel of nothing
        case OLD_RTHREAD_ID:         return c->idFn;     // always the same id
        case OLD_RDEBUG_WRITEMEMORY: return c->writeFn;
        case OLD_CHUNK_CREATELOCALCODE: mapped = NEW_CHUNK_CREATELOCALCODE; break;
        default:
            if (ordinal >= 1 && (u32)ordinal <= kShimEuserCount)
                mapped = kShimEuser[ordinal - 1];
            break;
        }
    } else if (kind == LIB_EFSRV) {
        // 9.x stopped exporting RFsBase::Close from efsrv; it is the one it
        // inherits, and euser still exports that.
        if (ordinal == OLD_RFSBASE_CLOSE)
            return (u32)&rhandle_close;
        if (ordinal >= 1 && (u32)ordinal <= kShimEfsrvCount)
            mapped = kShimEfsrv[ordinal - 1];
    }
    // Never null: the game calls what it is given without looking at it.
    const u32 fn = mapped
        ? ((u32 (*)(void *, int))c->newLibraryLookup)(lib, (int)mapped) : 0;
    if (!fn)
        note(c, (u32)ordinal, 'X');
    return fn ? fn : c->noopFn;
}

// Cancel is called on the game's timer -- which is really ours -- and on the
// direct screen access object, which is really four bytes back.
extern "C" void gate6_cancel(u32 *self, Context *c)
{
    typedef void (*Cancel)(void *);
    if (c->oldTimer && c->wrapTimer && self == c->oldTimer)
        self = c->wrapTimer;
    else if (c->dsaShadow && self == c->dsaShadow)
        self = c->dsaReal;
    ((Cancel)c->newCancel)(self);
}

// ---- the control -----------------------------------------------------------

// The game asks its application where it lives and takes the drive and path
// from the answer, which is how it finds its own data files. Ours is a 9.x
// CEikApplication built from nothing and has no name to give, so the answer is
// the path the loader actually opened.
//
// TFileName is a TBuf<256>: a length word whose top four bits are the
// descriptor type, a maximum length, then the text -- 0x208 bytes, which is
// what the game reserves for it. Too big to return in registers, so r0 is the
// buffer to fill and the function hands it back.
enum { EBuf = 3 };

extern "C" void *gate6_dll_name(u32 *out, void *, Context *c)
{
    out[0] = ((u32)EBuf << KTypeShift) | (u32)c->pathLen;
    out[1] = 256;
    u16 *text = (u16 *)(out + 2);
    for (int i = 0; i < c->pathLen; i++)
        text[i] = c->path[i];
    return out;
}

// The game must never see the environment as it really is. It asks for it by
// name as well as reading it out of its control -- CCoeEnv::Static() then
// [env+0x18] is how it finds the app UI -- so the shifted view is what
// CCoeEnv::Static() returns too.
extern "C" void *gate6_coeenv_static(u32, u32, Context *c)
{
    c->coeEnv = (u32 *)coeenv_static();
    const u32 *real = (const u32 *)((u8 *)c->coeEnv + COEENV_BIAS);
    for (int i = 0; i < COEENV_VIEW_WORDS; i++)
        c->coeEnvView[i] = real[i];
    if (c->oldUi)
        c->coeEnvView[OLD_COEENV_APPUI / 4] = (u32)c->oldUi;
    return c->coeEnvView;
}

// The game's own control, constructed the way its own code expects. What the
// 9.x constructor would write is not merely different, it is at the wrong
// offsets, so this writes the old layout instead. A GCC98r2 constructor returns
// the object.
extern "C" void *gate6_coecontrol_ctor(u32 *self, u32, Context *c)
{
    for (int i = 0; i < OLD_CONTROL_BYTES / 4; i++)
        self[i] = 0;
    self[OLD_CONTROL_COEENV / 4] = (u32)gate6_coeenv_static(0, 0, c);
    return self;
}

extern "C" void gate6_control_draw(void *, u32 rect, Context *c)
{
    old_call1(c->oldControl, OLD_CTL_DRAW, rect);
}

extern "C" void gate6_control_focus(void *, u32 drawNow, Context *c)
{
    old_call1(c->oldControl, OLD_CTL_FOCUS, drawNow);
}

// A window belongs to a 9.x control, so build one and lend the game its window:
// old Window() is one instruction, a load from offset 0x20, so putting the
// window there is all it takes for the game to find it.
extern "C" void gate6_create_window(u32 *oldControl, int, Context *c)
{
    u32 *ctl = (u32 *)user_allocz(WRAP_BYTES);
    if (!ctl) PANIC(CAT_MEM, -33);
    c->oldControl = oldControl;
    coecontrol_ctor(ctl);
    {
        u32 *cvt = copy_vtable(vtable_of(ctl), CONTROL_SLOTS);
        cvt[VT_HEADER + NEW_CTL_DRAW] = ctx_thunk(c->spare, c, (u32)&gate6_control_draw);
        c->spare += TRACE;
        cvt[VT_HEADER + NEW_CTL_FOCUS] = ctx_thunk(c->spare, c, (u32)&gate6_control_focus);
        c->spare += TRACE;
        instrument(c, cvt, CONTROL_SLOTS, OBJ_CONTROL);
        ctl[0] = (u32)(cvt + VT_HEADER);
    }
    coecontrol_createwindowl(ctl);
    oldControl[OLD_CONTROL_WIN / 4] = ctl[NEW_CONTROL_WIN / 4];
    c->wrapControl = ctl;
}

extern "C" void gate6_baseconstructl(void *, int flags, Context *c)
{
    // Now that the wrapper is a CAknAppUi, avkon's own base construction is
    // the right one, and the flags the game asked for are worth honouring --
    // it passes zero, a standard application with all its furniture.
    // The flags the game asks for -- zero, a standard application with all its
    // furniture. Asking avkon for less than that is worse, not safer: with
    // ENoAppResourceFile it goes off the rails entirely, while with the game's
    // own flags it gets as far as looking for status pane and menu resources
    // and says so, which is a resource file to write rather than a mystery.
    typedef void (*BaseConstructL)(void *, int);
    if (c->newBaseConstructL)
        ((BaseConstructL)c->newBaseConstructL)(c->wrapUi, flags);
    else
        eikappui_baseconstructl(c->wrapUi, ENoAppResourceFile | ENoScreenFurniture);
}

extern "C" void gate6_ui_construct(void *self)
{
    box_start(context_of(self));
    // From here the game's own ConstructL drives, and whatever it reaches that
    // the shim cannot answer panics with that import's index.
    context_of(self)->wrapUi = (u32 *)self;
    old_call((const u32 *)((const u32 *)self)[WRAP_OLD], OLD_UI_CONSTRUCT);

    // Confirmed on hardware: this runs to the end there too, so the fault is
    // past here and the framework takes the application on from here.
}

extern "C" void *gate6_create_app_ui(void *self)
{
    const u32 *oldDoc = (const u32 *)((const u32 *)self)[WRAP_OLD];
    u32 oldUi = old_call(oldDoc, OLD_CREATE_APP_UI);
    if (!oldUi) PANIC(CAT_NUL, 3);

    Context *c = context_of(self);
    c->oldUi = (u32 *)oldUi;

    u32 *ui = (u32 *)user_allocz(WRAP_BYTES);
    if (!ui) PANIC(CAT_MEM, -31);
    coeappui_ctor(ui);          // assigns iCoeEnv, which BaseConstructL reads
    eikappui_ctor(ui);

    // Then the part of CAknAppUi that can be constructed, and its vtable.
    typedef void (*Ctor)(void *);
    Ctor base = (Ctor)rlibrary_lookup(&c->avkon, AKN_APPUI_BASE_CTOR);
    const u32 *akn = (const u32 *)rlibrary_lookup(&c->avkon, AKN_APPUI_VTABLE);
    if (!base || !akn) PANIC(CAT_LIB, -1);
    // A vtable, not something else at that ordinal: no offset to a containing
    // object, and every slot filled.
    if (akn[0] != 0) PANIC(CAT_LIB, -2);
    for (int i = 0; i < AKN_APPUI_SLOTS; i++)
        if (!akn[VT_HEADER + i]) PANIC(CAT_LIB, -(3 + i));
    base(ui);

    ui[WRAP_OLD] = oldUi;
    ui[WRAP_CTX] = ((const u32 *)self)[WRAP_CTX];

    u32 *vt = copy_vtable(akn, AKN_APPUI_SLOTS);
    vt[VT_HEADER + SLOT_UI_CONSTRUCT] = (u32)&gate6_ui_construct;
    instrument(c, vt, AKN_APPUI_SLOTS, OBJ_UI);
    ui[0] = (u32)(vt + VT_HEADER);
    return ui;
}

// ---- the document ----------------------------------------------------------

extern "C" void *gate6_create_document(void *self)
{
    const u32 *oldApp = (const u32 *)((const u32 *)self)[WRAP_OLD];
    u32 oldDoc = old_call(oldApp, OLD_CREATE_DOCUMENT);
    if (!oldDoc) PANIC(CAT_NUL, 2);

    u32 *doc = (u32 *)user_allocz(WRAP_BYTES);
    if (!doc) PANIC(CAT_MEM, -32);
    akndocument_ctor(doc, self);        // the 9.x document points at the 9.x app
    doc[WRAP_OLD] = oldDoc;
    doc[WRAP_CTX] = ((const u32 *)self)[WRAP_CTX];

    u32 *vt = copy_vtable(vtable_of(doc), DOC_SLOTS);
    vt[VT_HEADER + SLOT_CREATE_APP_UI] = (u32)&gate6_create_app_ui;
    instrument(context_of(self), vt, DOC_SLOTS, OBJ_DOC);
    doc[0] = (u32)(vt + VT_HEADER);
    return doc;
}

// ---- the application -------------------------------------------------------

// The game's own AppDllUid answers with the N-Gage UID, and bridging it is what
// the first run of this did: the framework then looked the application up by
// that UID, found no registration for it and left with KErrNotFound before the
// document was ever asked for. The UID is the framework's name for *us*, so it
// stays ours -- the same one the registration resource carries.
extern "C" u32 gate6_app_dll_uid(void *)
{
    return 0xE0001006;          // TUid is one word, returned in r0
}

static u32 load_and_start(void);   // -> the wrapper the framework gets

extern "C" void *gate6_new_application()
{
    return (void *)load_and_start();
}

extern "C" u32 gate6_main()
{
    // Before anything can leave. The object has to outlive the thread's work,
    // so it goes on the heap rather than this frame; the constructor writes
    // only its own fields, so the room is generous on purpose.
    void *globals = user_allocz(512);
    if (!globals) PANIC(CAT_MEM, -40);
    cpprt_globals_ctor(globals);

    eikstart_runapplication(0, (u32)&gate6_new_application, 0, 0);
    PANIC(CAT_RET, 0);
    return 0;
}

static u32 load_and_start()
{
    u32 fs[2] = { 0, 0 };
    u32 file[4] = { 0, 0, 0, 0 };
    i32 err = fs_connect(fs, -1);
    if (err) PANIC(CAT_FS, err);

    // Where the game came from is not only how it is read: it is the answer to
    // CApaApplication::DllName(), and the game builds the names of its own
    // files beside it -- 6rbc.cwa among them, which lives where an N-Gage card
    // puts it. So the card's own layout is tried first, and the loose copies
    // only after.
    const u16 *paths[3] = { kPath2, kPath0, kPath1 };
    const int lens[3] = { sizeof kPath2 / 2, sizeof kPath0 / 2, sizeof kPath1 / 2 };
    // The game opens eight files of its own beside wherever it was loaded
    // from -- 6rbc.cwa, 6RBC.dat, cis.dat, cwivenc.dat and the rest -- and a
    // missing one is not an error it survives. So a candidate only counts if
    // its directory holds 6rbc.cwa too, and only if none of them does is the
    // first readable .app taken anyway, so the failure is the game's own.
    u16 sibling[32];
    err = -1;
    int chosen = -1;
    int fallback = -1;
    for (int pass = 0; pass < 2 && chosen < 0; pass++) {
        for (int i = 0; i < 3; i++) {
            Ptrc16 name;
            name.lengthAndType = ((u32)EPtrC << KTypeShift) | (u32)lens[i];
            name.text = paths[i];
            if (pass == 0) {
                // The same path with "app" turned into "cwa".
                if (lens[i] > 32) continue;
                for (int k = 0; k < lens[i]; k++) sibling[k] = paths[i][k];
                sibling[lens[i] - 3] = 'c';
                sibling[lens[i] - 2] = 'w';
                sibling[lens[i] - 1] = 'a';
                Ptrc16 with;
                with.lengthAndType = ((u32)EPtrC << KTypeShift) | (u32)lens[i];
                with.text = sibling;
                u32 probe[4] = { 0, 0, 0, 0 };
                if (file_open(probe, fs, &with, 1) != 0) continue;
                rhandle_close(probe);
            }
            err = file_open(file, fs, &name, 1);   // EFileRead | EFileShareReadersOnly
            if (!err) { chosen = i; break; }
            if (fallback < 0) fallback = i;
        }
    }
    if (chosen < 0) {
        if (fallback < 0) PANIC(CAT_FS, err);
        chosen = fallback;
        Ptrc16 name;
        name.lengthAndType = ((u32)EPtrC << KTypeShift) | (u32)lens[chosen];
        name.text = paths[chosen];
        err = file_open(file, fs, &name, 1);
        if (err) PANIC(CAT_FS, err);
    }

    int size = 0;
    err = file_size(file, &size);
    if (err) PANIC(CAT_FS, err);

    u8 *raw = (u8 *)user_alloc(size);
    if (!raw) PANIC(CAT_MEM, size);

    // RFile::Read stops at the descriptor's maximum, so loop until it is full.
    int got = 0;
    while (got < size) {
        Ptr8 des;
        des.lengthAndType = (u32)EPtr << KTypeShift;
        des.maxLength = size - got;
        des.ptr = raw + got;
        err = file_read(file, &des);
        if (err) PANIC(CAT_FS, err);
        int n = (int)(des.lengthAndType & 0x0FFFFFFF);
        if (n <= 0) break;
        got += n;
    }
    if (got != size) PANIC(CAT_FS, got);

    const E32 *h = (const E32 *)raw;
    if (h->sig != 0x434F5045) PANIC(CAT_HDR, 1);            // 'EPOC'
    if (h->uid1 != 0x10000079) PANIC(CAT_HDR, 2);           // a polymorphic DLL
    if (h->cpu != 0x2000 && h->cpu != 0x1000) PANIC(CAT_HDR, 3);  // must be EKA1
    if (h->compression) PANIC(CAT_HDR, 4);
    if (h->textSize > h->codeSize) PANIC(CAT_HDR, 5);

    const u32 nImports = (h->codeSize - h->textSize) / 4;
    const u32 stubBytes = nImports * SLOT;
    const u32 traceBytes = nImports * TRACE + 240 * TRACE;  // spares for our own thunks
    const u32 chunkSize = h->codeSize + stubBytes + traceBytes;

    u32 chunk[2] = { 0, 0 };
    err = chunk_createlocalcode(chunk, (int)chunkSize, (int)chunkSize, 0);
    if (err) PANIC(CAT_MEM, err);
    u8 *base = chunk_base(chunk);
    if (!base) PANIC(CAT_MEM, 0x0BADBA5E);

    for (u32 i = 0; i < h->codeSize; i++)
        base[i] = raw[h->codeOffset + i];

    // Rebase. Type 3 is KInferredRelocType and this image has no data section,
    // so every relocation lands in the code we just copied.
    const u32 delta = (u32)base - h->codeBase;
    u32 relocated = 0;
    if (h->codeRelocOffset) {
        const u8 *sec = raw + h->codeRelocOffset;
        const u32 secSize = *(const u32 *)sec;
        u32 o = 8;
        while (o < secSize + 8) {
            const u32 pageBase = *(const u32 *)(sec + o);
            const u32 blockSize = *(const u32 *)(sec + o + 4);
            if (blockSize < 8 || (blockSize & 1)) break;
            for (u32 k = 0; k < (blockSize - 8) / 2; k++) {
                const u16 e = *(const u16 *)(sec + o + 8 + 2 * k);
                if (!e) continue;
                const u32 at = pageBase + (e & 0x0FFF);
                if (at + 4 > h->codeSize) PANIC(CAT_HDR, 6);
                *(u32 *)(base + at) += delta;
                relocated++;
            }
            o += blockSize;
        }
    }
    if (!relocated) PANIC(CAT_HDR, 7);


    // Load the 9.x libraries the forwarding table names. Resolving at run time
    // rather than through our own import section means an ordinal this phone
    // does not have is a null we can count, not a refusal to start at all.
    u32 libs[24];
    if (kShimDllCount > 24) PANIC(CAT_SHIM, (int)kShimDllCount);
    Ptrc16 nopath;
    nopath.lengthAndType = (u32)EPtrC << KTypeShift;
    nopath.text = 0;
    for (u32 i = 0; i < kShimDllCount; i++) {
        libs[i] = 0;
        Ptrc16 nm;
        nm.lengthAndType = ((u32)EPtrC << KTypeShift) | (u32)kShimDllLen[i];
        nm.text = kShimDllName[i];
        err = rlibrary_load(&libs[i], &nm, &nopath);
        if (err) PANIC(CAT_LIB, (int)(i * 1000) + err);
    }

    // Build one stub per import and write its address into the import address
    // table, which on EKA1 sits at the end of the code section.
    //   ldr r0, [pc, #0]   -> the report code
    //   ldr pc, [pc, #0]   -> gate6_report
    u32 *iat = (u32 *)(base + h->textSize);
    u8 *stub = base + h->codeSize;
    u8 *trace = stub + stubBytes;
    u32 forwarded = 0, missing = 0;

    Context *ctx = (Context *)user_allocz((int)sizeof(Context));
    if (!ctx) PANIC(CAT_MEM, -23);
    ctx->path = paths[chosen];
    ctx->pathLen = lens[chosen];
    ctx->pathIndex = (u32)chosen;
    ctx->codeBase = (u32)base;
    ctx->lastImport = 0xFFFF;               // nothing yet
    ctx->spare = trace + nImports * TRACE + 16 * TRACE;  // past the fixed thunks
    ctx->spareEnd = trace + traceBytes;

    ctx->cppRuntime = (u32)&drtaeabi_pure_virtual;

    {
        u32 *noop = (u32 *)(trace + nImports * TRACE + 10 * TRACE);
        noop[0] = 0xE3A00000;           // mov r0, #0
        noop[1] = 0xE12FFF1E;           // bx  lr
        user_imb_range(noop, noop + 2);
        ctx->noopFn = (u32)noop;
    }

    // Read what the last run got to, if it left anything this build wrote, and
    // say so. The file is armed again by replacing it rather than deleting it,
    // so that a delete the file server refuses cannot leave a stale record to
    // be reported over and over.
    {
        Ptrc16 name;
        box_name(&name);
        u32 magic = 0, last = BOX_NONE, reached = 0, count = 0;
        if (fs_connect(ctx->boxFs, -1) == 0) {
            if (file_open(ctx->boxFile, ctx->boxFs, &name, 1) == 0) {
                Ptr8 des;
                des.lengthAndType = (u32)EPtr << KTypeShift;
                des.maxLength = BOX_BYTES;
                des.ptr = (u8 *)ctx->boxData;
                for (int i = 0; i < BOX_WORDS; i++) ctx->boxData[i] = 0;
                file_read(ctx->boxFile, &des);
                rhandle_close(ctx->boxFile);
                magic = ctx->boxData[0];
                last = ctx->boxData[1];
                reached = ctx->boxData[2];
                count = ctx->boxData[3];
                box_report(ctx, count);
            }
            if (file_replace(ctx->boxFile, ctx->boxFs, &name, EFileWrite | EFileShareAny) == 0) {
                ctx->lastImport = BOX_ARMED;    // armed, nothing recorded yet
                box_flush(ctx);
                ctx->lastImport = 0xFFFF;
            }
            // One number, three fields. How many imports the game got through
            // says at a glance whether it is running or stopped: a few hundred
            // is a startup that gave up, thousands is a frame loop. Then which
            // import it was on -- three digits, and 999 means the file was
            // armed and nothing was ever written to it -- and last a digit for
            // what happened: 1 the frame loop ran, 2 it left, 4 it exited.
            if (magic == BOX_MAGIC) {
                const u32 fate = ((reached & REACHED_RUNL) ? 1u : 0u)
                               | ((reached & REACHED_LEAVE) ? 2u : 0u)
                               | ((reached & REACHED_EXIT) ? 4u : 0u);
                const u32 steps = count > 99999 ? 99999 : count;
                PANIC(CAT_BOX, (int)(steps * 10000 +
                                     (last == BOX_ARMED ? 999 : (last % 1000)) * 10 +
                                     fate));
            }
        }
    }

    // The handler takes a TExcType in r0 and has nowhere to keep the context,
    // so it arrives through a thunk of its own.
    {
        u32 *b = (u32 *)(trace + nImports * TRACE);
        b[0] = 0xE1A01000;                  // mov r1, r0   -- the exception type
        b[1] = 0xE59F0000;                  // ldr r0, [pc, #0]
        b[2] = 0xE59FF000;                  // ldr pc, [pc, #0]
        b[3] = (u32)ctx;
        b[4] = (u32)&gate6_fault;
        user_setexceptionhandler(b, 0xFFFFFFFF);

    }
    for (u32 i = 0; i < nImports; i++) {
        u32 *s = (u32 *)(stub + SLOT * i);
        s[0] = 0xE59F0000;                  // ldr r0, [pc, #0]  -> the report code
        s[1] = 0xE59FF000;                  // ldr pc, [pc, #0]  -> gate6_report
        s[2] = nImports * 1000 + i;
        s[3] = (u32)&gate6_report;
        iat[i] = (u32)s;

        const u32 entry = (i < kShimCount) ? kShimTable[i] : 0;
        const u32 kind = entry >> 24;
        if (!kind)
            continue;

        if (kind == KIND_LOCAL) {
            switch (entry & 0xFFFF) {
            case LOCAL_NEGSF2:
                s[0] = 0xE2200102;          // eor r0, r0, #0x80000000
                s[1] = 0xE12FFF1E;          // bx  lr
                break;
            case LOCAL_NOOP:                // an empty body: _Reserved slots, CBase
                s[0] = 0xE3A00000;          // mov r0, #0
                s[1] = 0xE12FFF1E;          // bx  lr
                break;
            case LOCAL_SELF:                // a constructor with nothing to do
                s[0] = 0xE12FFF1E;          // bx  lr     -- r0 is still the object
                break;
            case LOCAL_TRUE:                // a predicate that is always yes
                s[0] = 0xE3A00001;          // mov r0, #1
                s[1] = 0xE12FFF1E;          // bx  lr
                break;
            case LOCAL_TRAP_ENTER:          // TTrap::Trap(TInt&): first pass, no error
                s[0] = 0xE3A00000;          // mov r0, #0
                s[1] = 0xE5810000;          // str r0, [r1]
                s[2] = 0xE12FFF1E;          // bx  lr
                break;
            case LOCAL_TINT64_SET:          // TInt64 from a TInt: sign-extend
                s[0] = 0xE5801000;          // str r1, [r0]
                s[1] = 0xE1A02FC1;          // mov r2, r1, asr #31
                s[2] = 0xE5802004;          // str r2, [r0, #4]
                s[3] = 0xE12FFF1E;          // bx  lr     -- r0 is still the object
                break;
            case LOCAL_MEM_COMPARE:
                s[0] = 0xE51FF004;          // ldr pc, [pc, #-4]
                s[1] = (u32)&gate6_mem_compare;
                break;
            default:
                s[0] = 0xE51FF004;
                s[1] = (u32)&gate6_pure_virtual;
                break;
            }
            forwarded++;
            continue;
        }

        void *fn = rlibrary_lookup(&libs[(entry >> 16) & 0xFF], (int)(entry & 0xFFFF));
        if (!fn) {
            missing++;                      // the stub stays, so we hear about it
            continue;
        }
        if (kind == KIND_CALL) {
            iat[i] = (u32)fn;
        } else if (kind == KIND_SRET8) {
            // GCC98r2 returned an eight-byte structure in r0 and r1; EABI wants
            // a buffer in r0 and pushes `this` to r1. Borrow eight bytes of
            // stack, let the callee fill them, and hand them back in registers.
            s[0] = 0xE92D4010;              // push  {r4, lr}
            s[1] = 0xE24DD008;              // sub   sp, sp, #8
            s[2] = 0xE1A01000;              // mov   r1, r0      -- `this`
            s[3] = 0xE1A0000D;              // mov   r0, sp      -- the buffer
            s[4] = 0xE59F4008;              // ldr   r4, [pc, #8]
            s[5] = 0xE12FFF34;              // blx   r4
            s[6] = 0xE8BD0003;              // ldmia sp!, {r0, r1}
            s[7] = 0xE8BD8010;              // pop   {r4, pc}
            s[8] = (u32)fn;
        } else if (kind == KIND_ARGSHIFT) {
            // A member function 9.x made free: drop `this` and move the rest
            // down a register.
            s[0] = 0xE1A00001;              // mov r0, r1
            s[1] = 0xE1A01002;              // mov r1, r2
            s[2] = 0xE1A02003;              // mov r2, r3
            s[3] = 0xE51FF004;              // ldr pc, [pc, #-4]
            s[4] = (u32)fn;
        } else if (kind == KIND_ARG3) {
            s[0] = 0xE3A02000;              // mov r2, #0    -- the added argument
            s[1] = 0xE51FF004;              // ldr pc, [pc, #-4]
            s[2] = (u32)fn;
        } else {
            s[0] = 0xE92D4000;              // push {lr}
            s[1] = 0xE59FC008;              // ldr  r12, [pc, #8]
            s[2] = 0xE12FFF3C;              // blx  r12
            s[3] = 0xE1A00001;              // mov  r0, r1   -- the remainder
            s[4] = 0xE8BD8000;              // pop  {pc}
            s[5] = (u32)fn;
        }
        forwarded++;
    }
    if (!forwarded) PANIC(CAT_SHIM, (int)missing);

    // Keep avkon's handle: the app UI needs two things out of it that no
    // header will give us, and the shim's list is a local of this function.
    for (u32 i = 0; i < kShimDllCount; i++) {
        const u16 *nm = kShimDllName[i];
        if (kShimDllLen[i] >= 5 && nm[0] == 'a' && nm[1] == 'v' && nm[2] == 'k' &&
            nm[3] == 'o' && nm[4] == 'n') {
            ctx->avkon = libs[i];
            break;
        }
    }
    if (!ctx->avkon) PANIC(CAT_LIB, -100);

    // The stub slot of a resolved import is spare -- its address went straight
    // into the table -- so the diversions are built there.
    if (nImports <= IMPORT_BASECONSTRUCTL) PANIC(CAT_SHIM, (int)nImports);
    ctx->newBaseConstructL = iat[IMPORT_BASECONSTRUCTL];
    iat[IMPORT_BASECONSTRUCTL] = ctx_thunk(stub + SLOT * IMPORT_BASECONSTRUCTL,
                                           ctx, (u32)&gate6_baseconstructl);

    if (nImports > IMPORT_CREATEWINDOWL)
        iat[IMPORT_CREATEWINDOWL] = ctx_thunk(stub + SLOT * IMPORT_CREATEWINDOWL,
                                              ctx, (u32)&gate6_create_window);
    if (nImports > IMPORT_DLL_NAME)
        iat[IMPORT_DLL_NAME] = ctx_thunk(stub + SLOT * IMPORT_DLL_NAME,
                                         ctx, (u32)&gate6_dll_name);
    if (nImports > IMPORT_COEENV_STATIC)
        iat[IMPORT_COEENV_STATIC] = ctx_thunk(stub + SLOT * IMPORT_COEENV_STATIC,
                                              ctx, (u32)&gate6_coeenv_static);
    if (nImports > IMPORT_COECONTROL_CTOR)
        iat[IMPORT_COECONTROL_CTOR] = ctx_thunk(stub + SLOT * IMPORT_COECONTROL_CTOR,
                                                ctx, (u32)&gate6_coecontrol_ctor);
    if (nImports > IMPORT_WINDOW) {
        u32 *w = (u32 *)(stub + SLOT * IMPORT_WINDOW);
        w[0] = 0xE5900000 | OLD_CONTROL_WIN;    // ldr r0, [r0, #0x20]  -- iWin
        w[1] = 0xE12FFF1E;                      // bx  lr
        iat[IMPORT_WINDOW] = (u32)w;
    }
    if (nImports > IMPORT_ADDTOSTACKL && IMPORT_ADDTOSTACKL < kShimCount &&
        (kShimTable[IMPORT_ADDTOSTACKL] >> 24) == KIND_CALL)
        iat[IMPORT_ADDTOSTACKL] = pair_thunk(stub + SLOT * IMPORT_ADDTOSTACKL,
                                             &ctx->wrapUi, &ctx->wrapControl,
                                             iat[IMPORT_ADDTOSTACKL]);

    for (u32 k = 0; k < sizeof kDiverts / sizeof kDiverts[0]; k++) {
        const u32 j = kDiverts[k].import;
        // An import the shim could not answer keeps its reporting stub: sending
        // it through a diversion would lose the one thing it can still tell us.
        if (j >= nImports || j >= kShimCount || (kShimTable[j] >> 24) != KIND_CALL)
            continue;
        u32 **cell = &ctx->wrapUi;
        if (kDiverts[k].object == ON_CONTROL) cell = &ctx->wrapControl;
        else if (kDiverts[k].object == ON_TIMER) cell = &ctx->wrapTimer;
        else if (kDiverts[k].object == ON_GC) cell = &ctx->realGc;
        iat[j] = this_thunk(stub + SLOT * j, cell, iat[j], kDiverts[k].arg);
    }

    if (nImports > IMPORT_ADD_FOREGROUND_OBSERVER &&
        IMPORT_ADD_FOREGROUND_OBSERVER < kShimCount &&
        (kShimTable[IMPORT_ADD_FOREGROUND_OBSERVER] >> 24) == KIND_CALL) {
        u8 *spare = trace + nImports * TRACE;
        u32 *vt = (u32 *)user_allocz(FOREGROUND_SLOTS * 4);
        u32 *obs = (u32 *)user_allocz(4);
        if (!vt || !obs) PANIC(CAT_MEM, -36);
        vt[0] = ctx_thunk(spare + 13 * TRACE, ctx, (u32)&gate6_foreground_gaining);
        vt[1] = ctx_thunk(spare + 14 * TRACE, ctx, (u32)&gate6_foreground_losing);
        obs[0] = (u32)vt;
        iat[IMPORT_ADD_FOREGROUND_OBSERVER] =
            fg_thunk(spare + 15 * TRACE, &ctx->oldForeground, &ctx->coeEnv, obs,
                     iat[IMPORT_ADD_FOREGROUND_OBSERVER]);
    }

    // The window server's view of the game's observer.
    if (nImports > IMPORT_DSA_NEWL && IMPORT_DSA_NEWL < kShimCount &&
        (kShimTable[IMPORT_DSA_NEWL] >> 24) == KIND_CALL) {
        u8 *spare = trace + nImports * TRACE;
        u32 *vt = (u32 *)user_allocz(DSA_SLOTS * 4);
        u32 *obs = (u32 *)user_allocz(4);
        if (!vt || !obs) PANIC(CAT_MEM, -34);
        vt[0] = ctx_thunk(spare + TRACE, ctx, (u32)&gate6_dsa_slot0);
        vt[1] = ctx_thunk(spare + 2 * TRACE, ctx, (u32)&gate6_dsa_slot1);
        obs[0] = (u32)vt;               // 9.x: the vptr points at slot 0
        // The old-layout view of the object, and the old-vtable view of the
        // graphics context inside it.
        ctx->dsaShadow = (u32 *)user_allocz(OLD_DSA_BYTES);
        u32 *gcVt = (u32 *)user_allocz((2 + OLD_GC_SLOTS) * 4);
        ctx->fakeGc = (u32 *)user_allocz(4);
        if (!ctx->dsaShadow || !gcVt || !ctx->fakeGc) PANIC(CAT_MEM, -37);
        u8 *gcRoom = ctx->spare;
        if (gcRoom + OLD_GC_SLOTS * GC_THUNK_BYTES > ctx->spareEnd)
            PANIC(CAT_MEM, -38);
        for (u32 i = 0; i < OLD_GC_SLOTS; i++)
            gcVt[2 + i] = (kGcSlot[i] == GC_NONE)
                ? (u32)&gate6_pure_virtual
                : gc_thunk(gcRoom + i * GC_THUNK_BYTES, &ctx->realGc, kGcSlot[i]);
        if (!DRAW_THE_FRAME) {
            // Its thunk is already there and already pointed at; only what it
            // does changes.
            u32 *b = (u32 *)(gcRoom + OLD_GC_BITBLT * GC_THUNK_BYTES);
            b[0] = 0xE3A00000;          // mov r0, #0
            b[1] = 0xE12FFF1E;          // bx  lr
            user_imb_range(b, b + 2);
        }
        ctx->spare = gcRoom + OLD_GC_SLOTS * GC_THUNK_BYTES;
        // GCC98r2 keeps the two header words in the table and points at them.
        ctx->fakeGc[0] = (u32)gcVt;

        iat[IMPORT_DSA_NEWL] = dsa_thunk(spare + 8 * TRACE, &ctx->oldObserver, obs,
                                         iat[IMPORT_DSA_NEWL], &ctx->dsaReal,
                                         &ctx->dsaShadow);
        if (nImports > IMPORT_DSA_STARTL && IMPORT_DSA_STARTL < kShimCount &&
            (kShimTable[IMPORT_DSA_STARTL] >> 24) == KIND_CALL) {
            ctx->newDsaStartL = iat[IMPORT_DSA_STARTL];
            iat[IMPORT_DSA_STARTL] = ctx_thunk(stub + SLOT * IMPORT_DSA_STARTL,
                                               ctx, (u32)&gate6_dsa_startl);
        }
    }

    if (nImports > IMPORT_CANCEL && IMPORT_CANCEL < kShimCount &&
        (kShimTable[IMPORT_CANCEL] >> 24) == KIND_CALL) {
        ctx->newCancel = iat[IMPORT_CANCEL];
        iat[IMPORT_CANCEL] = ctx_thunk(stub + SLOT * IMPORT_CANCEL, ctx,
                                       (u32)&gate6_cancel);
    }

    if (nImports > IMPORT_LIBRARY_LOOKUP && IMPORT_LIBRARY_LOOKUP < kShimCount &&
        (kShimTable[IMPORT_LIBRARY_LOOKUP] >> 24) == KIND_CALL) {
        u32 *id = (u32 *)(trace + nImports * TRACE + 11 * TRACE);
        id[0] = 0xE3A00000;             // mov r0, #0
        id[1] = 0xE3A01000;             // mov r1, #0
        id[2] = 0xE12FFF1E;             // bx  lr
        ctx->idFn = (u32)id;
        ctx->writeFn = ctx3_thunk(trace + nImports * TRACE + 12 * TRACE, ctx,
                                  (u32)&gate6_write_memory);
        ctx->newLibraryLookup = iat[IMPORT_LIBRARY_LOOKUP];
        iat[IMPORT_LIBRARY_LOOKUP] = ctx_thunk(stub + SLOT * IMPORT_LIBRARY_LOOKUP,
                                               ctx, (u32)&gate6_library_lookup);
        if (nImports > IMPORT_LIBRARY_LOAD && IMPORT_LIBRARY_LOAD < kShimCount &&
            (kShimTable[IMPORT_LIBRARY_LOAD] >> 24) == KIND_CALL) {
            ctx->newLibraryLoad = iat[IMPORT_LIBRARY_LOAD];
            iat[IMPORT_LIBRARY_LOAD] = ctx3_thunk(stub + SLOT * IMPORT_LIBRARY_LOAD,
                                                  ctx, (u32)&gate6_library_load);
        }
    }

    if (nImports > IMPORT_REQUEST_COMPLETE && IMPORT_REQUEST_COMPLETE < kShimCount &&
        (kShimTable[IMPORT_REQUEST_COMPLETE] >> 24) == KIND_CALL) {
        ctx->newRequestComplete = iat[IMPORT_REQUEST_COMPLETE];
        iat[IMPORT_REQUEST_COMPLETE] =
            ctx_thunk(stub + SLOT * IMPORT_REQUEST_COMPLETE, ctx,
                      (u32)&gate6_request_complete);
    }

    // The scheduler's timer, and the game's.
    if (nImports > IMPORT_CTIMER_CTOR && IMPORT_CTIMER_CTOR < kShimCount &&
        (kShimTable[IMPORT_CTIMER_CTOR] >> 24) == KIND_CALL) {
        u8 *spare = trace + nImports * TRACE;
        ctx->newTimerCtor = iat[IMPORT_CTIMER_CTOR];
        ctx->timerThunks[0] = ctx_thunk(spare + 4 * TRACE, ctx, (u32)&gate6_timer_docancel);
        ctx->timerThunks[1] = ctx_thunk(spare + 5 * TRACE, ctx, (u32)&gate6_timer_runl);
        ctx->timerThunks[2] = ctx_thunk(spare + 6 * TRACE, ctx, (u32)&gate6_timer_runerror);
        iat[IMPORT_CTIMER_CTOR] = ctx_thunk(spare + 7 * TRACE, ctx, (u32)&gate6_ctimer_ctor);
    }

    if (!TAKE_THE_SCREEN) {
        if (nImports > IMPORT_SET_AUTO_UPDATE) iat[IMPORT_SET_AUTO_UPDATE] = ctx->noopFn;
        if (nImports > IMPORT_SCREEN_UPDATE) iat[IMPORT_SCREEN_UPDATE] = ctx->noopFn;
    }

    for (u32 i = 0; i < sizeof kCrumb / sizeof kCrumb[0]; i++)
        if (kCrumb[i] + 4 <= h->codeSize)
            crumb_plant(ctx, base, kCrumb[i], CRUMB_FIRST + i);

    // Last, so that it records every import however it ended up being answered.
    for (u32 i = 0; i < nImports; i++)
        iat[i] = trace_thunk(trace + TRACE * i, ctx, i, iat[i], (u32)&gate6_trace);

    // Everything above -- the image, the stubs, every thunk -- was written as
    // data and is about to be run as code, so the caches are put right over
    // the whole chunk before anything in it is entered.
    user_imb_range(base, base + chunkSize);

    // Enter it. EKA1 calls a DLL's entry point with EDllProcessAttach first,
    // then apparc asks ordinal 1 for the application object.
    typedef int (*EntryFn)(int);
    typedef void *(*Ordinal1Fn)(void);
    ((EntryFn)(base + h->entryPoint))(0);
    const u32 ord1 = *(const u32 *)(raw + h->exportDirOffset);
    void *app = ((Ordinal1Fn)(base + ord1))();
    if (!app) PANIC(CAT_NUL, (int)(forwarded * 1000 + missing));
    // The 9.x application: built the ordinary way, then told which old object
    // it stands for, with its two overridden slots pointed at the game.
    u32 *wrap = (u32 *)user_allocz(WRAP_BYTES);
    if (!wrap) PANIC(CAT_MEM, -20);
    eikapplication_ctor(wrap);
    wrap[WRAP_OLD] = (u32)app;
    wrap[WRAP_CTX] = (u32)ctx;

    u32 *vt = copy_vtable(vtable_of(wrap), APP_SLOTS);
    vt[VT_HEADER + SLOT_APP_DLL_UID] = (u32)&gate6_app_dll_uid;
    vt[VT_HEADER + SLOT_CREATE_DOCUMENT] = (u32)&gate6_create_document;
    instrument(ctx, vt, APP_SLOTS, OBJ_APP);
    wrap[0] = (u32)(vt + VT_HEADER);
    return (u32)wrap;

}
