#!/usr/bin/env python3
"""Generate the forwarding table gate 4 links against.

    gen_shim.py <image> <output.cpp>

For every import the old binary makes, shimtable finds the Symbian 9.x ordinal
of the same function.  This writes that out as data: a list of DLLs to load and
one word per import holding which DLL and which ordinal, or zero where nothing
matched.

The forwards are resolved at run time with RLibrary::Lookup rather than through
our own import section, for two reasons.  An import section is checked when the
image loads, so one ordinal that does not exist on the device would stop the
whole program from starting, with no way to say which; a lookup that returns
null can be reported.  And the ordinals come from the Symbian source, which is
a later 9.x than any one phone, so some of them will be wrong.
"""
import os, re, sys

import e32imports, shimtable, symdef

ROOT = '/home/user/symbiansource'
KERNEL = ROOT + '/oss.fcl.sf.os.kernelhwsrv'
EPOC6 = '/home/user/EKA2L1/src/emu/bridge/include/bridge/epoc6.def'


def find_defs():
    out = {}
    for dirpath, _dirs, files in os.walk(ROOT):
        if 'eabi' not in dirpath.lower():
            continue
        for f in files:
            if not f.lower().endswith('.def'):
                continue
            b = symdef.base_name(f)
            for key in {b, b.rstrip('u'), re.sub(r'\d+u?$', '', b)}:
                out.setdefault(key, os.path.join(dirpath, f))
    return out


def build(image):
    d = open(image, 'rb').read()
    imports = [(n.split('[')[0].split('{')[0].lower(), o)
               for n, ords in e32imports.imports(d) for o in ords]
    defs = find_defs()
    new = {lib: defs[lib] for lib in {l for l, _o in imports} if lib in defs}
    rows = shimtable.match(imports, {'euser': KERNEL + '/kernel/eka/bmarm/7.0-euseru.def'},
                           new, epoc6=EPOC6)
    dlls = sorted({lib for _i, lib, _o, _s, ordinal, _src in rows if ordinal})
    return rows, dlls


def emit(rows, dlls, path):
    lines = ['// Generated by gen_shim.py -- do not edit.',
             '//',
             '// One word per import: (DLL index + 1) << 16 | 9.x ordinal, or 0 when',
             '// nothing matched and the import keeps its reporting stub.',
             '',
             'extern "C" {',
             '']
    for i, dll in enumerate(dlls):
        name = dll if dll.endswith('.dll') else dll + '.dll'
        chars = ', '.join("'%s'" % c for c in name)
        lines.append('extern const unsigned short kShimDll%d[];' % i)
        lines.append('extern const unsigned short kShimDll%d[] = { %s };' % (i, chars))
    lines.append('')
    lines.append('extern const unsigned short *const kShimDllName[] = { %s };'
                 % ', '.join('kShimDll%d' % i for i in range(len(dlls))))
    lines.append('extern const unsigned char kShimDllLen[] = { %s };'
                 % ', '.join(str(len(d if d.endswith('.dll') else d + '.dll')) for d in dlls))
    lines.append('extern const unsigned int kShimDllCount = %d;' % len(dlls))
    lines.append('')

    index = {d: i for i, d in enumerate(dlls)}
    words = []
    for _i, lib, _o, _sig, ordinal, _src in rows:
        words.append(((index[lib] + 1) << 16 | ordinal) if ordinal else 0)
    lines.append('extern const unsigned int kShimTable[] = {')
    for i in range(0, len(words), 8):
        lines.append('    ' + ' '.join('0x%08X,' % w for w in words[i:i + 8]))
    lines.append('};')
    lines.append('extern const unsigned int kShimCount = %d;' % len(words))
    lines.append('')
    lines.append('}')
    open(path, 'w').write('\n'.join(lines) + '\n')
    return sum(1 for w in words if w)


if __name__ == '__main__':
    rows, dlls = build(sys.argv[1])
    n = emit(rows, dlls, sys.argv[2])
    print('%s: %d of %d imports forwarded across %d DLLs (%s)'
          % (sys.argv[2], n, len(rows), len(dlls), ', '.join(dlls)))
