// Generated by gen_shim.py from 6r67.app -- do not edit.
//
// Which import index each diversion sits at in THIS game. See HOOKS in
// gen_shim.py for what each one is; 65535 means the game never imports it
// and the guards in gate6.cpp then leave that hook uninstalled.
//
// GAME_UID3 is the image these indices were read out of. The loader
// checks it against the image it is actually given, because this
// header and gate4_shim.cpp are generated as a pair from one game
// and are meaningless against another -- and a wrong index is not an
// error, it is a call to the wrong function.
#ifndef GATE_IMPORTS_H
#define GATE_IMPORTS_H

enum { GAME_UID3 = 0x101fd3fc };

enum {
    IMPORT_ADDDF3                      =   343,
    IMPORT_ADDTOSTACKL                 =    46,
    IMPORT_ADD_EVENT                   = 65535,   // absent
    IMPORT_ADD_FOREGROUND_OBSERVER     = 65535,   // absent
    IMPORT_AKN_CBA                     = 65535,   // absent
    IMPORT_AKN_STATUS_PANE             = 65535,   // absent
    IMPORT_APPUI_EXIT                  = 65535,   // absent
    IMPORT_APPUI_FACTORY               = 65535,   // absent
    IMPORT_APPUI_PREPARE_EXIT          =    29,
    IMPORT_APP_FULL_NAME               =     0,
    IMPORT_APP_RECT                    =   160,
    IMPORT_BASECONSTRUCTL              =     5,
    IMPORT_CACTIVE_CTOR                =   336,
    IMPORT_CANCEL                      =   253,
    IMPORT_CHUNK_CREATE_GLOBAL         = 65535,   // absent
    IMPORT_CLEANUP_NEW                 =   290,
    IMPORT_CLIENT_RECT                 = 65535,   // absent
    IMPORT_COECONTROL_CTOR             =    82,
    IMPORT_COEENV_STATIC               =    79,
    IMPORT_CREATEWINDOWL               =    51,
    IMPORT_CREATE_BITMAP               = 65535,   // absent
    IMPORT_CREATE_CONTEXT              = 65535,   // absent
    IMPORT_CREATE_SESSION              =   267,
    IMPORT_CTIMER_CTOR                 =   332,
    IMPORT_CTIMER_DOCANCEL             =   274,
    IMPORT_CTIMER_DTOR                 =   322,
    IMPORT_CTL_DRAWABLE_WINDOW         = 65535,   // absent
    IMPORT_CTL_RECT                    = 65535,   // absent
    IMPORT_CTL_SETRECT                 =    91,
    IMPORT_DEF_MODE_COLORS             = 65535,   // absent
    IMPORT_DELETE_OP                   =   346,
    IMPORT_DES_FORMAT                  = 65535,   // absent
    IMPORT_DES_FORMATLIST              = 65535,   // absent
    IMPORT_DIVDF3                      = 65535,   // absent
    IMPORT_DLL_NAME                    =     2,
    IMPORT_DSA_NEWL                    =   389,
    IMPORT_DSA_STARTL                  =   390,
    IMPORT_EQDF2                       = 65535,   // absent
    IMPORT_EXIT                        =   276,
    IMPORT_EXTENDSFDF2                 =   350,
    IMPORT_FBS_BITMAP_CREATE           =   364,
    IMPORT_FBS_BITMAP_CTOR             =   366,
    IMPORT_FBS_DATA_ADDRESS            =   365,
    IMPORT_FBS_DISPLAY_MODE            = 65535,   // absent
    IMPORT_FILEMAN_NEWL                = 65535,   // absent
    IMPORT_FILE_CREATE                 =    94,
    IMPORT_FILE_OPEN                   =   100,
    IMPORT_FILE_READ                   =   101,
    IMPORT_FILE_READ_POS               = 65535,   // absent
    IMPORT_FILE_READ_STATIC            =   101,
    IMPORT_FILE_REPLACE                = 65535,   // absent
    IMPORT_FILE_SIZE                   =   104,
    IMPORT_FIND_WILD_BY_DIR            = 65535,   // absent
    IMPORT_FIXDFSI                     = 65535,   // absent
    IMPORT_FLOATSIDF                   =   352,
    IMPORT_FOPEN                       =   213,
    IMPORT_FS_CONNECT                  =    93,
    IMPORT_FS_ENTRY                    = 65535,   // absent
    IMPORT_FS_MKDIRALL                 =    98,
    IMPORT_FS_MODIFIED                 = 65535,   // absent
    IMPORT_FS_SESSION_PATH             = 65535,   // absent
    IMPORT_FS_SET_DEFAULT_PATH         = 65535,   // absent
    IMPORT_FS_VOLUME                   = 65535,   // absent
    IMPORT_GC_SETCLIP                  =    42,
    IMPORT_GEDF2                       = 65535,   // absent
    IMPORT_GTDF2                       = 65535,   // absent
    IMPORT_HANDLE_CLOSE                =   254,
    IMPORT_LEAVE                       =   287,
    IMPORT_LEAVE_IF_ERROR              =   285,
    IMPORT_LEAVE_NOMEM                 =   286,
    IMPORT_LEDF2                       = 65535,   // absent
    IMPORT_LEX16_VAL_REAL              = 65535,   // absent
    IMPORT_LIBRARY_LOAD                = 65535,   // absent
    IMPORT_LIBRARY_LOOKUP              = 65535,   // absent
    IMPORT_LTDF2                       = 65535,   // absent
    IMPORT_MALLOC                      =   202,
    IMPORT_MATH_ACOS                   = 65535,   // absent
    IMPORT_MATH_ASIN                   = 65535,   // absent
    IMPORT_MATH_ATAN                   = 65535,   // absent
    IMPORT_MATH_ATAN2                  = 65535,   // absent
    IMPORT_MATH_COS                    = 65535,   // absent
    IMPORT_MATH_EXP                    = 65535,   // absent
    IMPORT_MATH_FRAC                   = 65535,   // absent
    IMPORT_MATH_FRAND                  = 65535,   // absent
    IMPORT_MATH_INT                    = 65535,   // absent
    IMPORT_MATH_INT16                  = 65535,   // absent
    IMPORT_MATH_INT_D                  = 65535,   // absent
    IMPORT_MATH_LN                     = 65535,   // absent
    IMPORT_MATH_LOG                    = 65535,   // absent
    IMPORT_MATH_MOD                    = 65535,   // absent
    IMPORT_MATH_POW                    = 65535,   // absent
    IMPORT_MATH_ROUND                  = 65535,   // absent
    IMPORT_MATH_SIN                    = 65535,   // absent
    IMPORT_MATH_SQRT                   = 65535,   // absent
    IMPORT_MATH_TAN                    = 65535,   // absent
    IMPORT_MDA_NEWL                    =   385,
    IMPORT_MKDIR                       = 65535,   // absent
    IMPORT_MSG_COMPLETE                =   256,
    IMPORT_MULDF3                      =   355,
    IMPORT_NEDF2                       = 65535,   // absent
    IMPORT_NEGDF2                      = 65535,   // absent
    IMPORT_PANIC                       =   293,
    IMPORT_PUSHL_CBASE                 =   299,
    IMPORT_READ_FILE_SECTION           = 65535,   // absent
    IMPORT_REQUEST_COMPLETE            =   303,
    IMPORT_RWIN_BEGIN_REDRAW           = 65535,   // absent
    IMPORT_RWIN_CTOR                   = 65535,   // absent
    IMPORT_RWIN_CTOR_WS                = 65535,   // absent
    IMPORT_RWIN_END_REDRAW             = 65535,   // absent
    IMPORT_SCREEN_INFO                 =   308,
    IMPORT_SCREEN_UPDATE               =    43,
    IMPORT_SEM_CREATE                  =   266,
    IMPORT_SEM_WAIT                    =   318,
    IMPORT_SEND_RECEIVE                =   309,
    IMPORT_SERVER_STARTL               =   313,
    IMPORT_SET_AUTO_UPDATE             =    41,
    IMPORT_SHADOW_BUFFLAT              = 65535,   // absent
    IMPORT_SHADOW_CMDLINE              = 65535,   // absent
    IMPORT_SHADOW_DESC16FLAT           = 65535,   // absent
    IMPORT_SHADOW_DESC8FLAT            = 65535,   // absent
    IMPORT_SHADOW_FILEMAN              = 65535,   // absent
    IMPORT_SHADOW_MSVSESSION           = 65535,   // absent
    IMPORT_SHADOW_PERIODIC             = 65535,   // absent
    IMPORT_SHADOW_SCREENDEVICE         = 65535,   // absent
    IMPORT_SHADOW_SDPAGENT             = 65535,   // absent
    IMPORT_SHADOW_SDPPATTERN           = 65535,   // absent
    IMPORT_SHADOW_WGNAME               = 65535,   // absent
    IMPORT_START_APP                   = 65535,   // absent
    IMPORT_SUBDF3                      = 65535,   // absent
    IMPORT_SYSTEM_GC                   = 65535,   // absent
    IMPORT_THREAD_CREATE               =   268,
    IMPORT_THREAD_OPEN                 =   292,
    IMPORT_THREAD_RESUME               =   305,
    IMPORT_THREAD_SUSPEND              = 65535,   // absent
    IMPORT_TRUNCDFSF2                  =   360,
    IMPORT_UNLINK                      = 65535,   // absent
    IMPORT_USER_ALLOC                  =   252,
    IMPORT_USER_ALLOCL                 =   251,
    IMPORT_USER_ALLOCZ                 =   358,
    IMPORT_USER_ALLOCZL                =   247,
    IMPORT_USER_FREE_OP                =   280,
    IMPORT_VEC_DELETE_OP               =   347,
    IMPORT_WFOPEN                      = 65535,   // absent
    IMPORT_WINDOW                      =    80,
    IMPORT_WS_EVENT_READY              = 65535,   // absent
    IMPORT_WS_GET_EVENT                = 65535,   // absent
};

// Imports that are a method on CCoeEnv. The game holds a copy of the
// environment laid out the old way; cone has to be given the real one.
//     47  CCoeEnv::AllocReadResourceAsDes16LC(int) const
#define GATE_COEENV_METHODS  47
#define GATE_COEENV_METHOD_COUNT 1

// Methods on CEikAppUi. A null `this` from the game is replaced
// with the real app UI, when the game asks for it (GAME_FIX_APPUI_THIS).
#define GATE_APPUI_METHODS  109, 113, 116, 123, 125, 127, 128, 129, 135, 137, 141, 143, 144, 145, 150, 151
#define GATE_APPUI_METHOD_COUNT 16

// The trace lists: see MILESTONES and HOT in gen_shim.py. Both may be
// empty, which is why gate6.cpp appends the two exits to the first.
#define GATE_MILESTONES  389, 390, 93, 100, 101, 92, 41, 42, 303, 266, 268, 311, 305, 318, 254, 290, 329, 282, 312, 285, 314, 267, 309, 265, 337, 313, 307, 338, 256, 319, 294, 385, 286, 280, 97, 99, 95,
#define GATE_HOT  361, 362, 258, 354, 327, 246, 298,
#define GATE_HOT_COUNT 7

// The diversions: see DIVERTS in gen_shim.py. {import, register,
// which wrapper}, and an import the game does not have is left out.
#define GATE_DIVERTS  { 160, 1, 0 }, { 91, 0, 1 }, { 45, 0, 1 }, { 64, 0, 1 }, { 65, 0, 1 }, { 75, 1, 1 }, { 69, 1, 1 }, { 16, 0, 0 }, { 18, 0, 0 }, { 42, 0, 3 }, { 257, 0, 2 }, { 250, 0, 2 }, { 248, 0, 2 }, { 310, 0, 2 },
#define GATE_DIVERT_COUNT 14

#endif
