// Generated by gen_shim.py from 6rbc_orig.app -- do not edit.
//
// Which import index each diversion sits at in THIS game. See HOOKS in
// gen_shim.py for what each one is; 65535 means the game never imports it
// and the guards in gate6.cpp then leave that hook uninstalled.
//
// GAME_UID3 is the image these indices were read out of. The loader
// checks it against the image it is actually given, because this
// header and gate4_shim.cpp are generated as a pair from one game
// and are meaningless against another -- and a wrong index is not an
// error, it is a call to the wrong function.
#ifndef GATE_IMPORTS_H
#define GATE_IMPORTS_H

enum { GAME_UID3 = 0x101fd42d };

enum {
    IMPORT_ADDTOSTACKL                 =    51,
    IMPORT_ADD_FOREGROUND_OBSERVER     =    50,
    IMPORT_APP_RECT                    =   172,
    IMPORT_BASECONSTRUCTL              =     9,
    IMPORT_CANCEL                      =   279,
    IMPORT_COECONTROL_CTOR             =    89,
    IMPORT_COEENV_STATIC               =    86,
    IMPORT_CREATEWINDOWL               =    55,
    IMPORT_CREATE_SESSION              =   298,
    IMPORT_CTIMER_CTOR                 =   391,
    IMPORT_DELETE_OP                   =   408,
    IMPORT_DLL_NAME                    =     2,
    IMPORT_DSA_NEWL                    =   460,
    IMPORT_DSA_STARTL                  =   461,
    IMPORT_EXIT                        =   308,
    IMPORT_FILE_CREATE                 =   101,
    IMPORT_FILE_OPEN                   =   109,
    IMPORT_FILE_READ                   =   110,
    IMPORT_FILE_READ_STATIC            =   110,
    IMPORT_FILE_REPLACE                =   111,
    IMPORT_LEAVE                       =   324,
    IMPORT_LEAVE_IF_ERROR              =   322,
    IMPORT_LEAVE_NOMEM                 =   323,
    IMPORT_LIBRARY_LOAD                =   325,
    IMPORT_LIBRARY_LOOKUP              =   326,
    IMPORT_MALLOC                      =   215,
    IMPORT_MDA_NEWL                    =   458,
    IMPORT_MSG_COMPLETE                =   285,
    IMPORT_PANIC                       =   338,
    IMPORT_REQUEST_COMPLETE            =   350,
    IMPORT_SCREEN_INFO                 =   356,
    IMPORT_SCREEN_UPDATE               =    47,
    IMPORT_SEM_CREATE                  =   296,
    IMPORT_SEM_WAIT                    =   374,
    IMPORT_SEND_RECEIVE                =   357,
    IMPORT_SERVER_STARTL               =   366,
    IMPORT_SET_AUTO_UPDATE             =    45,
    IMPORT_THREAD_CREATE               =   299,
    IMPORT_USER_ALLOC                  =   270,
    IMPORT_USER_ALLOCL                 =   269,
    IMPORT_USER_ALLOCZ                 =   421,
    IMPORT_USER_ALLOCZL                =   265,
    IMPORT_USER_FREE_OP                =   315,
    IMPORT_VEC_DELETE_OP               =   410,
    IMPORT_WINDOW                      =    87,
};

// Imports that are a method on CCoeEnv. The game holds a copy of the
// environment laid out the old way; cone has to be given the real one.
//     75  CCoeEnv::RemoveForegroundObserver(MCoeForegroundObserver &)
#define GATE_COEENV_METHODS  75
#define GATE_COEENV_METHOD_COUNT 1

// Methods on CEikAppUi. A null `this` from the game is replaced
// with the real app UI, when the game asks for it (GAME_FIX_APPUI_THIS).
#define GATE_APPUI_METHODS  121, 125, 128, 135, 137, 139, 140, 141, 147, 149, 153, 155, 156, 157, 162, 163
#define GATE_APPUI_METHOD_COUNT 16

// The trace lists: see MILESTONES and HOT in gen_shim.py. Both may be
// empty, which is why gate6.cpp appends the two exits to the first.
#define GATE_MILESTONES  100, 109, 110, 99, 325, 326, 283, 45, 46, 350, 296, 299, 362, 353, 374, 281, 330, 386, 319, 363, 367, 298, 357, 295, 397, 366, 355, 400, 285, 376, 339, 458, 372, 269, 373, 323, 315,
#define GATE_HOT  424, 425, 274, 287, 272, 417, 383, 369, 389, 264, 344,
#define GATE_HOT_COUNT 11

#endif
