// Generated by gen_shim.py from 6r58.app -- do not edit.
//
// Which import index each diversion sits at in THIS game. See HOOKS in
// gen_shim.py for what each one is; 65535 means the game never imports it
// and the guards in gate6.cpp then leave that hook uninstalled.
//
// GAME_UID3 is the image these indices were read out of. The loader
// checks it against the image it is actually given, because this
// header and gate4_shim.cpp are generated as a pair from one game
// and are meaningless against another -- and a wrong index is not an
// error, it is a call to the wrong function.
#ifndef GATE_IMPORTS_H
#define GATE_IMPORTS_H

enum { GAME_UID3 = 0x101fd409 };

enum {
    IMPORT_ADDDF3                      =   456,
    IMPORT_ADDTOSTACKL                 =    38,
    IMPORT_ADD_FOREGROUND_OBSERVER     =    37,
    IMPORT_APPUI_EXIT                  =   135,
    IMPORT_APPUI_FACTORY               =   123,
    IMPORT_APPUI_PREPARE_EXIT          =    23,
    IMPORT_APP_FULL_NAME               =     0,
    IMPORT_APP_RECT                    = 65535,   // absent
    IMPORT_BASECONSTRUCTL              =    10,
    IMPORT_CACTIVE_CTOR                =   445,
    IMPORT_CANCEL                      =   285,
    IMPORT_CLEANUP_NEW                 =   356,
    IMPORT_CLIENT_RECT                 =   128,
    IMPORT_COECONTROL_CTOR             =    79,
    IMPORT_COEENV_STATIC               =    76,
    IMPORT_CREATEWINDOWL               =    43,
    IMPORT_CREATE_CONTEXT              = 65535,   // absent
    IMPORT_CREATE_SESSION              = 65535,   // absent
    IMPORT_CTIMER_CTOR                 =   434,
    IMPORT_CTIMER_DOCANCEL             =   319,
    IMPORT_CTIMER_DTOR                 =   420,
    IMPORT_CTL_DRAWABLE_WINDOW         = 65535,   // absent
    IMPORT_CTL_RECT                    = 65535,   // absent
    IMPORT_CTL_SETRECT                 = 65535,   // absent
    IMPORT_DELETE_OP                   =   460,
    IMPORT_DES_FORMAT                  =   328,
    IMPORT_DES_FORMATLIST              = 65535,   // absent
    IMPORT_DIVDF3                      =   464,
    IMPORT_DLL_NAME                    =     2,
    IMPORT_DSA_NEWL                    =   530,
    IMPORT_DSA_STARTL                  =   531,
    IMPORT_EQDF2                       =   468,
    IMPORT_EXIT                        = 65535,   // absent
    IMPORT_EXTENDSFDF2                 =   470,
    IMPORT_FBS_BITMAP_CREATE           = 65535,   // absent
    IMPORT_FBS_BITMAP_CTOR             = 65535,   // absent
    IMPORT_FBS_DATA_ADDRESS            = 65535,   // absent
    IMPORT_FBS_DISPLAY_MODE            = 65535,   // absent
    IMPORT_FILEMAN_NEWL                =   105,
    IMPORT_FILE_CREATE                 =    94,
    IMPORT_FILE_OPEN                   =   106,
    IMPORT_FILE_READ                   =   108,
    IMPORT_FILE_READ_POS               = 65535,   // absent
    IMPORT_FILE_READ_STATIC            =   108,
    IMPORT_FILE_REPLACE                =   110,
    IMPORT_FILE_SIZE                   =   115,
    IMPORT_FIND_WILD_BY_DIR            =   100,
    IMPORT_FIXDFSI                     =   471,
    IMPORT_FLOATSIDF                   =   473,
    IMPORT_FS_CONNECT                  =    91,
    IMPORT_FS_ENTRY                    =    98,
    IMPORT_FS_SET_DEFAULT_PATH         =   113,
    IMPORT_FS_VOLUME                   =   116,
    IMPORT_GEDF2                       =   476,
    IMPORT_GTDF2                       =   477,
    IMPORT_HANDLE_CLOSE                =   288,
    IMPORT_LEAVE                       =   343,
    IMPORT_LEAVE_IF_ERROR              =   341,
    IMPORT_LEAVE_NOMEM                 =   342,
    IMPORT_LEDF2                       = 65535,   // absent
    IMPORT_LEX16_VAL_REAL              =   413,
    IMPORT_LIBRARY_LOAD                =   345,
    IMPORT_LIBRARY_LOOKUP              =   346,
    IMPORT_LTDF2                       =   480,
    IMPORT_MALLOC                      =   186,
    IMPORT_MATH_ACOS                   =   498,
    IMPORT_MATH_ASIN                   = 65535,   // absent
    IMPORT_MATH_ATAN                   =   253,
    IMPORT_MATH_ATAN2                  =   254,
    IMPORT_MATH_COS                    =   304,
    IMPORT_MATH_EXP                    = 65535,   // absent
    IMPORT_MATH_FRAC                   =   329,
    IMPORT_MATH_FRAND                  =   320,
    IMPORT_MATH_INT                    = 65535,   // absent
    IMPORT_MATH_INT16                  = 65535,   // absent
    IMPORT_MATH_INT_D                  = 65535,   // absent
    IMPORT_MATH_LN                     = 65535,   // absent
    IMPORT_MATH_LOG                    = 65535,   // absent
    IMPORT_MATH_MOD                    = 65535,   // absent
    IMPORT_MATH_POW                    =   370,
    IMPORT_MATH_ROUND                  = 65535,   // absent
    IMPORT_MATH_SIN                    =   398,
    IMPORT_MATH_SQRT                   =   400,
    IMPORT_MATH_TAN                    =   406,
    IMPORT_MDA_NEWL                    =   525,
    IMPORT_MSG_COMPLETE                = 65535,   // absent
    IMPORT_MULDF3                      =   485,
    IMPORT_NEDF2                       =   487,
    IMPORT_NEGDF2                      =   488,
    IMPORT_PANIC                       =   365,
    IMPORT_PUSHL_CBASE                 =   374,
    IMPORT_READ_FILE_SECTION           = 65535,   // absent
    IMPORT_REQUEST_COMPLETE            =   382,
    IMPORT_SCREEN_INFO                 =   388,
    IMPORT_SCREEN_UPDATE               =    34,
    IMPORT_SEM_CREATE                  =   309,
    IMPORT_SEM_WAIT                    =   415,
    IMPORT_SEND_RECEIVE                = 65535,   // absent
    IMPORT_SERVER_STARTL               = 65535,   // absent
    IMPORT_SET_AUTO_UPDATE             =    32,
    IMPORT_SUBDF3                      =   493,
    IMPORT_SYSTEM_GC                   = 65535,   // absent
    IMPORT_THREAD_CREATE               =   312,
    IMPORT_THREAD_OPEN                 =   364,
    IMPORT_THREAD_RESUME               =   386,
    IMPORT_THREAD_SUSPEND              =   405,
    IMPORT_TRUNCDFSF2                  =   495,
    IMPORT_USER_ALLOC                  =   261,
    IMPORT_USER_ALLOCL                 =   259,
    IMPORT_USER_ALLOCZ                 =   490,
    IMPORT_USER_ALLOCZL                =   252,
    IMPORT_USER_FREE_OP                =   330,
    IMPORT_VEC_DELETE_OP               =   462,
    IMPORT_WINDOW                      =    77,
};

// Imports that are a method on CCoeEnv. The game holds a copy of the
// environment laid out the old way; cone has to be given the real one.
//     39  CCoeEnv::AllocReadResourceAsDes16LC(int) const
//     65  CCoeEnv::RemoveForegroundObserver(MCoeForegroundObserver &)
#define GATE_COEENV_METHODS  39, 65
#define GATE_COEENV_METHOD_COUNT 2

// Methods on CEikAppUi. A null `this` from the game is replaced
// with the real app UI, when the game asks for it (GAME_FIX_APPUI_THIS).
#define GATE_APPUI_METHODS  124, 131, 138, 141, 142, 143, 149, 151, 155, 157, 158, 159, 164, 165
#define GATE_APPUI_METHOD_COUNT 14

// The trace lists: see MILESTONES and HOT in gen_shim.py. Both may be
// empty, which is why gate6.cpp appends the two exits to the first.
#define GATE_MILESTONES  91, 106, 108, 90, 345, 346, 290, 32, 33, 382, 309, 312, 394, 386, 415, 288, 356, 429, 338, 395, 341, 401, 525, 342, 330, 110, 102, 95,
#define GATE_HOT  496, 497, 279, 298, 273, 484, 424, 404, 432, 251, 373,
#define GATE_HOT_COUNT 11

// The diversions: see DIVERTS in gen_shim.py. {import, register,
// which wrapper}, and an import the game does not have is left out.
#define GATE_DIVERTS  { 128, 1, 0 }, { 36, 0, 1 }, { 57, 0, 1 }, { 73, 0, 1 }, { 60, 0, 1 }, { 71, 1, 1 }, { 66, 1, 1 }, { 13, 0, 0 }, { 15, 0, 0 }, { 33, 0, 3 }, { 296, 0, 2 }, { 257, 0, 2 }, { 255, 0, 2 }, { 389, 0, 2 },
#define GATE_DIVERT_COUNT 14

#endif
