// Generated by gen_shim.py from 6r66.lxe -- do not edit.
//
// Which import index each diversion sits at in THIS game. See HOOKS in
// gen_shim.py for what each one is; 65535 means the game never imports it
// and the guards in gate6.cpp then leave that hook uninstalled.
//
// GAME_UID3 is the image these indices were read out of. The loader
// checks it against the image it is actually given, because this
// header and gate4_shim.cpp are generated as a pair from one game
// and are meaningless against another -- and a wrong index is not an
// error, it is a call to the wrong function.
#ifndef GATE_IMPORTS_H
#define GATE_IMPORTS_H

enum { GAME_UID3 = 0x00000000 };

enum {
    IMPORT_ADDDF3                      = 65535,   // absent
    IMPORT_ADDTOSTACKL                 = 65535,   // absent
    IMPORT_ADD_EVENT                   =   114,
    IMPORT_ADD_FOREGROUND_OBSERVER     = 65535,   // absent
    IMPORT_AKN_CBA                     = 65535,   // absent
    IMPORT_AKN_STATUS_PANE             = 65535,   // absent
    IMPORT_APPUI_EXIT                  = 65535,   // absent
    IMPORT_APPUI_FACTORY               = 65535,   // absent
    IMPORT_APPUI_PREPARE_EXIT          = 65535,   // absent
    IMPORT_APP_FULL_NAME               = 65535,   // absent
    IMPORT_APP_RECT                    = 65535,   // absent
    IMPORT_BASECONSTRUCTL              = 65535,   // absent
    IMPORT_CACTIVE_CTOR                =   209,
    IMPORT_CANCEL                      =   125,
    IMPORT_CHUNK_CREATE_GLOBAL         =   136,
    IMPORT_CLEANUP_NEW                 =   153,
    IMPORT_CLIENT_RECT                 = 65535,   // absent
    IMPORT_COECONTROL_CTOR             = 65535,   // absent
    IMPORT_COEENV_STATIC               = 65535,   // absent
    IMPORT_CREATEWINDOWL               = 65535,   // absent
    IMPORT_CREATE_BITMAP               = 65535,   // absent
    IMPORT_CREATE_CONTEXT              = 65535,   // absent
    IMPORT_CREATE_SESSION              = 65535,   // absent
    IMPORT_CTIMER_CTOR                 = 65535,   // absent
    IMPORT_CTIMER_DOCANCEL             = 65535,   // absent
    IMPORT_CTIMER_DTOR                 = 65535,   // absent
    IMPORT_CTL_DRAWABLE_WINDOW         = 65535,   // absent
    IMPORT_CTL_RECT                    = 65535,   // absent
    IMPORT_CTL_SETRECT                 = 65535,   // absent
    IMPORT_DEF_MODE_COLORS             =   322,
    IMPORT_DELETE_OP                   =   217,
    IMPORT_DES_FORMAT                  = 65535,   // absent
    IMPORT_DES_FORMATLIST              = 65535,   // absent
    IMPORT_DIVDF3                      =   221,
    IMPORT_DLL_NAME                    = 65535,   // absent
    IMPORT_DSA_NEWL                    =   324,
    IMPORT_DSA_STARTL                  =   325,
    IMPORT_EQDF2                       = 65535,   // absent
    IMPORT_EXIT                        =   138,
    IMPORT_EXTENDSFDF2                 = 65535,   // absent
    IMPORT_FBS_BITMAP_CREATE           =   241,
    IMPORT_FBS_BITMAP_CTOR             =   245,
    IMPORT_FBS_DATA_ADDRESS            =   242,
    IMPORT_FBS_DISPLAY_MODE            = 65535,   // absent
    IMPORT_FILEMAN_NEWL                =    37,
    IMPORT_FILE_CREATE                 = 65535,   // absent
    IMPORT_FILE_OPEN                   = 65535,   // absent
    IMPORT_FILE_READ                   = 65535,   // absent
    IMPORT_FILE_READ_POS               = 65535,   // absent
    IMPORT_FILE_READ_STATIC            = 65535,   // absent
    IMPORT_FILE_REPLACE                = 65535,   // absent
    IMPORT_FILE_SIZE                   = 65535,   // absent
    IMPORT_FIND_WILD_BY_DIR            = 65535,   // absent
    IMPORT_FIXDFSI                     =   225,
    IMPORT_FLOATSIDF                   =   226,
    IMPORT_FS_CONNECT                  =    34,
    IMPORT_FS_ENTRY                    = 65535,   // absent
    IMPORT_FS_SET_DEFAULT_PATH         = 65535,   // absent
    IMPORT_FS_VOLUME                   =    40,
    IMPORT_GC_SETCLIP                  = 65535,   // absent
    IMPORT_GEDF2                       = 65535,   // absent
    IMPORT_GTDF2                       = 65535,   // absent
    IMPORT_HANDLE_CLOSE                =   126,
    IMPORT_LEAVE                       =   148,
    IMPORT_LEAVE_IF_ERROR              =   147,
    IMPORT_LEAVE_NOMEM                 = 65535,   // absent
    IMPORT_LEDF2                       = 65535,   // absent
    IMPORT_LEX16_VAL_REAL              = 65535,   // absent
    IMPORT_LIBRARY_LOAD                = 65535,   // absent
    IMPORT_LIBRARY_LOOKUP              = 65535,   // absent
    IMPORT_LTDF2                       = 65535,   // absent
    IMPORT_MALLOC                      =    67,
    IMPORT_MATH_ACOS                   = 65535,   // absent
    IMPORT_MATH_ASIN                   = 65535,   // absent
    IMPORT_MATH_ATAN                   = 65535,   // absent
    IMPORT_MATH_ATAN2                  = 65535,   // absent
    IMPORT_MATH_COS                    = 65535,   // absent
    IMPORT_MATH_EXP                    = 65535,   // absent
    IMPORT_MATH_FRAC                   = 65535,   // absent
    IMPORT_MATH_FRAND                  = 65535,   // absent
    IMPORT_MATH_INT                    = 65535,   // absent
    IMPORT_MATH_INT16                  = 65535,   // absent
    IMPORT_MATH_INT_D                  = 65535,   // absent
    IMPORT_MATH_LN                     = 65535,   // absent
    IMPORT_MATH_LOG                    = 65535,   // absent
    IMPORT_MATH_MOD                    = 65535,   // absent
    IMPORT_MATH_POW                    = 65535,   // absent
    IMPORT_MATH_ROUND                  = 65535,   // absent
    IMPORT_MATH_SIN                    = 65535,   // absent
    IMPORT_MATH_SQRT                   = 65535,   // absent
    IMPORT_MATH_TAN                    = 65535,   // absent
    IMPORT_MDA_NEWL                    =   249,
    IMPORT_MSG_COMPLETE                = 65535,   // absent
    IMPORT_MULDF3                      =   232,
    IMPORT_NEDF2                       = 65535,   // absent
    IMPORT_NEGDF2                      = 65535,   // absent
    IMPORT_PANIC                       =   157,
    IMPORT_PUSHL_CBASE                 =   165,
    IMPORT_READ_FILE_SECTION           = 65535,   // absent
    IMPORT_REQUEST_COMPLETE            =   168,
    IMPORT_RWIN_BEGIN_REDRAW           =   281,
    IMPORT_RWIN_CTOR                   =   318,
    IMPORT_RWIN_CTOR_WS                =   319,
    IMPORT_RWIN_END_REDRAW             =   290,
    IMPORT_SCREEN_INFO                 =   176,
    IMPORT_SCREEN_UPDATE               = 65535,   // absent
    IMPORT_SEM_CREATE                  = 65535,   // absent
    IMPORT_SEM_WAIT                    = 65535,   // absent
    IMPORT_SEND_RECEIVE                = 65535,   // absent
    IMPORT_SERVER_STARTL               = 65535,   // absent
    IMPORT_SET_AUTO_UPDATE             = 65535,   // absent
    IMPORT_SHADOW_BUFFLAT              = 65535,   // absent
    IMPORT_SHADOW_CMDLINE              =     6,
    IMPORT_SHADOW_DESC16FLAT           = 65535,   // absent
    IMPORT_SHADOW_DESC8FLAT            = 65535,   // absent
    IMPORT_SHADOW_FILEMAN              =    37,
    IMPORT_SHADOW_MSVSESSION           =   251,
    IMPORT_SHADOW_PERIODIC             =   152,
    IMPORT_SHADOW_SCREENDEVICE         =   317,
    IMPORT_SHADOW_SDPAGENT             =   254,
    IMPORT_SHADOW_SDPPATTERN           =   263,
    IMPORT_SHADOW_WGNAME               =     1,
    IMPORT_START_APP                   =     3,
    IMPORT_SUBDF3                      = 65535,   // absent
    IMPORT_SYSTEM_GC                   = 65535,   // absent
    IMPORT_THREAD_CREATE               =   137,
    IMPORT_THREAD_OPEN                 =   156,
    IMPORT_THREAD_RESUME               =   172,
    IMPORT_THREAD_SUSPEND              =   188,
    IMPORT_TRUNCDFSF2                  = 65535,   // absent
    IMPORT_USER_ALLOC                  = 65535,   // absent
    IMPORT_USER_ALLOCL                 =   117,
    IMPORT_USER_ALLOCZ                 =   234,
    IMPORT_USER_ALLOCZL                =   113,
    IMPORT_USER_FREE_OP                = 65535,   // absent
    IMPORT_VEC_DELETE_OP               =   219,
    IMPORT_WINDOW                      = 65535,   // absent
    IMPORT_WS_GET_EVENT                =   295,
};

// Imports that are a method on CCoeEnv. The game holds a copy of the
// environment laid out the old way; cone has to be given the real one.
#define GATE_COEENV_METHODS  /* none */
#define GATE_COEENV_METHOD_COUNT 0

// Methods on CEikAppUi. A null `this` from the game is replaced
// with the real app UI, when the game asks for it (GAME_FIX_APPUI_THIS).
#define GATE_APPUI_METHODS  /* none */
#define GATE_APPUI_METHOD_COUNT 0

// The trace lists: see MILESTONES and HOT in gen_shim.py. Both may be
// empty, which is why gate6.cpp appends the two exits to the first.
#define GATE_MILESTONES  285, 287, 308, 320, 310, 311, 322, 324, 325, 34, 168, 137, 180, 172, 126, 153, 201, 144, 147, 184, 249,
#define GATE_HOT  237, 238, 120, 231, 198, 187, 203, 112, 163,
#define GATE_HOT_COUNT 9

// The diversions: see DIVERTS in gen_shim.py. {import, register,
// which wrapper}, and an import the game does not have is left out.
#define GATE_DIVERTS  { 115, 0, 2 }, { 178, 0, 2 },
#define GATE_DIVERT_COUNT 2

#endif
