// Generated by gen_shim.py from 6r66_2.app -- do not edit.
//
// Which import index each diversion sits at in THIS game. See HOOKS in
// gen_shim.py for what each one is; 65535 means the game never imports it
// and the guards in gate6.cpp then leave that hook uninstalled.
//
// GAME_UID3 is the image these indices were read out of. The loader
// checks it against the image it is actually given, because this
// header and gate4_shim.cpp are generated as a pair from one game
// and are meaningless against another -- and a wrong index is not an
// error, it is a call to the wrong function.
#ifndef GATE_IMPORTS_H
#define GATE_IMPORTS_H

enum { GAME_UID3 = 0x101fd417 };

enum {
    IMPORT_ADDDF3                      = 65535,   // absent
    IMPORT_ADDTOSTACKL                 =    66,
    IMPORT_ADD_EVENT                   = 65535,   // absent
    IMPORT_ADD_FOREGROUND_OBSERVER     = 65535,   // absent
    IMPORT_AKN_CBA                     =    15,
    IMPORT_AKN_STATUS_PANE             =    43,
    IMPORT_APPUI_EXIT                  =   262,
    IMPORT_APPUI_FACTORY               = 65535,   // absent
    IMPORT_APPUI_PREPARE_EXIT          =    38,
    IMPORT_APP_FULL_NAME               =     4,
    IMPORT_APP_RECT                    = 65535,   // absent
    IMPORT_BASECONSTRUCTL              =    13,
    IMPORT_BMU_BEGIN                   = 65535,   // absent
    IMPORT_BMU_END                     = 65535,   // absent
    IMPORT_CACTIVE_CTOR                =   533,
    IMPORT_CANCEL                      =   424,
    IMPORT_CHUNK_CREATE_GLOBAL         =   440,
    IMPORT_CLEANUP_NEW                 = 65535,   // absent
    IMPORT_CLIENT_RECT                 = 65535,   // absent
    IMPORT_COECONTROL_CTOR             =   111,
    IMPORT_COEENV_STATIC               =   108,
    IMPORT_CREATEWINDOWL               =    71,
    IMPORT_CREATE_BITMAP               =   254,
    IMPORT_CREATE_CONTEXT              = 65535,   // absent
    IMPORT_CREATE_SESSION              =   442,
    IMPORT_CTIMER_CTOR                 =   531,
    IMPORT_CTIMER_DOCANCEL             =   448,
    IMPORT_CTIMER_DTOR                 =   517,
    IMPORT_CTL_DRAWABLE_WINDOW         = 65535,   // absent
    IMPORT_CTL_RECT                    =    93,
    IMPORT_CTL_SETRECT                 =   120,
    IMPORT_DEF_MODE_COLORS             = 65535,   // absent
    IMPORT_DELETE_OP                   =   547,
    IMPORT_DES_FORMAT                  = 65535,   // absent
    IMPORT_DES_FORMATLIST              = 65535,   // absent
    IMPORT_DIVDF3                      = 65535,   // absent
    IMPORT_DLL_NAME                    = 65535,   // absent
    IMPORT_DSA_NEWL                    = 65535,   // absent
    IMPORT_DSA_STARTL                  = 65535,   // absent
    IMPORT_EQDF2                       = 65535,   // absent
    IMPORT_EXIT                        = 65535,   // absent
    IMPORT_EXTENDSFDF2                 = 65535,   // absent
    IMPORT_FBS_BITMAP_CREATE           = 65535,   // absent
    IMPORT_FBS_BITMAP_CTOR             = 65535,   // absent
    IMPORT_FBS_DATA_ADDRESS            = 65535,   // absent
    IMPORT_FBS_DISPLAY_MODE            = 65535,   // absent
    IMPORT_FILEMAN_NEWL                = 65535,   // absent
    IMPORT_FILE_CREATE                 = 65535,   // absent
    IMPORT_FILE_OPEN                   =   128,
    IMPORT_FILE_READ                   =   129,
    IMPORT_FILE_READ_POS               = 65535,   // absent
    IMPORT_FILE_READ_STATIC            =   129,
    IMPORT_FILE_REPLACE                = 65535,   // absent
    IMPORT_FILE_SIZE                   = 65535,   // absent
    IMPORT_FIND_WILD_BY_DIR            = 65535,   // absent
    IMPORT_FIXDFSI                     = 65535,   // absent
    IMPORT_FLOATSIDF                   = 65535,   // absent
    IMPORT_FOPEN                       = 65535,   // absent
    IMPORT_FS_CONNECT                  =   125,
    IMPORT_FS_ENTRY                    = 65535,   // absent
    IMPORT_FS_MKDIRALL                 =   127,
    IMPORT_FS_MODIFIED                 = 65535,   // absent
    IMPORT_FS_SESSION_PATH             = 65535,   // absent
    IMPORT_FS_SET_DEFAULT_PATH         = 65535,   // absent
    IMPORT_FS_VOLUME                   =   130,
    IMPORT_GC_SETCLIP                  = 65535,   // absent
    IMPORT_GEDF2                       = 65535,   // absent
    IMPORT_GTDF2                       = 65535,   // absent
    IMPORT_HANDLE_CLOSE                =   425,
    IMPORT_LEAVE                       =   458,
    IMPORT_LEAVE_IF_ERROR              =   457,
    IMPORT_LEAVE_NOMEM                 = 65535,   // absent
    IMPORT_LEDF2                       = 65535,   // absent
    IMPORT_LEX16_VAL_REAL              = 65535,   // absent
    IMPORT_LIBRARY_LOAD                = 65535,   // absent
    IMPORT_LIBRARY_LOOKUP              =   461,
    IMPORT_LTDF2                       = 65535,   // absent
    IMPORT_MALLOC                      = 65535,   // absent
    IMPORT_MATH_ACOS                   = 65535,   // absent
    IMPORT_MATH_ASIN                   = 65535,   // absent
    IMPORT_MATH_ATAN                   = 65535,   // absent
    IMPORT_MATH_ATAN2                  = 65535,   // absent
    IMPORT_MATH_COS                    = 65535,   // absent
    IMPORT_MATH_EXP                    = 65535,   // absent
    IMPORT_MATH_FRAC                   = 65535,   // absent
    IMPORT_MATH_FRAND                  = 65535,   // absent
    IMPORT_MATH_INT                    = 65535,   // absent
    IMPORT_MATH_INT16                  = 65535,   // absent
    IMPORT_MATH_INT_D                  = 65535,   // absent
    IMPORT_MATH_LN                     = 65535,   // absent
    IMPORT_MATH_LOG                    = 65535,   // absent
    IMPORT_MATH_MOD                    = 65535,   // absent
    IMPORT_MATH_POW                    = 65535,   // absent
    IMPORT_MATH_ROUND                  = 65535,   // absent
    IMPORT_MATH_SIN                    = 65535,   // absent
    IMPORT_MATH_SQRT                   = 65535,   // absent
    IMPORT_MATH_TAN                    = 65535,   // absent
    IMPORT_MDA_NEWL                    = 65535,   // absent
    IMPORT_MKDIR                       = 65535,   // absent
    IMPORT_MSG_COMPLETE                = 65535,   // absent
    IMPORT_MULDF3                      = 65535,   // absent
    IMPORT_NEDF2                       = 65535,   // absent
    IMPORT_NEGDF2                      = 65535,   // absent
    IMPORT_PANIC                       =   474,
    IMPORT_PUSHL_CBASE                 =   480,
    IMPORT_READ_FILE_SECTION           = 65535,   // absent
    IMPORT_REQUEST_COMPLETE            =   483,
    IMPORT_RWIN_BEGIN_REDRAW           = 65535,   // absent
    IMPORT_RWIN_CTOR                   = 65535,   // absent
    IMPORT_RWIN_CTOR_WS                = 65535,   // absent
    IMPORT_RWIN_END_REDRAW             = 65535,   // absent
    IMPORT_SCREEN_INFO                 = 65535,   // absent
    IMPORT_SCREEN_UPDATE               = 65535,   // absent
    IMPORT_SDPDB_CLOSE                 = 65535,   // absent
    IMPORT_SDPDB_CREATE_RECORD         = 65535,   // absent
    IMPORT_SDPDB_CTOR                  = 65535,   // absent
    IMPORT_SDPDB_DELETE_RECORD         = 65535,   // absent
    IMPORT_SDPDB_OPEN                  = 65535,   // absent
    IMPORT_SDPDB_UPDATE_DES16          = 65535,   // absent
    IMPORT_SDPDB_UPDATE_UINT           = 65535,   // absent
    IMPORT_SDPDB_UPDATE_VALUE          = 65535,   // absent
    IMPORT_SDP_NEW_DES                 = 65535,   // absent
    IMPORT_SEM_CREATE                  = 65535,   // absent
    IMPORT_SEM_WAIT                    =   510,
    IMPORT_SEND_RECEIVE                =   490,
    IMPORT_SERVER_STARTL               = 65535,   // absent
    IMPORT_SET_AUTO_UPDATE             = 65535,   // absent
    IMPORT_SHADOW_BUFFLAT              =   467,
    IMPORT_SHADOW_CMDLINE              =     7,
    IMPORT_SHADOW_DESC16FLAT           =    58,
    IMPORT_SHADOW_DESC8FLAT            =    57,
    IMPORT_SHADOW_FILEMAN              = 65535,   // absent
    IMPORT_SHADOW_MSVSESSION           = 65535,   // absent
    IMPORT_SHADOW_PERIODIC             =   468,
    IMPORT_SHADOW_SCREENDEVICE         = 65535,   // absent
    IMPORT_SHADOW_SDPAGENT             = 65535,   // absent
    IMPORT_SHADOW_SDPPATTERN           = 65535,   // absent
    IMPORT_SHADOW_WGNAME               = 65535,   // absent
    IMPORT_SOCK_RECV1                  = 65535,   // absent
    IMPORT_SOCK_WRITE                  = 65535,   // absent
    IMPORT_START_APP                   =     1,
    IMPORT_SUBDF3                      = 65535,   // absent
    IMPORT_SYSTEM_GC                   =   109,
    IMPORT_THREAD_CREATE               = 65535,   // absent
    IMPORT_THREAD_OPEN                 = 65535,   // absent
    IMPORT_THREAD_RESUME               = 65535,   // absent
    IMPORT_THREAD_SUSPEND              = 65535,   // absent
    IMPORT_TRUNCDFSF2                  = 65535,   // absent
    IMPORT_UNLINK                      = 65535,   // absent
    IMPORT_USER_AFTER                  =   400,
    IMPORT_USER_ALLOC                  = 65535,   // absent
    IMPORT_USER_ALLOCL                 =   404,
    IMPORT_USER_ALLOCZ                 =   555,
    IMPORT_USER_ALLOCZL                =   398,
    IMPORT_USER_FREE_OP                = 65535,   // absent
    IMPORT_VEC_DELETE_OP               =   549,
    IMPORT_WAIT_FOR_REQUEST            =   509,
    IMPORT_WFOPEN                      = 65535,   // absent
    IMPORT_WINDOW                      = 65535,   // absent
    IMPORT_WS_EVENT_READY              = 65535,   // absent
    IMPORT_WS_GET_EVENT                = 65535,   // absent
};

// Imports that are a method on CCoeEnv. The game holds a copy of the
// environment laid out the old way; cone has to be given the real one.
//     70  CCoeEnv::CreateResourceReaderLC(TResourceReader &, int) const
//    274  CEikonEnv::NewDefaultCharFormatLayerL()
#define GATE_COEENV_METHODS  70, 274
#define GATE_COEENV_METHOD_COUNT 2

// Methods on CEikAppUi. A null `this` from the game is replaced
// with the real app UI, when the game asks for it (GAME_FIX_APPUI_THIS).
#define GATE_APPUI_METHODS  253, 257, 265, 267, 269, 270, 271, 278, 280, 284, 286, 287, 288, 293, 294
#define GATE_APPUI_METHOD_COUNT 15

// The trace lists: see MILESTONES and HOT in gen_shim.py. Both may be
// empty, which is why gate6.cpp appends the two exits to the first.
#define GATE_MILESTONES  580, 125, 128, 129, 124, 461, 427, 483, 510, 425, 457, 500, 442, 490, 126,
#define GATE_HOT  419, 414, 554, 520, 503, 526, 397,
#define GATE_HOT_COUNT 7

// The diversions: see DIVERTS in gen_shim.py. {import, register,
// which wrapper}, and an import the game does not have is left out.
#define GATE_DIVERTS  { 120, 0, 1 }, { 65, 0, 1 }, { 73, 0, 1 }, { 93, 1, 1 }, { 88, 0, 1 }, { 99, 1, 1 }, { 94, 1, 1 }, { 25, 0, 0 }, { 28, 0, 0 }, { 433, 0, 2 }, { 401, 0, 2 }, { 399, 0, 2 }, { 492, 0, 2 },
#define GATE_DIVERT_COUNT 13

#endif
