// Generated by gen_shim.py from ngtest.app -- do not edit.
//
// Which import index each diversion sits at in THIS game. See HOOKS in
// gen_shim.py for what each one is; 65535 means the game never imports it
// and the guards in gate6.cpp then leave that hook uninstalled.
//
// GAME_UID3 is the image these indices were read out of. The loader
// checks it against the image it is actually given, because this
// header and gate4_shim.cpp are generated as a pair from one game
// and are meaningless against another -- and a wrong index is not an
// error, it is a call to the wrong function.
#ifndef GATE_IMPORTS_H
#define GATE_IMPORTS_H

enum { GAME_UID3 = 0x10205e7a };

enum {
    IMPORT_ADDDF3                      = 65535,   // absent
    IMPORT_ADDTOSTACKL                 =    21,
    IMPORT_ADD_FOREGROUND_OBSERVER     = 65535,   // absent
    IMPORT_APPUI_EXIT                  =    81,
    IMPORT_APPUI_FACTORY               = 65535,   // absent
    IMPORT_APPUI_PREPARE_EXIT          =    14,
    IMPORT_APP_FULL_NAME               =     0,
    IMPORT_APP_RECT                    = 65535,   // absent
    IMPORT_BASECONSTRUCTL              =     4,
    IMPORT_CACTIVE_CTOR                =   171,
    IMPORT_CANCEL                      =   130,
    IMPORT_CLEANUP_NEW                 =   146,
    IMPORT_CLIENT_RECT                 =    72,
    IMPORT_COECONTROL_CTOR             =    56,
    IMPORT_COEENV_STATIC               = 65535,   // absent
    IMPORT_CREATEWINDOWL               =    25,
    IMPORT_CREATE_CONTEXT              = 65535,   // absent
    IMPORT_CREATE_SESSION              = 65535,   // absent
    IMPORT_CTIMER_CTOR                 = 65535,   // absent
    IMPORT_CTIMER_DOCANCEL             = 65535,   // absent
    IMPORT_CTIMER_DTOR                 = 65535,   // absent
    IMPORT_CTL_DRAWABLE_WINDOW         = 65535,   // absent
    IMPORT_CTL_RECT                    =    43,
    IMPORT_CTL_SETRECT                 = 65535,   // absent
    IMPORT_DELETE_OP                   =   174,
    IMPORT_DES_FORMAT                  =   141,
    IMPORT_DES_FORMATLIST              =   140,
    IMPORT_DIVDF3                      = 65535,   // absent
    IMPORT_DLL_NAME                    = 65535,   // absent
    IMPORT_DSA_NEWL                    = 65535,   // absent
    IMPORT_DSA_STARTL                  = 65535,   // absent
    IMPORT_EQDF2                       = 65535,   // absent
    IMPORT_EXIT                        =   137,
    IMPORT_EXTENDSFDF2                 = 65535,   // absent
    IMPORT_FILEMAN_NEWL                = 65535,   // absent
    IMPORT_FILE_CREATE                 = 65535,   // absent
    IMPORT_FILE_OPEN                   = 65535,   // absent
    IMPORT_FILE_READ                   = 65535,   // absent
    IMPORT_FILE_READ_POS               = 65535,   // absent
    IMPORT_FILE_READ_STATIC            = 65535,   // absent
    IMPORT_FILE_REPLACE                =    67,
    IMPORT_FILE_SIZE                   = 65535,   // absent
    IMPORT_FIND_WILD_BY_DIR            = 65535,   // absent
    IMPORT_FIXDFSI                     = 65535,   // absent
    IMPORT_FLOATSIDF                   = 65535,   // absent
    IMPORT_FS_CONNECT                  =    65,
    IMPORT_FS_ENTRY                    = 65535,   // absent
    IMPORT_FS_SET_DEFAULT_PATH         = 65535,   // absent
    IMPORT_FS_VOLUME                   = 65535,   // absent
    IMPORT_GEDF2                       = 65535,   // absent
    IMPORT_GTDF2                       = 65535,   // absent
    IMPORT_HANDLE_CLOSE                =   131,
    IMPORT_LEAVE                       = 65535,   // absent
    IMPORT_LEAVE_IF_ERROR              =   143,
    IMPORT_LEAVE_NOMEM                 = 65535,   // absent
    IMPORT_LEDF2                       = 65535,   // absent
    IMPORT_LEX16_VAL_REAL              = 65535,   // absent
    IMPORT_LIBRARY_LOAD                = 65535,   // absent
    IMPORT_LIBRARY_LOOKUP              = 65535,   // absent
    IMPORT_LTDF2                       = 65535,   // absent
    IMPORT_MALLOC                      = 65535,   // absent
    IMPORT_MATH_ACOS                   = 65535,   // absent
    IMPORT_MATH_ASIN                   = 65535,   // absent
    IMPORT_MATH_ATAN                   = 65535,   // absent
    IMPORT_MATH_ATAN2                  = 65535,   // absent
    IMPORT_MATH_COS                    = 65535,   // absent
    IMPORT_MATH_EXP                    = 65535,   // absent
    IMPORT_MATH_FRAC                   = 65535,   // absent
    IMPORT_MATH_FRAND                  = 65535,   // absent
    IMPORT_MATH_INT                    = 65535,   // absent
    IMPORT_MATH_INT16                  = 65535,   // absent
    IMPORT_MATH_INT_D                  = 65535,   // absent
    IMPORT_MATH_LN                     = 65535,   // absent
    IMPORT_MATH_LOG                    = 65535,   // absent
    IMPORT_MATH_MOD                    = 65535,   // absent
    IMPORT_MATH_POW                    = 65535,   // absent
    IMPORT_MATH_ROUND                  = 65535,   // absent
    IMPORT_MATH_SIN                    = 65535,   // absent
    IMPORT_MATH_SQRT                   = 65535,   // absent
    IMPORT_MATH_TAN                    = 65535,   // absent
    IMPORT_MDA_NEWL                    =   180,
    IMPORT_MSG_COMPLETE                = 65535,   // absent
    IMPORT_MULDF3                      = 65535,   // absent
    IMPORT_NEDF2                       = 65535,   // absent
    IMPORT_NEGDF2                      = 65535,   // absent
    IMPORT_PANIC                       = 65535,   // absent
    IMPORT_PUSHL_CBASE                 =   150,
    IMPORT_READ_FILE_SECTION           = 65535,   // absent
    IMPORT_REQUEST_COMPLETE            =   151,
    IMPORT_SCREEN_INFO                 = 65535,   // absent
    IMPORT_SCREEN_UPDATE               = 65535,   // absent
    IMPORT_SEM_CREATE                  = 65535,   // absent
    IMPORT_SEM_WAIT                    = 65535,   // absent
    IMPORT_SEND_RECEIVE                = 65535,   // absent
    IMPORT_SERVER_STARTL               = 65535,   // absent
    IMPORT_SET_AUTO_UPDATE             = 65535,   // absent
    IMPORT_SUBDF3                      = 65535,   // absent
    IMPORT_SYSTEM_GC                   =    54,
    IMPORT_THREAD_CREATE               = 65535,   // absent
    IMPORT_THREAD_OPEN                 = 65535,   // absent
    IMPORT_THREAD_RESUME               =   152,
    IMPORT_THREAD_SUSPEND              = 65535,   // absent
    IMPORT_TRUNCDFSF2                  = 65535,   // absent
    IMPORT_USER_ALLOC                  = 65535,   // absent
    IMPORT_USER_ALLOCL                 = 65535,   // absent
    IMPORT_USER_ALLOCZ                 =   178,
    IMPORT_USER_ALLOCZL                =   124,
    IMPORT_USER_FREE_OP                = 65535,   // absent
    IMPORT_VEC_DELETE_OP               = 65535,   // absent
    IMPORT_WINDOW                      = 65535,   // absent
};

// Imports that are a method on CCoeEnv. The game holds a copy of the
// environment laid out the old way; cone has to be given the real one.
#define GATE_COEENV_METHODS  /* none */
#define GATE_COEENV_METHOD_COUNT 0

// Methods on CEikAppUi. A null `this` from the game is replaced
// with the real app UI, when the game asks for it (GAME_FIX_APPUI_THIS).
#define GATE_APPUI_METHODS  73, 76, 84, 86, 88, 89, 90, 96, 98, 102, 104, 105, 106, 111, 112
#define GATE_APPUI_METHOD_COUNT 15

// The trace lists: see MILESTONES and HOT in gen_shim.py. Both may be
// empty, which is why gate6.cpp appends the two exits to the first.
#define GATE_MILESTONES  65, 64, 151, 152, 131, 146, 166, 142, 143, 156, 180, 67, 66,
#define GATE_HOT  165, 168,
#define GATE_HOT_COUNT 2

// The diversions: see DIVERTS in gen_shim.py. {import, register,
// which wrapper}, and an import the game does not have is left out.
#define GATE_DIVERTS  { 72, 1, 0 }, { 20, 0, 1 }, { 43, 1, 1 }, { 38, 0, 1 }, { 49, 1, 1 }, { 44, 1, 1 }, { 6, 0, 0 }, { 8, 0, 0 }, { 125, 0, 2 }, { 154, 0, 2 },
#define GATE_DIVERT_COUNT 10

#endif
